SELECT TRANCHE_ALLOWED_ORDER_SPREAD AS SPREAD_, COUNT(*) AS TRANCHES_
FROM   DGSTREAM.OB_DEAL_TRANCHE
GROUP  BY TRANCHE_ALLOWED_ORDER_SPREAD ORDER BY TRANCHES_ DESC;

SELECT TRANCHE_ALLOWED_ORDER_YIELD AS YIELD_, COUNT(*) AS TRANCHES_
FROM   DGSTREAM.OB_DEAL_TRANCHE
GROUP  BY TRANCHE_ALLOWED_ORDER_YIELD ORDER BY TRANCHES_ DESC;

SELECT TRANCHE_ALLOWED_ORDER_MAX_PRICE AS MAX_PRICE_, COUNT(*) AS TRANCHES_
FROM   DGSTREAM.OB_DEAL_TRANCHE
GROUP  BY TRANCHE_ALLOWED_ORDER_MAX_PRICE ORDER BY TRANCHES_ DESC
FETCH  FIRST 15 ROWS ONLY;

SELECT DEAL_ID, TRANCHE_ID, NAME,
       TRANCHE_ALLOWED_ORDER_SPREAD, TRANCHE_ALLOWED_ORDER_YIELD,
       TRANCHE_ALLOWED_ORDER_MAX_PRICE
FROM   DGSTREAM.OB_DEAL_TRANCHE
WHERE  ORIGINATION_TRANSACTION_ID = '75043505';
