SELECT table_name, column_name, data_type
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM'
AND    table_name IN ('OB_DEAL_TRANCHE', 'OB_TRANCHE', 'OB_ORDER', 'OB_ORDER_TRADE')
AND   (column_name LIKE '%ALLOW%' OR column_name LIKE '%ORDER_TYPE%'
       OR column_name LIKE '%ORDERTYPE%' OR column_name LIKE '%PRICE_TYPE%'
       OR column_name LIKE '%PRICING_TYPE%' OR column_name LIKE '%BASIS%'
       OR column_name LIKE '%SPREAD%' OR column_name LIKE '%YIELD%')
ORDER  BY table_name, column_name;

SELECT table_name, COUNT(*) AS COLS_
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM' AND table_name LIKE 'OB_%TRANCHE%'
GROUP  BY table_name
ORDER  BY table_name;

SELECT DT.DEAL_ID, DT.TRANCHE_ID, DT.NAME, DT.COUPON_TYPE, DT.PRICE_GUIDANCE,
       DT.FRN_COUPON_INDEX
FROM   DGSTREAM.OB_DEAL_TRANCHE DT
WHERE  DT.ORIGINATION_TRANSACTION_ID = '75043505';

SELECT T.PARENT_ID AS TRANCHE_ID, T.PRICE_BASIS_CODE, COUNT(*) AS TRADES_
FROM   DGSTREAM.OB_ORDER_TRADE T
WHERE  T.ROOT_ID IN (SELECT DEAL_ID FROM DGSTREAM.OB_DEAL_TRANCHE
                     WHERE ORIGINATION_TRANSACTION_ID = '75043505')
GROUP  BY T.PARENT_ID, T.PRICE_BASIS_CODE
ORDER  BY T.PARENT_ID, TRADES_ DESC;

SELECT PRICE_BASIS_CODE, COUNT(*) AS TRADES_
FROM   DGSTREAM.OB_ORDER_TRADE
GROUP  BY PRICE_BASIS_CODE
ORDER  BY TRADES_ DESC;
