SELECT 'OB_ECM_ORDER' AS SRC, INVESTOR_CLASSIFICATION_VALUE AS VALUE_, COUNT(*) AS ROWS_
FROM DGSTREAM.OB_ECM_ORDER
WHERE INVESTOR_CLASSIFICATION_VALUE IS NOT NULL
GROUP BY INVESTOR_CLASSIFICATION_VALUE
UNION ALL
SELECT 'OB_ORDER', INVESTOR_CLASSIFICATION, COUNT(*)
FROM DGSTREAM.OB_ORDER
WHERE INVESTOR_CLASSIFICATION IS NOT NULL
GROUP BY INVESTOR_CLASSIFICATION
ORDER BY 1, 3 DESC;
