SELECT DEAL_ID, TRANCHE_ID, TRANCHE_NAME, TENORS, CURRENCY,
       IDENTIFIER_TYPE, IDENTIFIER_VALUE
FROM   DGSTREAM.VW_TRANCHE_SUMMARY
WHERE  UPPER(IDENTIFIER_VALUE) LIKE '%63307A3T0%'
ORDER  BY DEAL_ID, TRANCHE_ID;

SELECT T.DEAL_TRANCHE_ID, T.TYPE, T.VALUE
FROM   DGSTREAM.OB_TRANCHE T
WHERE  UPPER(T.VALUE) LIKE '%63307A3T0%'
ORDER  BY T.DEAL_TRANCHE_ID, T.TYPE;

SELECT COUNT(*) AS CUSIPS_ON_MULTIPLE_TRANCHES,
       SUM(N_TRANCHES) AS TRANCHE_ROWS_INVOLVED
FROM  (SELECT UPPER(VALUE) AS V, COUNT(DISTINCT DEAL_TRANCHE_ID) AS N_TRANCHES
       FROM   DGSTREAM.OB_TRANCHE
       WHERE  UPPER(TYPE) = 'CUSIP'
       GROUP  BY UPPER(VALUE)
       HAVING COUNT(DISTINCT DEAL_TRANCHE_ID) > 1);

SELECT COUNT(DISTINCT UPPER(VALUE)) AS DISTINCT_CUSIPS,
       COUNT(DISTINCT DEAL_TRANCHE_ID) AS TRANCHES_WITH_A_CUSIP
FROM   DGSTREAM.OB_TRANCHE
WHERE  UPPER(TYPE) = 'CUSIP';

SELECT TRANCHE_ID, CURRENCY,
       COUNT(*)              AS ORDERS_,
       SUM(ORDER_DEMAND_QTY) AS DEMAND_,
       SUM(ORDER_ALLOCATION) AS ALLOCATION_
FROM   DGSTREAM.VW_ORDER_DETAIL
WHERE  PRODUCT = 'DCM'
AND    TRANCHE_ID IN ('I-260831-113901749968',
                      'I-260828-133124755115',
                      'I-260901-111645995584')
GROUP  BY TRANCHE_ID, CURRENCY
ORDER  BY TRANCHE_ID;
