SELECT I.TABLE_NAME,
       I.INDEX_NAME,
       I.INDEX_TYPE,
       I.UNIQUENESS,
       I.STATUS,
       LISTAGG(C.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY C.COLUMN_POSITION) AS INDEX_COLUMNS
FROM ALL_INDEXES I
JOIN ALL_IND_COLUMNS C
  ON C.INDEX_OWNER = I.OWNER
 AND C.INDEX_NAME  = I.INDEX_NAME
 AND C.TABLE_NAME  = I.TABLE_NAME
WHERE I.TABLE_OWNER = 'DGSTREAM'
  AND I.TABLE_NAME IN (
      'OB_ORDER','OB_ORDER_SIZE','OB_ORDER_TRADE','OB_ORDER_TRADE_SYNDICATE',
      'OB_HEDGE_ORDER','OB_HEDGE_TRADE',
      'OB_DEAL_TRANCHE','OB_DEAL_ISSUER','OB_TRANCHE','OB_TRANCHE_RATING',
      'OB_TRANCHE_SYNDICATE_MEMBER',
      'OB_ECM_ORDER','OB_ECM_ORDER_IOI',
      'OB_ECM_TRADE_BOOK_INVESTOR_TRADE','OB_ECM_TRADE_BOOK_DESIGNATION',
      'OPUS_ECM_TRANSACTION','OPUS_ECM_TRANSACTION_STATUS',
      'OPUS_ECM_TRANSACTION_TRANCHE',
      'OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY',
      'OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL',
      'OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL_IDENTIFIER',
      'OPUS_ECM_TRANSACTION_TRANCHE_SYNDICATE',
      'OPUS_BASE_TRANSACTION','OPUS_BASE_TRANSACTION_RELATED_PARTIES')
GROUP BY I.TABLE_NAME, I.INDEX_NAME, I.INDEX_TYPE, I.UNIQUENESS, I.STATUS
ORDER BY I.TABLE_NAME, I.INDEX_NAME;

SELECT T.TABLE_NAME,
       T.NUM_ROWS,
       T.BLOCKS,
       T.LAST_ANALYZED
FROM ALL_TABLES T
WHERE T.OWNER = 'DGSTREAM'
  AND T.TABLE_NAME IN (
      'OB_ORDER','OB_ORDER_SIZE','OB_ORDER_TRADE','OB_ORDER_TRADE_SYNDICATE',
      'OB_HEDGE_ORDER','OB_HEDGE_TRADE',
      'OB_DEAL_TRANCHE','OB_DEAL_ISSUER','OB_TRANCHE','OB_TRANCHE_RATING',
      'OB_TRANCHE_SYNDICATE_MEMBER',
      'OB_ECM_ORDER','OB_ECM_ORDER_IOI',
      'OB_ECM_TRADE_BOOK_INVESTOR_TRADE','OB_ECM_TRADE_BOOK_DESIGNATION',
      'OPUS_ECM_TRANSACTION','OPUS_ECM_TRANSACTION_STATUS',
      'OPUS_ECM_TRANSACTION_TRANCHE',
      'OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY',
      'OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL',
      'OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL_IDENTIFIER',
      'OPUS_ECM_TRANSACTION_TRANCHE_SYNDICATE',
      'OPUS_BASE_TRANSACTION','OPUS_BASE_TRANSACTION_RELATED_PARTIES')
ORDER BY T.TABLE_NAME;

SELECT E.TABLE_NAME,
       E.INDEX_NAME,
       E.COLUMN_POSITION,
       E.COLUMN_EXPRESSION
FROM ALL_IND_EXPRESSIONS E
WHERE E.TABLE_OWNER = 'DGSTREAM'
  AND E.TABLE_NAME IN (
      'OB_ORDER','OB_ORDER_SIZE','OB_ORDER_TRADE','OB_ORDER_TRADE_SYNDICATE',
      'OB_HEDGE_ORDER','OB_HEDGE_TRADE',
      'OB_DEAL_TRANCHE','OB_DEAL_ISSUER','OB_TRANCHE','OB_TRANCHE_RATING',
      'OB_TRANCHE_SYNDICATE_MEMBER',
      'OB_ECM_ORDER','OB_ECM_ORDER_IOI',
      'OB_ECM_TRADE_BOOK_INVESTOR_TRADE','OB_ECM_TRADE_BOOK_DESIGNATION',
      'OPUS_ECM_TRANSACTION','OPUS_ECM_TRANSACTION_STATUS',
      'OPUS_ECM_TRANSACTION_TRANCHE',
      'OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY',
      'OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL',
      'OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL_IDENTIFIER',
      'OPUS_ECM_TRANSACTION_TRANCHE_SYNDICATE',
      'OPUS_BASE_TRANSACTION','OPUS_BASE_TRANSACTION_RELATED_PARTIES')
ORDER BY E.TABLE_NAME, E.INDEX_NAME, E.COLUMN_POSITION;

SELECT 'OB_ORDER' AS TBL,
       COUNT(*) AS IDS_WITH_MULTIPLE_PARENT_KEYS
FROM (SELECT ORDER_ID
      FROM DGSTREAM.OB_ORDER
      GROUP BY ORDER_ID
      HAVING COUNT(DISTINCT ROOT_ID || '~' || PARENT_ID) > 1)
UNION ALL
SELECT 'OB_ORDER_TRADE',
       COUNT(*)
FROM (SELECT ORDER_TRADE_ID
      FROM DGSTREAM.OB_ORDER_TRADE
      GROUP BY ORDER_TRADE_ID
      HAVING COUNT(DISTINCT ROOT_ID) > 1)
UNION ALL
SELECT 'OB_HEDGE_ORDER',
       COUNT(*)
FROM (SELECT HEDGE_ORDER_ID
      FROM DGSTREAM.OB_HEDGE_ORDER
      GROUP BY HEDGE_ORDER_ID
      HAVING COUNT(DISTINCT ROOT_ID) > 1)
UNION ALL
SELECT 'OB_HEDGE_TRADE',
       COUNT(*)
FROM (SELECT HEDGE_TRADE_ID
      FROM DGSTREAM.OB_HEDGE_TRADE
      GROUP BY HEDGE_TRADE_ID
      HAVING COUNT(DISTINCT ROOT_ID) > 1)
UNION ALL
SELECT 'OB_ECM_ORDER',
       COUNT(*)
FROM (SELECT ORDER_ID
      FROM DGSTREAM.OB_ECM_ORDER
      GROUP BY ORDER_ID
      HAVING COUNT(DISTINCT DEAL_ID || '~' || TRANCHE_ID) > 1);
