SELECT column_name, data_type, data_precision, data_scale
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM' AND table_name = 'OB_ECM_ORDER_IOI'
ORDER  BY column_id;

SELECT O.ORDER_ID,
       O.INVESTOR_NAME,
       O.INVESTOR_GPNUM,
       O.DEMAND_QTY,
       O.ORDER_STATUS,
       O.IS_MATCHED,
       O.IS_DOMINANT,
       O.IS_OWNED
FROM   DGSTREAM.OB_ECM_ORDER O
WHERE  O.INVESTOR_GPNUM = '48326'
ORDER  BY O.ORDER_ID;

SELECT I.*
FROM   DGSTREAM.OB_ECM_ORDER_IOI I
WHERE  I.ORDER_ID IN (SELECT O.ORDER_ID
                      FROM DGSTREAM.OB_ECM_ORDER O
                      WHERE O.INVESTOR_GPNUM = '48326')
FETCH FIRST 20 ROWS ONLY;

SELECT COUNT(*) AS IOI_ROWS,
       COUNT(LIMIT_VALUE) AS WITH_LIMIT_VALUE,
       MIN(LIMIT_VALUE) AS MIN_LIMIT,
       MEDIAN(LIMIT_VALUE) AS MEDIAN_LIMIT,
       MAX(LIMIT_VALUE) AS MAX_LIMIT
FROM   DGSTREAM.OB_ECM_ORDER_IOI;

SELECT COUNT(*) AS ECM_ORDERS,
       COUNT(DEMAND_QTY) AS WITH_DEMAND,
       MIN(DEMAND_QTY) AS MIN_DEMAND,
       MEDIAN(DEMAND_QTY) AS MEDIAN_DEMAND,
       MAX(DEMAND_QTY) AS MAX_DEMAND
FROM   DGSTREAM.OB_ECM_ORDER;

SELECT I.*
FROM   DGSTREAM.OB_ECM_ORDER_IOI I
WHERE  I.ORDER_ID IN (SELECT O.ORDER_ID
                      FROM DGSTREAM.OB_ECM_ORDER O
                      WHERE O.INVESTOR_GPNUM = '59271')
ORDER  BY I.ORDER_ID, I.LIMIT_VALUE
FETCH FIRST 30 ROWS ONLY;

SELECT POINTS_PER_ORDER, COUNT(*) AS ORDERS_
FROM (SELECT ORDER_ID, COUNT(*) AS POINTS_PER_ORDER
      FROM DGSTREAM.OB_ECM_ORDER_IOI
      GROUP BY ORDER_ID)
GROUP BY POINTS_PER_ORDER
ORDER BY POINTS_PER_ORDER;

SELECT COUNT(*) AS ORDERS_WITH_IOI,
       COUNT(CASE WHEN O.DEMAND_QTY IS NOT NULL THEN 1 END) AS ALSO_HAS_DEMAND_QTY,
       COUNT(CASE WHEN O.DEMAND_QTY IS NULL THEN 1 END) AS IOI_ONLY
FROM   DGSTREAM.OB_ECM_ORDER O
WHERE  EXISTS (SELECT 1 FROM DGSTREAM.OB_ECM_ORDER_IOI I
               WHERE I.ORDER_ID = O.ORDER_ID);
