SELECT column_name, data_type, data_precision, data_scale
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM' AND table_name = 'OB_ECM_ORDER'
AND   (column_name LIKE '%IOI%' OR column_name LIKE '%UNIT%'
       OR column_name LIKE '%DEMAND%')
ORDER  BY column_id;

SELECT O.IOI_TYPE,
       O.IOI_UNIT,
       COUNT(*)                AS ORDERS_,
       MIN(I.IOI_QTY)          AS MIN_QTY,
       MEDIAN(I.IOI_QTY)       AS MEDIAN_QTY,
       MAX(I.IOI_QTY)          AS MAX_QTY
FROM   DGSTREAM.OB_ECM_ORDER O
JOIN   DGSTREAM.OB_ECM_ORDER_IOI I ON I.ORDER_ID = O.ORDER_ID
GROUP  BY O.IOI_TYPE, O.IOI_UNIT
ORDER  BY ORDERS_ DESC;

SELECT COUNT(*) AS ORDERS_WHOSE_POINTS_SUM_TO_100
FROM  (SELECT ORDER_ID, SUM(IOI_QTY) AS S
       FROM   DGSTREAM.OB_ECM_ORDER_IOI
       GROUP  BY ORDER_ID
       HAVING ROUND(SUM(IOI_QTY), 4) = 100);

SELECT COUNT(*)                                        AS IOI_ROWS,
       COUNT(IOI_QTY)                                  AS WITH_QTY,
       COUNT(CASE WHEN IOI_QTY >= 1000000000 THEN 1 END) AS SENTINEL_1E9_PLUS,
       COUNT(CASE WHEN IOI_QTY <> TRUNC(IOI_QTY) THEN 1 END) AS FRACTIONAL_QTY,
       MIN(IOI_QTY) AS MIN_QTY, MEDIAN(IOI_QTY) AS MEDIAN_QTY,
       MAX(IOI_QTY) AS MAX_QTY
FROM   DGSTREAM.OB_ECM_ORDER_IOI;

SELECT COUNT(*) AS ORDERS_WITH_BOTH,
       COUNT(CASE WHEN O.DEMAND_QTY = X.TOP_QTY THEN 1 END) AS DEMAND_EQ_TOP_POINT,
       COUNT(CASE WHEN O.DEMAND_QTY = X.SUM_QTY THEN 1 END) AS DEMAND_EQ_SUM,
       COUNT(CASE WHEN O.DEMAND_QTY = X.MAX_QTY THEN 1 END) AS DEMAND_EQ_MAX
FROM   DGSTREAM.OB_ECM_ORDER O
JOIN  (SELECT ORDER_ID,
              SUM(IOI_QTY) AS SUM_QTY,
              MAX(IOI_QTY) AS MAX_QTY,
              MAX(IOI_QTY) KEEP (DENSE_RANK FIRST
                   ORDER BY LIMIT_VALUE ASC NULLS FIRST) AS TOP_QTY
       FROM   DGSTREAM.OB_ECM_ORDER_IOI
       GROUP  BY ORDER_ID) X ON X.ORDER_ID = O.ORDER_ID
WHERE  O.DEMAND_QTY IS NOT NULL;
