SELECT COUNT(*)                                              AS MULTIPOINT_WITH_DEMAND,
       COUNT(CASE WHEN O.DEMAND_QTY = X.TOP_QTY THEN 1 END)  AS EQ_TOP_LOWEST_PRICE,
       COUNT(CASE WHEN O.DEMAND_QTY = X.BOTTOM_QTY THEN 1 END) AS EQ_HIGHEST_PRICE,
       COUNT(CASE WHEN O.DEMAND_QTY = X.SUM_QTY THEN 1 END)  AS EQ_SUM,
       COUNT(CASE WHEN O.DEMAND_QTY = X.MAX_QTY THEN 1 END)  AS EQ_MAX
FROM   DGSTREAM.OB_ECM_ORDER O
JOIN  (SELECT ORDER_ID,
              COUNT(*)     AS N_POINTS,
              SUM(IOI_QTY) AS SUM_QTY,
              MAX(IOI_QTY) AS MAX_QTY,
              MAX(IOI_QTY) KEEP (DENSE_RANK FIRST
                   ORDER BY LIMIT_VALUE ASC NULLS FIRST) AS TOP_QTY,
              MAX(IOI_QTY) KEEP (DENSE_RANK LAST
                   ORDER BY LIMIT_VALUE ASC NULLS FIRST) AS BOTTOM_QTY
       FROM   DGSTREAM.OB_ECM_ORDER_IOI
       GROUP  BY ORDER_ID
       HAVING COUNT(*) > 1) X ON X.ORDER_ID = O.ORDER_ID
WHERE  O.DEMAND_QTY IS NOT NULL;

SELECT O.IOI_UNIT,
       COUNT(*)                                             AS ORDERS_WITH_BOTH,
       COUNT(CASE WHEN O.DEMAND_QTY = X.TOP_QTY THEN 1 END) AS DEMAND_EQ_TOP,
       COUNT(CASE WHEN O.DEMAND_QTY <> X.TOP_QTY THEN 1 END) AS DEMAND_DIFFERS
FROM   DGSTREAM.OB_ECM_ORDER O
JOIN  (SELECT ORDER_ID,
              MAX(IOI_QTY) KEEP (DENSE_RANK FIRST
                   ORDER BY LIMIT_VALUE ASC NULLS FIRST) AS TOP_QTY
       FROM   DGSTREAM.OB_ECM_ORDER_IOI
       GROUP  BY ORDER_ID) X ON X.ORDER_ID = O.ORDER_ID
WHERE  O.DEMAND_QTY IS NOT NULL
GROUP  BY O.IOI_UNIT
ORDER  BY ORDERS_WITH_BOTH DESC;

SELECT COUNT(DISTINCT O.DEAL_ID) AS DEALS_,
       COUNT(*) AS ORDERS_,
       COUNT(CASE WHEN O.IOI_UNIT = 'SHARES' THEN 1 END) AS SHARES_ORDERS,
       ROUND(100 * COUNT(CASE WHEN O.IOI_UNIT = 'SHARES' THEN 1 END)
             / COUNT(*), 1) AS PCT_SHARES
FROM   DGSTREAM.OB_ECM_ORDER O
WHERE  O.ORDER_STATUS NOT IN ('CANCELLED', 'DELETED', 'PASS');

SELECT O.DEAL_ID,
       COUNT(*) AS ORDERS_,
       COUNT(DISTINCT O.IOI_UNIT) AS DISTINCT_UNITS,
       LISTAGG(DISTINCT O.IOI_UNIT, ' | ') WITHIN GROUP (ORDER BY O.IOI_UNIT) AS UNITS_
FROM   DGSTREAM.OB_ECM_ORDER O
WHERE  O.ORDER_STATUS NOT IN ('CANCELLED', 'DELETED', 'PASS')
GROUP  BY O.DEAL_ID
HAVING COUNT(DISTINCT O.IOI_UNIT) > 1
ORDER  BY DISTINCT_UNITS DESC, ORDERS_ DESC
FETCH  FIRST 15 ROWS ONLY;
