SELECT O.IOI_UNIT,
       COUNT(*)                                             AS ORDERS_WITH_BOTH,
       COUNT(CASE WHEN O.DEMAND_QTY = X.MAX_QTY THEN 1 END) AS DEMAND_EQ_MAX,
       COUNT(CASE WHEN O.DEMAND_QTY = X.TOP_QTY THEN 1 END) AS DEMAND_EQ_TOP
FROM   DGSTREAM.OB_ECM_ORDER O
JOIN  (SELECT ORDER_ID,
              MAX(IOI_QTY) AS MAX_QTY,
              MAX(IOI_QTY) KEEP (DENSE_RANK FIRST
                   ORDER BY LIMIT_VALUE ASC NULLS FIRST) AS TOP_QTY
       FROM   DGSTREAM.OB_ECM_ORDER_IOI
       GROUP  BY ORDER_ID) X ON X.ORDER_ID = O.ORDER_ID
WHERE  O.DEMAND_QTY IS NOT NULL
GROUP  BY O.IOI_UNIT
ORDER  BY ORDERS_WITH_BOTH DESC;

SELECT COUNT(*) AS MULTIPOINT_SHARES_WITH_DEMAND,
       COUNT(CASE WHEN O.DEMAND_QTY = X.MAX_QTY THEN 1 END) AS EQ_MAX,
       COUNT(CASE WHEN O.DEMAND_QTY = X.TOP_QTY THEN 1 END) AS EQ_TOP
FROM   DGSTREAM.OB_ECM_ORDER O
JOIN  (SELECT ORDER_ID, COUNT(*) AS N,
              MAX(IOI_QTY) AS MAX_QTY,
              MAX(IOI_QTY) KEEP (DENSE_RANK FIRST
                   ORDER BY LIMIT_VALUE ASC NULLS FIRST) AS TOP_QTY
       FROM   DGSTREAM.OB_ECM_ORDER_IOI
       GROUP  BY ORDER_ID HAVING COUNT(*) > 1) X ON X.ORDER_ID = O.ORDER_ID
WHERE  O.DEMAND_QTY IS NOT NULL AND O.IOI_UNIT IN ('SHARES','BOND');

SELECT COUNT(*) AS LIVE_ORDERS,
       COUNT(CASE WHEN O.DEMAND_QTY IS NOT NULL THEN 1 END) AS HAS_DEMAND_TODAY,
       COUNT(CASE WHEN O.DEMAND_QTY IS NOT NULL
                    OR O.IOI_UNIT IN ('SHARES','BOND') THEN 1 END) AS COVERED_AFTER_FIX
FROM   DGSTREAM.OB_ECM_ORDER O
WHERE  O.ORDER_STATUS NOT IN ('CANCELLED','DELETED','PASS');
