SELECT COUNT(DISTINCT ET.DEAL_TRANSACTION_ID) AS ECM_DEALS,
       COUNT(DISTINCT CASE WHEN ET.ISSUER_GFCID IS NULL
                            AND RP.PARTY_GFCID IS NOT NULL
                           THEN ET.DEAL_TRANSACTION_ID END) AS GFCID_LOST,
       COUNT(DISTINCT CASE WHEN ET.ISSUER_TICKER IS NULL
                            AND RP.PARTY_TICKER IS NOT NULL
                           THEN ET.DEAL_TRANSACTION_ID END) AS TICKER_LOST,
       COUNT(DISTINCT CASE WHEN RP.PARTY_NAME IS NOT NULL
                            AND UPPER(TRIM(RP.PARTY_NAME)) <>
                                UPPER(TRIM(ET.ISSUER_NAME_FROM_SOURCE))
                           THEN ET.DEAL_TRANSACTION_ID END) AS NAME_DIFFERS
FROM (SELECT DISTINCT DEAL_TRANSACTION_ID, ISSUER_GFCID, ISSUER_TICKER,
             ISSUER_NAME_FROM_SOURCE
      FROM DGSTREAM.OPUS_ECM_TRANSACTION
      WHERE DEAL_TRANSACTION_ID IS NOT NULL) ET
LEFT JOIN (
    SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER
    FROM (
        SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER,
               ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID
                                  ORDER BY PUBLISHED_TS DESC) AS RN_
        FROM DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES
        WHERE PARTY_ROLE = 'Primary Client'
    ) WHERE RN_ = 1
) RP
    ON RP.TRANSACTION_ID = ET.DEAL_TRANSACTION_ID;

SELECT COUNT(DISTINCT D.DEAL_ID) AS DCM_DEALS_WITH_TXN_LINK,
       COUNT(DISTINCT CASE WHEN D.GFCID IS NULL
                            AND RP.PARTY_GFCID IS NOT NULL
                           THEN D.DEAL_ID END) AS GFCID_LOST,
       COUNT(DISTINCT CASE WHEN RP.PARTY_NAME IS NOT NULL
                            AND UPPER(TRIM(RP.PARTY_NAME)) <>
                                UPPER(TRIM(D.ISSUER_NAME))
                           THEN D.DEAL_ID END) AS NAME_DIFFERS
FROM (
    SELECT DT.DEAL_ID,
           MAX(DT.ORIGINATION_TRANSACTION_ID) AS TXN_ID,
           MAX(DI.GFCID) AS GFCID,
           MAX(DI.NAME) AS ISSUER_NAME
    FROM DGSTREAM.OB_DEAL_TRANCHE DT
    LEFT JOIN DGSTREAM.OB_DEAL_ISSUER DI
        ON DI.DEAL_TRANCHE_ID = DT.DEAL_ID || '-' || DT.TRANCHE_ID
    WHERE DT.ORIGINATION_TRANSACTION_ID IS NOT NULL
    GROUP BY DT.DEAL_ID
) D
JOIN (
    SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID
    FROM (
        SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID,
               ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID
                                  ORDER BY PUBLISHED_TS DESC) AS RN_
        FROM DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES
        WHERE PARTY_ROLE = 'Primary Client'
    ) WHERE RN_ = 1
) RP
    ON RP.TRANSACTION_ID = D.TXN_ID;
