SELECT 'OB_ORDER_SIZE.AMT' AS COL,
       COUNT(AMT) AS NONNULL_,
       COUNT(CASE WHEN AMT <> ROUND(AMT, 4) THEN 1 END) AS SCALE_GT4,
       COUNT(CASE WHEN AMT <> ROUND(AMT, 9) THEN 1 END) AS SCALE_GT9,
       MAX(CASE WHEN AMT <> ROUND(AMT, 4) THEN AMT END) AS SAMPLE_GT4
FROM DGSTREAM.OB_ORDER_SIZE;

SELECT COUNT(FINAL_ALLOC) AS ALLOC_NONNULL,
       COUNT(CASE WHEN FINAL_ALLOC <> ROUND(FINAL_ALLOC, 4) THEN 1 END) AS ALLOC_GT4,
       COUNT(CASE WHEN FINAL_ALLOC <> ROUND(FINAL_ALLOC, 9) THEN 1 END) AS ALLOC_GT9,
       COUNT(CASE WHEN ORDER_SIZE_CHANGE <> ROUND(ORDER_SIZE_CHANGE, 4) THEN 1 END) AS SIZECHG_GT4
FROM DGSTREAM.OB_ORDER;

SELECT COUNT(CASE WHEN DEMAND_QTY <> ROUND(DEMAND_QTY, 4) THEN 1 END) AS DEMAND_GT4,
       COUNT(CASE WHEN PRIVATE_ALLOC <> ROUND(PRIVATE_ALLOC, 4) THEN 1 END) AS ALLOC_GT4,
       COUNT(CASE WHEN ACTIVE_PRICE <> ROUND(ACTIVE_PRICE, 6) THEN 1 END) AS PRICE_GT6
FROM DGSTREAM.OB_ECM_ORDER;

SELECT COUNT(CASE WHEN LIMIT_VALUE <> ROUND(LIMIT_VALUE, 4) THEN 1 END) AS LIMIT_GT4,
       COUNT(CASE WHEN LIMIT_VALUE <> ROUND(LIMIT_VALUE, 9) THEN 1 END) AS LIMIT_GT9
FROM DGSTREAM.OB_ECM_ORDER_IOI;

SELECT COUNT(CASE WHEN DEAL_ISSUE_SIZE <> ROUND(DEAL_ISSUE_SIZE, 4) THEN 1 END) AS DEALSIZE_GT4,
       COUNT(CASE WHEN PRICE <> ROUND(PRICE, 6) THEN 1 END) AS PRICE_GT6
FROM DGSTREAM.OB_DEAL_TRANCHE;

SELECT COUNT(CASE WHEN TOTAL_FEE <> ROUND(TOTAL_FEE, 6) THEN 1 END) AS TOTFEE_GT6,
       COUNT(CASE WHEN UNDERWRITING_FEE <> ROUND(UNDERWRITING_FEE, 6) THEN 1 END) AS UWFEE_GT6,
       COUNT(CASE WHEN MANAGEMENT_FEES <> ROUND(MANAGEMENT_FEES, 6) THEN 1 END) AS MGMT_GT6,
       COUNT(CASE WHEN SELLING_CONSESSION_FEE <> ROUND(SELLING_CONSESSION_FEE, 6) THEN 1 END) AS SELL_GT6,
       COUNT(CASE WHEN PRAECIPIUM_FEES <> ROUND(PRAECIPIUM_FEES, 6) THEN 1 END) AS PRAE_GT6,
       COUNT(CASE WHEN RETAIL_UW_FEE <> ROUND(RETAIL_UW_FEE, 6) THEN 1 END) AS RETAIL_GT6
FROM DGSTREAM.OB_DEAL_TRANCHE;

SELECT COUNT(CASE WHEN HEDGESIZE_AMOUNT <> ROUND(HEDGESIZE_AMOUNT, 4) THEN 1 END) AS HAMT_GT4,
       COUNT(CASE WHEN HEDGESIZE_ISNAMOUNT <> ROUND(HEDGESIZE_ISNAMOUNT, 4) THEN 1 END) AS HISN_GT4,
       COUNT(CASE WHEN HEDGESIZE_PCTFACE <> ROUND(HEDGESIZE_PCTFACE, 6) THEN 1 END) AS HPCT_GT6
FROM DGSTREAM.OB_HEDGE_ORDER;

SELECT COUNT(CASE WHEN TRADE_SIZE <> ROUND(TRADE_SIZE, 4) THEN 1 END) AS TSIZE_GT4,
       COUNT(CASE WHEN ALLOCATION_FINALALLOC <> ROUND(ALLOCATION_FINALALLOC, 4) THEN 1 END) AS TALLOC_GT4,
       COUNT(CASE WHEN PRICE_BASIS_VALUE <> ROUND(PRICE_BASIS_VALUE, 6) THEN 1 END) AS PBASIS_GT6
FROM DGSTREAM.OB_ORDER_TRADE;

SELECT COUNT(CASE WHEN ORDER_QTY <> ROUND(ORDER_QTY, 4) THEN 1 END) AS QTY_GT4,
       COUNT(CASE WHEN PRICE <> ROUND(PRICE, 6) THEN 1 END) AS PRICE_GT6,
       COUNT(CASE WHEN COMMISSION_RATE <> ROUND(COMMISSION_RATE, 9) THEN 1 END) AS COMM_GT9
FROM DGSTREAM.OB_ECM_TRADE_BOOK_INVESTOR_TRADE;

SELECT COUNT(CASE WHEN QUANTITY <> ROUND(QUANTITY, 4) THEN 1 END) AS QTY_GT4,
       COUNT(CASE WHEN POT_SPLIT_PERCENTAGE <> ROUND(POT_SPLIT_PERCENTAGE, 9) THEN 1 END) AS POTPCT_GT9,
       COUNT(CASE WHEN SELLING_CONCESSION <> ROUND(SELLING_CONCESSION, 6) THEN 1 END) AS SELL_GT6,
       COUNT(CASE WHEN EV <> ROUND(EV, 6) THEN 1 END) AS EV_GT6
FROM DGSTREAM.OB_ECM_TRADE_BOOK_DESIGNATION;

SELECT COUNT(CASE WHEN TOTAL_FEE <> ROUND(TOTAL_FEE, 6) THEN 1 END) AS TOTFEE_GT6,
       COUNT(CASE WHEN MANAGEMENT_FEE <> ROUND(MANAGEMENT_FEE, 6) THEN 1 END) AS MGMT_GT6,
       COUNT(CASE WHEN GROSS_SPREAD_PER_FEE <> ROUND(GROSS_SPREAD_PER_FEE, 6) THEN 1 END) AS GROSS_GT6,
       COUNT(CASE WHEN DESIGNATION_FEE <> ROUND(DESIGNATION_FEE, 6) THEN 1 END) AS DESIG_GT6
FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE;

SELECT COUNT(CASE WHEN BASE_PRICE <> ROUND(BASE_PRICE, 6) THEN 1 END) AS BASE_GT6,
       COUNT(CASE WHEN REOFFER_LOW_PRICE <> ROUND(REOFFER_LOW_PRICE, 6) THEN 1 END) AS RLOW_GT6,
       COUNT(CASE WHEN REOFFER_HIGH_PRICE <> ROUND(REOFFER_HIGH_PRICE, 6) THEN 1 END) AS RHIGH_GT6,
       COUNT(CASE WHEN FX_RATE <> ROUND(FX_RATE, 9) THEN 1 END) AS FX_GT9
FROM DGSTREAM.OPUS_ECM_TRANSACTION;

SELECT COUNT(CASE WHEN DEAL_FEE_MM <> ROUND(DEAL_FEE_MM, 6) THEN 1 END) AS FEEMM_GT6,
       COUNT(CASE WHEN DEAL_SIZE_MM <> ROUND(DEAL_SIZE_MM, 6) THEN 1 END) AS SIZEMM_GT6
FROM DGSTREAM.OPUS_BASE_TRANSACTION;
