SELECT DEALER,
       CASE WHEN REGEXP_LIKE(DEALER, '^CITI(GROUP|BANK)?([ _]|$)', 'i')
            THEN 'CITI' ELSE 'not citi' END AS VERDICT,
       COUNT(DISTINCT DEAL_TRANCHE_ID) AS TRANCHES_
FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER
WHERE  UPPER(DEALER) LIKE '%CITI%'
GROUP  BY DEALER
ORDER  BY VERDICT, TRANCHES_ DESC;

SELECT COUNT(*) AS SOLO_NEW_RULE_ALL_TIME
FROM  (SELECT DEAL_TRANCHE_ID
       FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER
       GROUP  BY DEAL_TRANCHE_ID
       HAVING COUNT(DEALER) > 0
          AND SUM(CASE WHEN REGEXP_LIKE(DEALER, '^CITI(GROUP|BANK)?([ _]|$)', 'i')
                       THEN 0 ELSE 1 END) = 0);

SELECT COUNT(DISTINCT S.DEAL_TRANCHE_ID) AS SOLO_NEW_RULE_2024
FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER S
JOIN   DGSTREAM.OB_DEAL_TRANCHE DT
       ON S.DEAL_TRANCHE_ID = DT.DEAL_ID || '-' || DT.TRANCHE_ID
WHERE  DT.PRICING_TS >= DATE '2024-01-01' AND DT.PRICING_TS < DATE '2025-01-01'
GROUP  BY S.DEAL_TRANCHE_ID
HAVING COUNT(S.DEALER) > 0
   AND SUM(CASE WHEN REGEXP_LIKE(S.DEALER, '^CITI(GROUP|BANK)?([ _]|$)', 'i')
                THEN 0 ELSE 1 END) = 0;

SELECT S.DEAL_TRANCHE_ID,
       CASE WHEN COUNT(S.DEALER) > 0
             AND SUM(CASE WHEN REGEXP_LIKE(S.DEALER, '^CITI(GROUP|BANK)?([ _]|$)', 'i')
                          THEN 0 ELSE 1 END) = 0
            THEN 'SOLO' ELSE 'SHARED' END AS NEW_SHARING_TYPE
FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER S
WHERE  S.DEAL_TRANCHE_ID LIKE 'I-260914-233059921862%'
GROUP  BY S.DEAL_TRANCHE_ID;
