SELECT DEAL_ID, TRANCHE_ID, TRANCHE_NAME, PRICING_TS, DEAL_SHARING_TYPE,
       SYNDICATE_MEMBER_NAME, BND_BANK, BND_BROKER
FROM   DGSTREAM.VW_TRANCHE_SUMMARY
WHERE  DEAL_ID = 'I-260914-233059921862';

SELECT S.DEAL_TRANCHE_ID, S.DEALER, COUNT(*) AS ROWS_
FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER S
WHERE  S.DEAL_TRANCHE_ID LIKE 'I-260914-233059921862%'
GROUP  BY S.DEAL_TRANCHE_ID, S.DEALER
ORDER  BY S.DEAL_TRANCHE_ID, S.DEALER;

SELECT DT.DEAL_ID, DT.TRANCHE_ID, DT.BD_BANK, DT.PRICING_TS, DT.STATUS
FROM   DGSTREAM.OB_DEAL_TRANCHE DT
WHERE  DT.DEAL_ID = 'I-260914-233059921862';

SELECT DEALER, COUNT(DISTINCT DEAL_TRANCHE_ID) AS TRANCHES_
FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER
WHERE  UPPER(DEALER) LIKE '%CITI%'
GROUP  BY DEALER
ORDER  BY TRANCHES_ DESC;

SELECT COUNT(*) AS TRANCHES_TOTAL,
       COUNT(CASE WHEN M.DEAL_TRANCHE_ID IS NULL THEN 1 END) AS NO_SYNDICATE_ROWS,
       COUNT(CASE WHEN M.DEAL_TRANCHE_ID IS NULL
                   AND UPPER(DT.BD_BANK) LIKE '%CITI%' THEN 1 END) AS NO_ROWS_BUT_CITI_BD
FROM  (SELECT DISTINCT DEAL_ID, TRANCHE_ID, BD_BANK FROM DGSTREAM.OB_DEAL_TRANCHE) DT
LEFT JOIN (SELECT DISTINCT DEAL_TRANCHE_ID FROM DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER) M
       ON M.DEAL_TRANCHE_ID = DT.DEAL_ID || '-' || DT.TRANCHE_ID;

SELECT COUNT(*) AS SOLO_TODAY_RULE
FROM  (SELECT DEAL_TRANCHE_ID
       FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER
       GROUP  BY DEAL_TRANCHE_ID
       HAVING MIN(DEALER) = MAX(DEALER)
          AND MIN(DEALER) LIKE '%Citigroup Global%');

SELECT COUNT(*) AS SOLO_ALL_CITI_ENTITIES_CI
FROM  (SELECT DEAL_TRANCHE_ID
       FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER
       WHERE  DEALER IS NOT NULL
       GROUP  BY DEAL_TRANCHE_ID
       HAVING SUM(CASE WHEN UPPER(DEALER) LIKE '%CITI%' THEN 0 ELSE 1 END) = 0);

SELECT COUNT(DISTINCT DEAL_TRANCHE_ID) AS SOLO_2024_ALL_CITI_CI
FROM  (SELECT S.DEAL_TRANCHE_ID
       FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER S
       JOIN   DGSTREAM.OB_DEAL_TRANCHE DT
              ON S.DEAL_TRANCHE_ID = DT.DEAL_ID || '-' || DT.TRANCHE_ID
       WHERE  DT.PRICING_TS >= DATE '2024-01-01' AND DT.PRICING_TS < DATE '2025-01-01'
       AND    S.DEALER IS NOT NULL
       GROUP  BY S.DEAL_TRANCHE_ID
       HAVING SUM(CASE WHEN UPPER(S.DEALER) LIKE '%CITI%' THEN 0 ELSE 1 END) = 0);
