SELECT column_name, data_type, data_precision, data_scale
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM' AND table_name = 'VW_ORDER_DETAIL'
AND    column_name IN ('ORDER_AMOUNT','ORDER_DEMAND_QTY','ORDER_ALLOCATION',
                       'TRANCHE_SIZE','DEAL_SIZE','ACTIVE_PRICE')
ORDER BY column_name;

SELECT COUNT(*) AS ROWS_,
       COUNT(CASE WHEN ORDER_AMOUNT <> ROUND(ORDER_AMOUNT, 4) THEN 1 END) AS AMT_SCALE_GT4,
       COUNT(CASE WHEN ORDER_AMOUNT <> ROUND(ORDER_AMOUNT, 0) THEN 1 END) AS AMT_FRACTIONAL
FROM DGSTREAM.VW_ORDER_DETAIL
WHERE UPPER(CURRENCY) = 'USD'
AND   PRICING_TS >= DATE '2025-09-03'
AND   PRICING_TS <  DATE '2026-09-04';
