SELECT COUNT(HEDGESECURITY_COUPON) AS COUPON_NONNULL,
       COUNT(CASE WHEN HEDGESECURITY_COUPON <> ROUND(HEDGESECURITY_COUPON, 6)
                  THEN 1 END) AS COUPON_GT6
FROM DGSTREAM.OB_HEDGE_ORDER;

SELECT COUNT(HEDGESECURITY_COUPON) AS COUPON_NONNULL,
       COUNT(CASE WHEN HEDGESECURITY_COUPON <> ROUND(HEDGESECURITY_COUPON, 6)
                  THEN 1 END) AS COUPON_GT6
FROM DGSTREAM.OB_HEDGE_TRADE;

SELECT COUNT(CASE WHEN POT_SPLIT <> ROUND(POT_SPLIT, 4) THEN 1 END) AS POTSPLIT_GT4,
       COUNT(CASE WHEN DESIGNABLE_SHARES <> ROUND(DESIGNABLE_SHARES, 4)
                  THEN 1 END) AS DESIGNABLE_GT4,
       COUNT(CASE WHEN UNDERWRITING_FEES <> ROUND(UNDERWRITING_FEES, 6)
                  THEN 1 END) AS UWFEES_GT6,
       COUNT(CASE WHEN MANAGEMENT_FEES <> ROUND(MANAGEMENT_FEES, 6)
                  THEN 1 END) AS MGMTFEES_GT6
FROM DGSTREAM.OB_ECM_TRADE_BOOK_DESIGNATION;
