SELECT COUNT(*) AS ECM_ORDERS,
       COUNT(DEMAND_QTY) AS WITH_DEMAND_QTY,
       COUNT(CASE WHEN PRIVATE_ALLOC IS NOT NULL AND DEMAND_QTY IS NULL
                  THEN 1 END) AS ALLOC_BUT_NO_DEMAND,
       COUNT(CASE WHEN DEMAND_QTY IS NOT NULL
                   AND NOT REGEXP_LIKE(TO_CHAR(DEMAND_QTY),
                       '^\s*[+-]?[0-9]+(\.[0-9]+)?([Ee][+-]?[0-9]+)?\s*$')
                  THEN 1 END) AS NON_NUMERIC_DEMAND
FROM DGSTREAM.OB_ECM_ORDER;

SELECT COUNT(*) AS NULL_DEMAND_ORDERS,
       COUNT(OI.ORDER_ID) AS COVERED_BY_IOI_LIMIT
FROM (SELECT ORDER_ID
      FROM DGSTREAM.OB_ECM_ORDER
      WHERE DEMAND_QTY IS NULL) O
LEFT JOIN (SELECT DISTINCT ORDER_ID
           FROM DGSTREAM.OB_ECM_ORDER_IOI
           WHERE LIMIT_VALUE IS NOT NULL) OI
    ON OI.ORDER_ID = O.ORDER_ID;

SELECT 'OB_DEAL_ISSUER' AS SRC, NAME AS ISSUER_NAME, COUNT(*) AS ROWS_
FROM DGSTREAM.OB_DEAL_ISSUER
WHERE UPPER(NAME) LIKE '%TRAVELER%'
GROUP BY NAME
UNION ALL
SELECT 'OPUS_ECM_TRANSACTION', ISSUER_NAME_FROM_SOURCE, COUNT(*)
FROM DGSTREAM.OPUS_ECM_TRANSACTION
WHERE UPPER(ISSUER_NAME_FROM_SOURCE) LIKE '%TRAVELER%'
GROUP BY ISSUER_NAME_FROM_SOURCE
UNION ALL
SELECT 'RELATED_PARTIES', PARTY_NAME, COUNT(*)
FROM DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES
WHERE UPPER(PARTY_NAME) LIKE '%TRAVELER%'
GROUP BY PARTY_NAME;

SELECT COUNT(*) AS CUSIP_HITS
FROM DGSTREAM.OB_TRANCHE
WHERE UPPER(VALUE) LIKE '%5C7GNK9W9%';
