SELECT PRODUCT,
       COUNT(*) AS ORDERS_,
       COUNT(DISTINCT INVESTOR_GP_ID) AS INVESTORS_,
       ROUND(SUM(ORDER_AMOUNT)) AS TOTAL_ORDER_AMOUNT
FROM DGSTREAM.VW_ORDER_DETAIL
WHERE UPPER(CURRENCY) = 'USD'
AND   PRICING_TS >= DATE '2025-09-03'
AND   PRICING_TS <  DATE '2026-09-04'
GROUP BY PRODUCT;

SELECT *
FROM (
    SELECT INVESTOR_NAME,
           INVESTOR_GP_ID,
           ROUND(SUM(ORDER_AMOUNT)) AS TOTAL_ORDER_AMOUNT
    FROM DGSTREAM.VW_ORDER_DETAIL
    WHERE UPPER(CURRENCY) = 'USD'
    AND   PRICING_TS >= DATE '2025-09-03'
    AND   PRICING_TS <  DATE '2026-09-04'
    GROUP BY INVESTOR_NAME, INVESTOR_GP_ID
    ORDER BY 3 DESC
)
WHERE ROWNUM <= 10;

SELECT COUNT(CASE WHEN T <> ROUND(T, 4) THEN 1 END) AS TOTALS_SCALE_GT4,
       COUNT(CASE WHEN T <> ROUND(T, 9) THEN 1 END) AS TOTALS_SCALE_GT9,
       COUNT(*) AS INVESTOR_TOTALS
FROM (
    SELECT SUM(ORDER_AMOUNT) AS T
    FROM DGSTREAM.VW_ORDER_DETAIL
    WHERE UPPER(CURRENCY) = 'USD'
    AND   PRICING_TS >= DATE '2025-09-03'
    AND   PRICING_TS <  DATE '2026-09-04'
    GROUP BY INVESTOR_NAME, INVESTOR_GP_ID
);
