-- ===========================================================================
-- WAVE-B DESC REQUESTS (2026-08-28) — the ONE consolidated ask. Run each as
-- SCRIPT OUTPUT (clean text) and screenshot; these unlock the remaining
-- domain views/branches so V3 covers everything before the whitelist:
--   * ECM order riches + ECM trade/book branches
--   * hedge TRADES view, trade SYNDICATE view
--   * firm-account design, salesperson reference
-- ===========================================================================

desc DGSTREAM.OB_ECM_ORDER;
desc DGSTREAM.OPUS_ECM_TRANSACTION;
desc DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE;
desc DGSTREAM.OB_HEDGE_TRADE;
desc DGSTREAM.OB_ORDER_TRADE_SYNDICATE;
desc DGSTREAM.OB_ECM_ORDER_BOOK_DETAILS;
desc DGSTREAM.OB_ECM_ORDER_BOOK_SUMMARY;
desc DGSTREAM.OB_ECM_TRADE_BOOK_INVESTOR_TRADE;
desc DGSTREAM.OB_TRANCHE_HEDGE_SECURITY;
desc DGSTREAM.VG_BCOSMOS_CUSTOMER_ACCOUNT;
desc DGSTREAM.OB_ECM_TRADE_BOOK_DESIGNATION;
desc DGSTREAM.OB_ECM_TRADE_BOOK_INVESTOR_MOGA_SPLIT_TRADES;
desc DGSTREAM.OB_ORDER_MATCH_GROUP_TRADE_SPLIT;

-- Populations for the three above (never counted in P1/P1b):
SELECT 'DESIGNATION' AS T, COUNT(*) AS ROWS_ FROM DGSTREAM.OB_ECM_TRADE_BOOK_DESIGNATION
UNION ALL SELECT 'MOGA_SPLIT_TRADES', COUNT(*) FROM DGSTREAM.OB_ECM_TRADE_BOOK_INVESTOR_MOGA_SPLIT_TRADES
UNION ALL SELECT 'MATCH_GROUP_TRADE_SPLIT', COUNT(*) FROM DGSTREAM.OB_ORDER_MATCH_GROUP_TRADE_SPLIT;

-- OB_INVESTOR_SALES is 19 rows — the whole table beats a desc:
SELECT * FROM DGSTREAM.OB_INVESTOR_SALES;

-- Samples (10 rows each) for the tables becoming views:
SELECT * FROM DGSTREAM.OB_HEDGE_TRADE FETCH FIRST 10 ROWS ONLY;
SELECT * FROM DGSTREAM.OB_ORDER_TRADE_SYNDICATE FETCH FIRST 10 ROWS ONLY;
SELECT * FROM DGSTREAM.OB_ECM_ORDER_BOOK_SUMMARY FETCH FIRST 10 ROWS ONLY;
