-- ===========================================================================
-- WAVE-A NAME VALIDATION (2026-08-28) — run BEFORE handing release 3 over.
-- Each statement compiles only if EVERY new source column name is exactly
-- right (WHERE 1=0 = zero cost, instant ORA-00904 on any typo — the PCM
-- lesson, applied preemptively). All three must return "no rows selected".
-- Note: SELLING_CONSESSION_FEE is the SOURCE's own spelling (sic) — the
-- view aliases it to SELLING_CONCESSION_FEE.
-- ===========================================================================

SELECT COUPON, YIELD, PRICE, PRICE_GUIDANCE, ORDER_BOOK_SIZE_USD,
       TOTAL_FEE, UNDERWRITING_FEE, MANAGEMENT_FEES, SELLING_CONSESSION_FEE,
       PRAECIPIUM_FEES, RETAIL_UW_FEE, ANNOUNCEMENT_DATE, ISSUE_DATE,
       TRADE_DATE, TARGET_MARKET, FRN_COUPON_INDEX
FROM   DGSTREAM.OB_DEAL_TRANCHE WHERE 1 = 0;

SELECT DEAL_FEE_MM, DEAL_FEE_CURRENCY, DEAL_SIZE_MM, DEAL_SIZE_CURRENCY
FROM   DGSTREAM.OPUS_BASE_TRANSACTION WHERE 1 = 0;

SELECT STATUS, QIB_STATUS, SUB_TYPE, IS_FIRM_ORDER, IS_POT, DRAFT_ALLOC,
       SOFT_ALLOC, ISN_ALLOC, RETENTION, RATIONALE, RATIONALE_TYPE,
       FX_CURRENCY, OBO_NAME, OBO_LEGAL_ENTITY_ID, ESG_TAG,
       ORDER_SIZE_CHANGE, IS_AFFILIATED, ONE_OFF_INVESTOR, SOEID
FROM   DGSTREAM.OB_ORDER WHERE 1 = 0;

SELECT INVESTOR_LEID FROM DGSTREAM.OB_ECM_ORDER WHERE 1 = 0;

-- WAVE B additions (2026-08-31) — same contract: every statement must
-- return "no rows selected" before handover.
SELECT HEDGE_TRADE_ID, ROOT_ID, PARENT_ID, SIBLING_ID, TYPE, SUB_TYPE,
       DIRECTION, HEDGE_TYPE, BND, SETTLEMENT_PERIOD, COUNTERPARTY_NAME,
       COUNTERPARTY_GPID, COUNTERPARTY_TYPE, HEDGESIZE_AMOUNT,
       HEDGESIZE_WEIGHT, HEDGESIZE_PCTFACE, HEDGESECURITY_ISIN,
       HEDGESECURITY_CUSIP, HEDGESECURITY_NAME, HEDGESECURITY_MATURITY_DATE,
       HEDGESECURITY_COUPON, HEDGESECURITY_COUPON_TYPE, HEDGESECURITY_TYPE,
       HEDGESECURITY_ISSUER, SALES_FIRSTNAME, SALES_LASTNAME, SALES_REGION,
       TRADE_TRADE_REFERENCE, TRADE_STATUS, PUBLISHED_TS
FROM   DGSTREAM.OB_HEDGE_TRADE WHERE 1 = 0;

SELECT DESIGNATION_ID, DEAL_ID, TRANCHE_ID, TRANCHE_NAME, TRADE_ID,
       INVESTOR_NAME, GPNUM, FIRM_ACCOUNT, SIDE, SALES_ID, CURRENCY,
       QUANTITY, DESIGNABLE_SHARES, POT_SPLIT, POT_SPLIT_PERCENTAGE,
       SELLING_CONCESSION, UNDERWRITING_FEES, MANAGEMENT_FEES, EV,
       SECURITY_ID, SECURITY_ID_TYPE, BROKER_NAME, BROKER_CODE,
       DESIGNATION_TYPE, SUBMISSION_STATUS, CARD_STATUS, STATUS,
       TRADE_DATE, SETTLEMENT_DATE, APPROVED_AT, APPROVED_BY, PUBLISHED_TS
FROM   DGSTREAM.OB_ECM_TRADE_BOOK_DESIGNATION WHERE 1 = 0;

SELECT ORDER_TRADE_ID, DEALER, DESIGNATION_AMT, ADJUSTED_DESIGNATION_AMT,
       ADJUSTED_DESIGNATION_PCT, CARVEOUT_AMT, DISTRIBUTED_CARVEOUT,
       DG_UPDATED_TS
FROM   DGSTREAM.OB_ORDER_TRADE_SYNDICATE WHERE 1 = 0;

SELECT INVESTOR_TRADE_ID, ORDER_ID, TRANCHE_ID, DEAL_ID, FLOW_TYPE,
       CHANNEL, SIDE, BILL_BY_BROKER, INVESTOR_NAME, GPNUM, REGION,
       ORDER_QTY, PRICE, STATUS, CLIENT_TRADE_ID, DEAL_SOURCE,
       LAST_MODIFIED_DATE, EXECUTION_TIME, FIRM_ACCOUNT_NUMBER,
       FIRM_ACCOUNT_TYPE, COMMISSION_RATE
FROM   DGSTREAM.OB_ECM_TRADE_BOOK_INVESTOR_TRADE WHERE 1 = 0;

SELECT INVESTOR_SALESPERSON_NAME, INVESTOR_SALESPERSON_SOEID,
       IS_FIRM_ORDER, IS_POT_ORDER, DRAFT_ALLOC, WALL_CROSSED_VALUE,
       INVESTOR_CLASSIFICATION_VALUE, EXISTING_HOLDER_VALUE, ACTIVE_PRICE,
       BOOK_STATUS, INVESTOR_LEID, ORDER_STATUS
FROM   DGSTREAM.OB_ECM_ORDER WHERE 1 = 0;

SELECT TOTAL_FEE, UNDERWRITING_FEE, MANAGEMENT_FEE, SELLING_CONCESSION_FEE,
       PRAEPICIUM_FEE, RETAIL_UNDERWRITING_FEE, ANNOUNCE_TS, TRADE_DATE,
       GROSS_SPREAD_PER_FEE, DESIGNATION_FEE,
       TOTAL_SHARES_OVER_ALLOTMENT_AUTHORIZED,
       TOTAL_SHARES_OVER_ALLOTMENT_EXERCISED, FIRST_TRADE_DATE,
       MANAGERS_LOCKUP_DATE
FROM   DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE WHERE 1 = 0;

SELECT ANNOUNCE_TS, BASE_PRICE, REOFFER_LOW_PRICE, REOFFER_HIGH_PRICE,
       FX_RATE, ISSUER_COUNTRY_NAME, ISSUER_DOMICILE_COUNTRY_NAME,
       OFFERING_FORMAT, ISSUER_LEID
FROM   DGSTREAM.OPUS_ECM_TRANSACTION WHERE 1 = 0;

SELECT INVESTOR_CLASSIFICATION FROM DGSTREAM.OB_ORDER WHERE 1 = 0;
