SELECT COUNT(*) AS ROWS_,
       COUNT(DISTINCT PRODUCT || '~' || ORDER_ID) AS KEYS_,
       COUNT(CASE WHEN ORDER_AMOUNT <> ROUND(ORDER_AMOUNT, 4) THEN 1 END) AS AMT_SCALE_GT4,
       COUNT(CASE WHEN PRODUCT = 'ECM' AND ORDER_DEMAND_QTY IS NOT NULL
                  THEN 1 END) AS ECM_ORDERS_WITH_DEMAND
FROM DGSTREAM.VW_ORDER_DETAIL;

SELECT COUNT(CASE WHEN PRODUCT = 'ECM' AND TOTAL_DEMAND > 0 THEN 1 END) AS ECM_DEALS_WITH_DEMAND,
       COUNT(CASE WHEN SUBSCRIPTION_RATIO IS NOT NULL THEN 1 END) AS SUBS_RATIO_DEALS
FROM DGSTREAM.VW_DEAL_SUMMARY;

SELECT COUNT(CASE WHEN TOTAL_FEE <> ROUND(TOTAL_FEE, 6) THEN 1 END) AS FEE_SCALE_GT6,
       COUNT(CASE WHEN GROSS_SPREAD_PER_FEE <> ROUND(GROSS_SPREAD_PER_FEE, 6)
                  THEN 1 END) AS GROSS_SCALE_GT6
FROM DGSTREAM.VW_TRANCHE_SUMMARY;
