-- ===========================================================================
-- DB ASKS — the ONE file of SQL checks for the user. Oracle (DGSTREAM) unless
-- a section says Trino. Sections A, B, C… are OPEN asks (dated; run, screenshot
-- to ~/Desktop/ADK, then the section is deleted once the verdict is recorded).
-- Sections S1, S2 are STANDING checks that stay.
-- ===========================================================================


-- ===========================================================================
-- S1. STANDING — SOURCE-NAME VALIDATION. Run BEFORE every view handover, on
-- the target environment. Every statement must return "no rows selected";
-- an ORA-00904 names the typo (WHERE 1=0 = zero cost). RULE: this list must
-- cover EVERY source column referenced by the views since the last deploy —
-- add a line for each new column, never only the newest wave. Sic spellings
-- are the source's own (SELLING_CONSESSION_FEE, PRAEPICIUM_FEE, IS_POT_ORDER).
-- ===========================================================================
SELECT COUPON, YIELD, PRICE, PRICE_GUIDANCE, ORDER_BOOK_SIZE_USD,
       TOTAL_FEE, UNDERWRITING_FEE, MANAGEMENT_FEES, SELLING_CONSESSION_FEE,
       PRAECIPIUM_FEES, RETAIL_UW_FEE, ANNOUNCEMENT_DATE, ISSUE_DATE,
       TRADE_DATE, TARGET_MARKET, FRN_COUPON_INDEX,
       DEAL_ISSUE_SIZE, USE_OF_PROCEEDS, STATUS, SETTLEMENT_DATE, DEAL_NAME,
       TRANCHE_ALLOWED_ORDER_SPREAD, TRANCHE_ALLOWED_ORDER_YIELD,
       TRANCHE_ALLOWED_ORDER_MAX_PRICE, TENOR_VALUE, TENOR_PERIOD, PRODUCT_CLASS,
       ORIGINATION_TRANSACTION_ID, REGION, PRICING_TS, CURRENCY
FROM   DGSTREAM.OB_DEAL_TRANCHE WHERE 1 = 0;

SELECT DEAL_FEE_MM, DEAL_FEE_CURRENCY, DEAL_SIZE_MM, DEAL_SIZE_CURRENCY, DEAL_REGION
FROM   DGSTREAM.OPUS_BASE_TRANSACTION WHERE 1 = 0;

SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER, PARTY_ROLE, PUBLISHED_TS
FROM   DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES WHERE 1 = 0;

SELECT STATUS, QIB_STATUS, SUB_TYPE, IS_FIRM_ORDER, IS_POT, DRAFT_ALLOC,
       SOFT_ALLOC, ISN_ALLOC, RETENTION, RATIONALE, RATIONALE_TYPE,
       FX_CURRENCY, OBO_NAME, OBO_LEGAL_ENTITY_ID, ESG_TAG,
       ORDER_SIZE_CHANGE, IS_AFFILIATED, ONE_OFF_INVESTOR, SOEID,
       INVESTOR_CLASSIFICATION, ROOT_ID, PARENT_ID, ORDER_ID, GPID, FINAL_ALLOC, BND
FROM   DGSTREAM.OB_ORDER WHERE 1 = 0;

SELECT ORDER_ID, AMT FROM DGSTREAM.OB_ORDER_SIZE WHERE 1 = 0;

SELECT INVESTOR_SALESPERSON_NAME, INVESTOR_SALESPERSON_SOEID,
       IS_FIRM_ORDER, IS_POT_ORDER, DRAFT_ALLOC, WALL_CROSSED_VALUE,
       INVESTOR_CLASSIFICATION_VALUE, EXISTING_HOLDER_VALUE, ACTIVE_PRICE,
       BOOK_STATUS, INVESTOR_LEID, ORDER_STATUS, DEMAND_QTY, PRIVATE_ALLOC,
       IOI_UNIT, IS_MATCHED, IS_DOMINANT, DEAL_ID, TRANCHE_ID, ORDER_ID,
       INVESTOR_GPNUM, BILLEDBY_BROKER_CODE
FROM   DGSTREAM.OB_ECM_ORDER WHERE 1 = 0;

SELECT ORDER_ID, IOI_QTY, LIMIT_VALUE, LIMIT_TYPE
FROM   DGSTREAM.OB_ECM_ORDER_IOI WHERE 1 = 0;

SELECT HEDGE_TRADE_ID, ROOT_ID, PARENT_ID, SIBLING_ID, TYPE, SUB_TYPE,
       DIRECTION, HEDGE_TYPE, BND, SETTLEMENT_PERIOD, COUNTERPARTY_NAME,
       COUNTERPARTY_GPID, COUNTERPARTY_TYPE, HEDGESIZE_AMOUNT,
       HEDGESIZE_WEIGHT, HEDGESIZE_PCTFACE, HEDGESECURITY_ISIN,
       HEDGESECURITY_CUSIP, HEDGESECURITY_NAME, HEDGESECURITY_MATURITY_DATE,
       HEDGESECURITY_COUPON, HEDGESECURITY_COUPON_TYPE, HEDGESECURITY_TYPE,
       HEDGESECURITY_ISSUER, SALES_FIRSTNAME, SALES_LASTNAME, SALES_REGION,
       TRADE_TRADE_REFERENCE, TRADE_STATUS, PUBLISHED_TS
FROM   DGSTREAM.OB_HEDGE_TRADE WHERE 1 = 0;

SELECT HEDGESIZE_AMOUNT, HEDGESIZE_ISNAMOUNT, HEDGESIZE_PCTFACE, ROOT_ID, PARENT_ID
FROM   DGSTREAM.OB_HEDGE_ORDER WHERE 1 = 0;

SELECT DESIGNATION_ID, DEAL_ID, TRANCHE_ID, TRANCHE_NAME, TRADE_ID,
       INVESTOR_NAME, GPNUM, FIRM_ACCOUNT, SIDE, SALES_ID, CURRENCY,
       QUANTITY, DESIGNABLE_SHARES, POT_SPLIT, POT_SPLIT_PERCENTAGE,
       SELLING_CONCESSION, UNDERWRITING_FEES, MANAGEMENT_FEES, EV,
       SECURITY_ID, SECURITY_ID_TYPE, BROKER_NAME, BROKER_CODE,
       DESIGNATION_TYPE, SUBMISSION_STATUS, CARD_STATUS, STATUS,
       TRADE_DATE, SETTLEMENT_DATE, APPROVED_AT, APPROVED_BY, PUBLISHED_TS
FROM   DGSTREAM.OB_ECM_TRADE_BOOK_DESIGNATION WHERE 1 = 0;

SELECT ORDER_TRADE_ID, DEALER, DESIGNATION_AMT, ADJUSTED_DESIGNATION_AMT,
       ADJUSTED_DESIGNATION_PCT, CARVEOUT_AMT, DISTRIBUTED_CARVEOUT,
       DG_UPDATED_TS
FROM   DGSTREAM.OB_ORDER_TRADE_SYNDICATE WHERE 1 = 0;

SELECT ORDER_TRADE_ID, ROOT_ID, PARENT_ID, PRICE_BASIS_CODE, PRICE_BASIS_VALUE,
       TRADE_SIZE, ALLOCATION_FINALALLOC
FROM   DGSTREAM.OB_ORDER_TRADE WHERE 1 = 0;

SELECT INVESTOR_TRADE_ID, ORDER_ID, TRANCHE_ID, DEAL_ID, FLOW_TYPE,
       CHANNEL, SIDE, BILL_BY_BROKER, INVESTOR_NAME, GPNUM, REGION,
       ORDER_QTY, PRICE, STATUS, CLIENT_TRADE_ID, DEAL_SOURCE,
       LAST_MODIFIED_DATE, EXECUTION_TIME, FIRM_ACCOUNT_NUMBER,
       FIRM_ACCOUNT_TYPE, COMMISSION_RATE, ISSUE_NAME
FROM   DGSTREAM.OB_ECM_TRADE_BOOK_INVESTOR_TRADE WHERE 1 = 0;

SELECT TOTAL_FEE, UNDERWRITING_FEE, MANAGEMENT_FEE, SELLING_CONCESSION_FEE,
       PRAEPICIUM_FEE, RETAIL_UNDERWRITING_FEE, ANNOUNCE_TS, TRADE_DATE,
       GROSS_SPREAD_PER_FEE, DESIGNATION_FEE,
       TOTAL_SHARES_OVER_ALLOTMENT_AUTHORIZED,
       TOTAL_SHARES_OVER_ALLOTMENT_EXERCISED, FIRST_TRADE_DATE,
       MANAGERS_LOCKUP_DATE, ECM_TRANSACTION_ID, ECM_TRANSACTION_TRANCHE_ID
FROM   DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE WHERE 1 = 0;

SELECT ANNOUNCE_TS, BASE_PRICE, REOFFER_LOW_PRICE, REOFFER_HIGH_PRICE,
       FX_RATE, ISSUER_COUNTRY_NAME, ISSUER_DOMICILE_COUNTRY_NAME,
       OFFERING_FORMAT, ISSUER_LEID, DEAL_SIZE, USE_OF_PROCEEDS,
       ECM_TRANSACTION_ID, DEAL_TRANSACTION_ID, SYNDICATE_DEAL_NAME,
       ISSUER_NAME_FROM_SOURCE, ISSUER_GFCID, ISSUER_TICKER,
       ISSUER_INDUSTRY_SECTOR, PRODUCT_EQUITY_TYPE_VALUE,
       PRODUCT_OFFERING_TYPE_VALUE, SETTLEMENT_TS, SETTLEMENT_CURRENCY_NAME
FROM   DGSTREAM.OPUS_ECM_TRANSACTION WHERE 1 = 0;

SELECT ECM_TRANSACTION_ID, STATUS_TYPE, STATUS_VALUE
FROM   DGSTREAM.OPUS_ECM_TRANSACTION_STATUS WHERE 1 = 0;

SELECT DEAL_TRANCHE_ID, DEALER
FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER WHERE 1 = 0;

SELECT DEAL_TRANCHE_ID, NAME, GFCID, TICKER
FROM   DGSTREAM.OB_DEAL_ISSUER WHERE 1 = 0;


-- ===========================================================================
-- S2. STANDING — SCALE RE-CENSUS FOR A NEW ENVIRONMENT (PROD at promote time,
-- run by the access holder). Counts > 0 in a _GT4/_GT6/_GT9 column mean a
-- value carries more decimals than the view's ROUND bound and would be
-- rounded on read; DEV/UAT counts are not expectations.
-- ===========================================================================
SELECT 'OB_ORDER_SIZE.AMT' AS COL,
       COUNT(AMT) AS NONNULL_,
       COUNT(CASE WHEN AMT <> ROUND(AMT, 4) THEN 1 END) AS SCALE_GT4,
       COUNT(CASE WHEN AMT <> ROUND(AMT, 9) THEN 1 END) AS SCALE_GT9,
       MAX(CASE WHEN AMT <> ROUND(AMT, 4) THEN AMT END) AS SAMPLE_GT4
FROM DGSTREAM.OB_ORDER_SIZE;

SELECT COUNT(FINAL_ALLOC) AS ALLOC_NONNULL,
       COUNT(CASE WHEN FINAL_ALLOC <> ROUND(FINAL_ALLOC, 4) THEN 1 END) AS ALLOC_GT4,
       COUNT(CASE WHEN FINAL_ALLOC <> ROUND(FINAL_ALLOC, 9) THEN 1 END) AS ALLOC_GT9,
       COUNT(CASE WHEN ORDER_SIZE_CHANGE <> ROUND(ORDER_SIZE_CHANGE, 4) THEN 1 END) AS SIZECHG_GT4
FROM DGSTREAM.OB_ORDER;

SELECT COUNT(CASE WHEN DEMAND_QTY <> ROUND(DEMAND_QTY, 4) THEN 1 END) AS DEMAND_GT4,
       COUNT(CASE WHEN PRIVATE_ALLOC <> ROUND(PRIVATE_ALLOC, 4) THEN 1 END) AS ALLOC_GT4,
       COUNT(CASE WHEN ACTIVE_PRICE <> ROUND(ACTIVE_PRICE, 6) THEN 1 END) AS PRICE_GT6
FROM DGSTREAM.OB_ECM_ORDER;

SELECT COUNT(CASE WHEN IOI_QTY <> ROUND(IOI_QTY, 4) THEN 1 END) AS IOIQTY_GT4,
       COUNT(CASE WHEN LIMIT_VALUE <> ROUND(LIMIT_VALUE, 4) THEN 1 END) AS LIMIT_GT4,
       COUNT(CASE WHEN LIMIT_VALUE <> ROUND(LIMIT_VALUE, 9) THEN 1 END) AS LIMIT_GT9
FROM DGSTREAM.OB_ECM_ORDER_IOI;

SELECT COUNT(CASE WHEN DEAL_ISSUE_SIZE <> ROUND(DEAL_ISSUE_SIZE, 4) THEN 1 END) AS DEALSIZE_GT4,
       COUNT(CASE WHEN PRICE <> ROUND(PRICE, 6) THEN 1 END) AS PRICE_GT6,
       COUNT(CASE WHEN TOTAL_FEE <> ROUND(TOTAL_FEE, 6) THEN 1 END) AS TOTFEE_GT6,
       COUNT(CASE WHEN UNDERWRITING_FEE <> ROUND(UNDERWRITING_FEE, 6) THEN 1 END) AS UWFEE_GT6,
       COUNT(CASE WHEN MANAGEMENT_FEES <> ROUND(MANAGEMENT_FEES, 6) THEN 1 END) AS MGMT_GT6,
       COUNT(CASE WHEN SELLING_CONSESSION_FEE <> ROUND(SELLING_CONSESSION_FEE, 6) THEN 1 END) AS SELL_GT6,
       COUNT(CASE WHEN PRAECIPIUM_FEES <> ROUND(PRAECIPIUM_FEES, 6) THEN 1 END) AS PRAE_GT6,
       COUNT(CASE WHEN RETAIL_UW_FEE <> ROUND(RETAIL_UW_FEE, 6) THEN 1 END) AS RETAIL_GT6
FROM DGSTREAM.OB_DEAL_TRANCHE;

SELECT COUNT(CASE WHEN HEDGESIZE_AMOUNT <> ROUND(HEDGESIZE_AMOUNT, 4) THEN 1 END) AS HAMT_GT4,
       COUNT(CASE WHEN HEDGESIZE_ISNAMOUNT <> ROUND(HEDGESIZE_ISNAMOUNT, 4) THEN 1 END) AS HISN_GT4,
       COUNT(CASE WHEN HEDGESIZE_PCTFACE <> ROUND(HEDGESIZE_PCTFACE, 6) THEN 1 END) AS HPCT_GT6
FROM DGSTREAM.OB_HEDGE_ORDER;

SELECT COUNT(CASE WHEN TRADE_SIZE <> ROUND(TRADE_SIZE, 4) THEN 1 END) AS TSIZE_GT4,
       COUNT(CASE WHEN ALLOCATION_FINALALLOC <> ROUND(ALLOCATION_FINALALLOC, 4) THEN 1 END) AS TALLOC_GT4,
       COUNT(CASE WHEN PRICE_BASIS_VALUE <> ROUND(PRICE_BASIS_VALUE, 6) THEN 1 END) AS PBASIS_GT6
FROM DGSTREAM.OB_ORDER_TRADE;

SELECT COUNT(CASE WHEN ORDER_QTY <> ROUND(ORDER_QTY, 4) THEN 1 END) AS QTY_GT4,
       COUNT(CASE WHEN PRICE <> ROUND(PRICE, 6) THEN 1 END) AS PRICE_GT6,
       COUNT(CASE WHEN COMMISSION_RATE <> ROUND(COMMISSION_RATE, 9) THEN 1 END) AS COMM_GT9
FROM DGSTREAM.OB_ECM_TRADE_BOOK_INVESTOR_TRADE;

SELECT COUNT(CASE WHEN QUANTITY <> ROUND(QUANTITY, 4) THEN 1 END) AS QTY_GT4,
       COUNT(CASE WHEN POT_SPLIT_PERCENTAGE <> ROUND(POT_SPLIT_PERCENTAGE, 9) THEN 1 END) AS POTPCT_GT9,
       COUNT(CASE WHEN SELLING_CONCESSION <> ROUND(SELLING_CONCESSION, 6) THEN 1 END) AS SELL_GT6,
       COUNT(CASE WHEN EV <> ROUND(EV, 6) THEN 1 END) AS EV_GT6
FROM DGSTREAM.OB_ECM_TRADE_BOOK_DESIGNATION;

SELECT COUNT(CASE WHEN TOTAL_FEE <> ROUND(TOTAL_FEE, 6) THEN 1 END) AS TOTFEE_GT6,
       COUNT(CASE WHEN MANAGEMENT_FEE <> ROUND(MANAGEMENT_FEE, 6) THEN 1 END) AS MGMT_GT6,
       COUNT(CASE WHEN GROSS_SPREAD_PER_FEE <> ROUND(GROSS_SPREAD_PER_FEE, 6) THEN 1 END) AS GROSS_GT6,
       COUNT(CASE WHEN DESIGNATION_FEE <> ROUND(DESIGNATION_FEE, 6) THEN 1 END) AS DESIG_GT6
FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE;

SELECT COUNT(CASE WHEN BASE_PRICE <> ROUND(BASE_PRICE, 6) THEN 1 END) AS BASE_GT6,
       COUNT(CASE WHEN REOFFER_LOW_PRICE <> ROUND(REOFFER_LOW_PRICE, 6) THEN 1 END) AS RLOW_GT6,
       COUNT(CASE WHEN REOFFER_HIGH_PRICE <> ROUND(REOFFER_HIGH_PRICE, 6) THEN 1 END) AS RHIGH_GT6,
       COUNT(CASE WHEN FX_RATE <> ROUND(FX_RATE, 9) THEN 1 END) AS FX_GT9
FROM DGSTREAM.OPUS_ECM_TRANSACTION;

SELECT COUNT(CASE WHEN DEAL_FEE_MM <> ROUND(DEAL_FEE_MM, 6) THEN 1 END) AS FEEMM_GT6,
       COUNT(CASE WHEN DEAL_SIZE_MM <> ROUND(DEAL_SIZE_MM, 6) THEN 1 END) AS SIZEMM_GT6
FROM DGSTREAM.OPUS_BASE_TRANSACTION;


-- ===========================================================================
-- S3. STANDING — TRINO-SIDE COLUMN VISIBILITY. Run THROUGH STARBURST/TRINO
-- (catalog bds_dg_oraas), NOT Oracle. Run after every view deploy: the
-- Oracle-side deploy check cannot see a stale connector metadata cache.
-- Any failure here = Trino still serves the pre-deploy column list → BDS ask.
-- PASSED UAT 2026-09-17: all four SELECTs resolve; SHOW COLUMNS maps every cast
-- metric as decimal(38,4)/(38,6) — nothing left at decimal(38,0).
-- ===========================================================================
SELECT demand_as_submitted, demand_unit, tenors, product_class
FROM   bds_dg_oraas.dgstream.vw_order_detail
LIMIT  1;

SELECT allowed_order_spread, allowed_order_yield, allowed_order_max_price
FROM   bds_dg_oraas.dgstream.vw_tranche_summary
LIMIT  1;

SELECT transaction_id, tenors
FROM   bds_dg_oraas.dgstream.vw_hedge_order
LIMIT  1;

SELECT transaction_id, tenors
FROM   bds_dg_oraas.dgstream.vw_hedge_trade
LIMIT  1;

SHOW COLUMNS FROM bds_dg_oraas.dgstream.vw_order_detail;




-- ===========================================================================
-- S4. STANDING — PROD CENSUS PACK. Counts and vocabularies ONLY (no deal
-- names, no investor names, no row-level data) so an access holder can run
-- it on PROD and share a screenshot. Run at promote time and after every
-- PROD view release. The results REPLACE the UAT-labelled numbers quoted in
-- SKILL / yaml prose (regions, settlement, indication coverage, vocabularies,
-- bookless share). Every statement is a full scan of one view — run
-- off-peak; the order-view ones take minutes on 5M+ rows.
-- ===========================================================================

-- S4.1 Bookless share per product (UAT 2026-09-17: DCM 51 %, ECM 86 %).
SELECT PRODUCT, COUNT(*) AS DEALS_,
       SUM(CASE WHEN ORDER_COUNT IS NULL THEN 1 ELSE 0 END) AS BOOKLESS_
FROM   DGSTREAM.VW_DEAL_SUMMARY
GROUP  BY PRODUCT;

-- S4.2 ECM indication coverage + IOI unit mix (UAT: 72.3 % covered; SHARES/BOND fill).
SELECT O.IOI_UNIT, COUNT(*) AS LIVE_ORDERS,
       COUNT(CASE WHEN O.DEMAND_QTY IS NOT NULL THEN 1 END) AS HAS_DEMAND
FROM   DGSTREAM.OB_ECM_ORDER O
WHERE  O.ORDER_STATUS NOT IN ('CANCELLED','DELETED','PASS')
GROUP  BY O.IOI_UNIT
ORDER  BY LIVE_ORDERS DESC;

-- S4.3 Order-level fill rates per product (doctrine quotes UAT %s for these).
SELECT PRODUCT, COUNT(*) AS ORDERS_,
       COUNT(INVESTOR_REGION)         AS HAS_REGION,
       COUNT(INVESTOR_CATEGORY)       AS HAS_CATEGORY,
       COUNT(INVESTOR_CLASSIFICATION) AS HAS_CLASSIFICATION,
       COUNT(TRANSACTION_ID)          AS HAS_TXN_ID
FROM   DGSTREAM.VW_ORDER_DETAIL
GROUP  BY PRODUCT;

-- S4.4 Vocabularies with counts (labels only).
SELECT PRODUCT, DEAL_STATUS, COUNT(*) AS DEALS_
FROM   DGSTREAM.VW_DEAL_SUMMARY
GROUP  BY PRODUCT, DEAL_STATUS ORDER BY PRODUCT, DEALS_ DESC;

SELECT PRODUCT, INVESTOR_CLASSIFICATION, COUNT(*) AS ORDERS_
FROM   DGSTREAM.VW_ORDER_DETAIL
GROUP  BY PRODUCT, INVESTOR_CLASSIFICATION ORDER BY PRODUCT, ORDERS_ DESC;

SELECT PRODUCT, INVESTOR_REGION, COUNT(*) AS ORDERS_
FROM   DGSTREAM.VW_ORDER_DETAIL
GROUP  BY PRODUCT, INVESTOR_REGION ORDER BY PRODUCT, ORDERS_ DESC;

-- S4.5 Deal-level coverage: region, settlement, issuer identity, txn id.
SELECT PRODUCT, COUNT(*) AS DEALS_,
       COUNT(DEAL_REGION)    AS HAS_REGION,
       COUNT(SETTLEMENT_TS)  AS HAS_SETTLEMENT,
       COUNT(GFCID)          AS HAS_GFCID,
       COUNT(ISSUER_NAME)    AS HAS_ISSUER_NAME,
       COUNT(TRANSACTION_ID) AS HAS_TXN_ID
FROM   DGSTREAM.VW_DEAL_SUMMARY
GROUP  BY PRODUCT;

-- S4.6 Transaction-id coverage by pricing year (the "forward-populated" claim).
SELECT PRODUCT, EXTRACT(YEAR FROM LAST_PRICED) AS YR,
       COUNT(*) AS DEALS_, COUNT(TRANSACTION_ID) AS HAS_TXN_ID
FROM   DGSTREAM.VW_DEAL_SUMMARY
WHERE  LAST_PRICED >= DATE '2022-01-01'
GROUP  BY PRODUCT, EXTRACT(YEAR FROM LAST_PRICED)
ORDER  BY PRODUCT, YR;

-- S4.7 Subscription-ratio distribution (are deal sizes and demand sane?).
SELECT PRODUCT,
       SUM(CASE WHEN SUBSCRIPTION_RATIO IS NULL THEN 1 ELSE 0 END)                       AS RATIO_NULL,
       SUM(CASE WHEN SUBSCRIPTION_RATIO < 1 THEN 1 ELSE 0 END)                             AS UNDER_1X,
       SUM(CASE WHEN SUBSCRIPTION_RATIO BETWEEN 1 AND 10 THEN 1 ELSE 0 END)                AS X1_TO_10,
       SUM(CASE WHEN SUBSCRIPTION_RATIO > 10 AND SUBSCRIPTION_RATIO <= 100 THEN 1 ELSE 0 END) AS X10_TO_100,
       SUM(CASE WHEN SUBSCRIPTION_RATIO > 100 THEN 1 ELSE 0 END)                           AS OVER_100X
FROM   DGSTREAM.VW_DEAL_SUMMARY
GROUP  BY PRODUCT;

-- S4.8 Identifier-type combinations and currency vocabulary per product.
SELECT PRODUCT, IDENTIFIER_TYPE, COUNT(*) AS TRANCHES_
FROM   DGSTREAM.VW_TRANCHE_SUMMARY
GROUP  BY PRODUCT, IDENTIFIER_TYPE ORDER BY PRODUCT, TRANCHES_ DESC;

SELECT PRODUCT, CURRENCY, COUNT(*) AS TRANCHES_
FROM   DGSTREAM.VW_TRANCHE_SUMMARY
GROUP  BY PRODUCT, CURRENCY ORDER BY PRODUCT, TRANCHES_ DESC;

-- S4.9 Citi dealer spellings (bank labels): the SOLO regex must catch every
--      real Citi entity and no competitor (Citizens / CITIC).
SELECT DEALER,
       CASE WHEN REGEXP_LIKE(DEALER, '^CITI(GROUP|BANK)?([ _]|$)', 'i')
            THEN 'CITI' ELSE 'not citi' END AS VERDICT,
       COUNT(DISTINCT DEAL_TRANCHE_ID) AS TRANCHES_
FROM   DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER
WHERE  UPPER(DEALER) LIKE '%CITI%'
GROUP  BY DEALER ORDER BY VERDICT, TRANCHES_ DESC;

-- S4.10 SOLO / SHARED split per product.
SELECT PRODUCT, DEAL_SHARING_TYPE, COUNT(*) AS TRANCHES_
FROM   DGSTREAM.VW_TRANCHE_SUMMARY
GROUP  BY PRODUCT, DEAL_SHARING_TYPE ORDER BY PRODUCT, DEAL_SHARING_TYPE;

-- S4.11 DCM pricing film population (OB_TRANCHE_PRICING): on UAT the four
--       stages exist on ~11k tranches but VALUE is filled on only a few
--       hundred. PROD decides whether vw_tranche_pricing is worth building.
SELECT PRICING_TYPE, PRICING_STATUS, COUNT(*) AS ROWS_,
       COUNT(DISTINCT DEAL_TRANCHE_ID) AS TRANCHES_,
       COUNT(VALUE) AS HAS_VALUE, COUNT(LOWER_BOUND) AS HAS_LOWER,
       COUNT(AREA_RANGE) AS HAS_AREA
FROM   DGSTREAM.OB_TRANCHE_PRICING
GROUP  BY PRICING_TYPE, PRICING_STATUS ORDER BY ROWS_ DESC;

-- S4.12 DCM order price basis + limit fill (OB_ORDER_SIZE): UAT = 99 % reOffer,
--       ~55k limit rows (benchmark / midSwap / minYield / maxPrice /
--       floatingRate), AMT_CHANGE on 19 %, CREATED_TS ~100 %.
SELECT TYPE, COUNT(*) AS ROWS_, COUNT(PRICE_DEMAND) AS HAS_PRICE_LIMIT,
       COUNT(SPREAD_DEMAND) AS HAS_SPREAD_LIMIT, COUNT(MIN_YIELD) AS HAS_MIN_YIELD,
       COUNT(AMT_CHANGE) AS HAS_AMT_CHANGE, COUNT(CREATED_TS) AS HAS_CREATED_TS
FROM   DGSTREAM.OB_ORDER_SIZE
GROUP  BY TYPE ORDER BY ROWS_ DESC;


-- ===========================================================================
-- L. 2026-09-21 — DCM ORDER STATUS CODES. Census K found the DCM order status
-- is a workflow code (XB 1.9M, B 1.6M, NEW, UPDATED, NULL 120k, D 96k, R, FR,
-- PN, A, F, XR) beside the plain DELETED / CANCELLED. The exclusion rule cannot
-- ship until D (deleted?), XB/XR (cancelled?) are decoded. UAT. Screenshot.
-- ===========================================================================

-- L1. What the codes look like in practice: per code, the share of orders that
--     carry a size row, an allocation, and whether the row is flagged active.
SELECT UPPER(O.STATUS) AS STATUS_, COUNT(*) AS ORDERS_,
       SUM(CASE WHEN O.FINAL_ALLOC > 0 THEN 1 ELSE 0 END) AS WITH_ALLOC_,
       SUM(CASE WHEN Z.ORDER_ID IS NOT NULL THEN 1 ELSE 0 END) AS WITH_SIZE_,
       MIN(O.PUBLISHED_TS) AS FIRST_SEEN_, MAX(O.PUBLISHED_TS) AS LAST_SEEN_
FROM   DGSTREAM.OB_ORDER O
LEFT JOIN (SELECT DISTINCT ORDER_ID FROM DGSTREAM.OB_ORDER_SIZE) Z ON Z.ORDER_ID = O.ORDER_ID
GROUP  BY UPPER(O.STATUS) ORDER BY ORDERS_ DESC;

-- L2. Do codes co-occur with the plain words on the same deal (a status
--     lifecycle, or two feeds)? Source system per code.
SELECT UPPER(STATUS) AS STATUS_, SOURCE_SYSTEM, ITEM_SOURCE, COUNT(*) AS ORDERS_
FROM   DGSTREAM.OB_ORDER
GROUP  BY UPPER(STATUS), SOURCE_SYSTEM, ITEM_SOURCE
ORDER  BY ORDERS_ DESC FETCH FIRST 30 ROWS ONLY;

-- L3. Ask the feed owner (no SQL): the meaning of XB, B, D, R, FR, PN, A, F, XR
--     and whether NULL status = live. Until answered the rule excludes ONLY the
--     spelled-out DELETED / CANCELLED on DCM orders.


-- ===========================================================================
-- M. 2026-09-21 — IPREO AS A NEW ECM SOURCE: what is already there. Run BEFORE
-- the view design; the answers decide whether Ipreo is new TABLES, new ROWS in
-- the tables we read, or a second feed into both. UAT. Screenshot each.
-- ===========================================================================

-- M1. Any Ipreo-named objects in DGSTREAM already?
SELECT object_name, object_type, created, last_ddl_time
FROM   all_objects
WHERE  owner = 'DGSTREAM' AND UPPER(object_name) LIKE '%IPREO%'
ORDER  BY object_name;

-- M2. Are Ipreo rows already flowing into the ECM tables we read?
SELECT 'OB_ECM_ORDER' AS TBL, COUNT(*) AS ROWS_,
       COUNT(IPREO_EXTERNAL_ORDER_ID) AS WITH_IPREO_ID_,
       COUNT(DISTINCT DEAL_ID) AS DEALS_,
       COUNT(DISTINCT CASE WHEN IPREO_EXTERNAL_ORDER_ID IS NOT NULL THEN DEAL_ID END) AS DEALS_WITH_IPREO_
FROM   DGSTREAM.OB_ECM_ORDER;

-- M3. Source-system vocabulary on the ECM transaction spine and the order table.
SELECT 'OPUS_ECM_TRANSACTION' AS TBL, SOURCE_SYSTEM, COUNT(DISTINCT DEAL_TRANSACTION_ID) AS DEALS_
FROM   DGSTREAM.OPUS_ECM_TRANSACTION GROUP BY SOURCE_SYSTEM
UNION ALL
SELECT 'OB_ECM_ORDER', SOURCE_SYSTEM, COUNT(DISTINCT DEAL_ID)
FROM   DGSTREAM.OB_ECM_ORDER GROUP BY SOURCE_SYSTEM
ORDER  BY 1, 3 DESC;

-- M4. The ECM deals the views CANNOT see today: orders whose DEAL_ID has no
--     OPUS transaction row (the inner join drops them). If Ipreo deals land
--     without an OPUS spine row, this is the number that grows.
SELECT COUNT(DISTINCT O.DEAL_ID) AS ORDER_DEALS_WITHOUT_OPUS_SPINE,
       COUNT(*) AS ORDERS_DROPPED
FROM   DGSTREAM.OB_ECM_ORDER O
WHERE  NOT EXISTS (SELECT 1 FROM DGSTREAM.OPUS_ECM_TRANSACTION T
                   WHERE T.DEAL_TRANSACTION_ID = O.DEAL_ID);

-- M5. Cross-system id fill on the spine (which external ids a deal carries).
SELECT COUNT(*) AS TXNS_, COUNT(CMG_DEAL_ID) AS CMG_, COUNT(ISSUE_NET_DEAL_ID) AS ISSUENET_,
       COUNT(DEAL_LOGIC_DEAL_ID) AS DEALOGIC_, COUNT(BB_DEAL_ID) AS BB_, COUNT(DMS_DEAL_ID) AS DMS_
FROM   DGSTREAM.OPUS_ECM_TRANSACTION WHERE DEAL_TRANSACTION_ID IS NOT NULL;


-- ===========================================================================
-- N. 2026-09-21 — IPREO ECM BUILD CENSUS. Everything the three Ipreo branches
-- (deal / tranche / order views, third UNION ALL, PRODUCT 'ECM') stand on, in
-- ONE script. Run as a SCRIPT (F5) on UAT and paste the Script Output as
-- TEXT — column names and codes do not survive screenshots. A statement that
-- ERRORS is a finding (a table or column the draft assumed does not exist):
-- keep going, paste the error. Sections: A schema · B keys · C grain ·
-- D vocabularies · E fill · F exclusions · G overlap · H stability.
-- ===========================================================================

-- ---------- A. SCHEMA (the S1 name-validation source) ----------------------
-- N-A1. Every Ipreo table with row counts.
SELECT table_name, num_rows, last_analyzed
FROM   all_tables WHERE owner = 'DGSTREAM' AND UPPER(table_name) LIKE '%IPREO%'
ORDER  BY table_name;

-- N-A2. Every column of every Ipreo table + the two OPUS tables the draft reuses.
SELECT table_name, column_id, column_name, data_type, data_length, data_precision, data_scale, nullable
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM'
AND   (UPPER(table_name) LIKE '%IPREO%'
       OR table_name IN ('OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY', 'OPUS_ECM_TRANSACTION_STATUS'))
ORDER  BY table_name, column_id;

-- N-A3. Indexes on the Ipreo tables (the filter shapes we will hit: deal id,
--       tranche id, order id, investor code).
SELECT i.table_name, i.index_name, i.uniqueness,
       LISTAGG(c.column_name, ',') WITHIN GROUP (ORDER BY c.column_position) AS cols
FROM   all_indexes i JOIN all_ind_columns c
       ON c.index_owner = i.owner AND c.index_name = i.index_name
WHERE  i.owner = 'DGSTREAM' AND UPPER(i.table_name) LIKE '%IPREO%'
GROUP  BY i.table_name, i.index_name, i.uniqueness
ORDER  BY i.table_name, i.index_name;

-- ---------- B. KEYS (which id ties issue -> tranche -> order -> OPUS txn) ---
-- N-B1. Does an Ipreo ISS_ID equal an OPUS DEAL_TRANSACTION_ID? Counts of each
--       population and of the intersection under that equality.
SELECT (SELECT COUNT(*) FROM DGSTREAM.IPREO_ISSUE) AS ISSUES_,
       (SELECT COUNT(DISTINCT DEAL_TRANSACTION_ID) FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION
         WHERE DEAL_TRANSACTION_ID IS NOT NULL) AS IPREO_OPUS_TXNS_,
       (SELECT COUNT(*) FROM DGSTREAM.IPREO_ISSUE I
         WHERE EXISTS (SELECT 1 FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION T
                       WHERE T.DEAL_TRANSACTION_ID = TO_CHAR(I.ISS_ID))) AS ISSUES_MATCHING_TXN_
FROM   DUAL;

-- N-B2. Candidate link columns, by name, on the four key tables.
SELECT table_name, column_name, data_type
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM'
AND    table_name IN ('IPREO_ISSUE', 'IPREO_OPUS_ECM_TRANSACTION', 'IPREO_TRANCHE', 'IPREO_ORDER',
                      'IPREO_OPUS_ECM_TRANSACTION_TRANCHE')
AND   (column_name LIKE '%TRANSACTION%' OR column_name LIKE '%DEAL%' OR column_name LIKE '%ISS%'
       OR column_name LIKE '%TRN%' OR column_name LIKE '%OPUS%' OR column_name LIKE '%EXT%'
       OR column_name LIKE '%REF%' OR column_name LIKE '%_ID')
ORDER  BY table_name, column_name;

-- N-B3. Ten sample ids side by side, so the format itself can be compared
--       (numeric vs text, 8-digit vs GUID).
SELECT 'IPREO_ISSUE.ISS_ID' AS SRC, TO_CHAR(ISS_ID) AS ID_ FROM DGSTREAM.IPREO_ISSUE WHERE ROWNUM <= 10
UNION ALL
SELECT 'IPREO_OPUS_ECM_TRANSACTION.DEAL_TRANSACTION_ID', DEAL_TRANSACTION_ID
FROM   DGSTREAM.IPREO_OPUS_ECM_TRANSACTION WHERE DEAL_TRANSACTION_ID IS NOT NULL AND ROWNUM <= 10
UNION ALL
SELECT 'IPREO_OPUS_ECM_TRANSACTION.ECM_TRANSACTION_ID', TO_CHAR(ECM_TRANSACTION_ID)
FROM   DGSTREAM.IPREO_OPUS_ECM_TRANSACTION WHERE ROWNUM <= 10
UNION ALL
SELECT 'IPREO_TRANCHE.TRN_ID', TO_CHAR(TRN_ID) FROM DGSTREAM.IPREO_TRANCHE WHERE ROWNUM <= 10
UNION ALL
SELECT 'IPREO_OPUS_ECM_TRANSACTION_TRANCHE.ECM_TRANSACTION_TRANCHE_ID', TO_CHAR(ECM_TRANSACTION_TRANCHE_ID)
FROM   DGSTREAM.IPREO_OPUS_ECM_TRANSACTION_TRANCHE WHERE ROWNUM <= 10
UNION ALL
SELECT 'OPUS_ECM_TRANSACTION.DEAL_TRANSACTION_ID (current ECM)', DEAL_TRANSACTION_ID
FROM   DGSTREAM.OPUS_ECM_TRANSACTION WHERE DEAL_TRANSACTION_ID IS NOT NULL AND ROWNUM <= 10;

-- N-B4. Tranche -> issue: does every IPREO_TRANCHE carry an ISS_ID that exists
--       in IPREO_ISSUE, and does IPREO_OPUS_ECM_TRANSACTION_TRANCHE link to
--       IPREO_TRANCHE at all (which column)?
SELECT (SELECT COUNT(*) FROM DGSTREAM.IPREO_TRANCHE) AS TRANCHES_,
       (SELECT COUNT(*) FROM DGSTREAM.IPREO_TRANCHE T
         WHERE EXISTS (SELECT 1 FROM DGSTREAM.IPREO_ISSUE I WHERE I.ISS_ID = T.ISS_ID)) AS TRANCHES_WITH_ISSUE_,
       (SELECT COUNT(*) FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION_TRANCHE) AS OPUS_TRANCHES_
FROM   DUAL;

-- N-B5. Order -> tranche / issue integrity.
SELECT COUNT(*) AS ORDERS_,
       SUM(CASE WHEN EXISTS (SELECT 1 FROM DGSTREAM.IPREO_TRANCHE T WHERE T.TRN_ID = O.TRN_ID) THEN 1 ELSE 0 END) AS WITH_TRANCHE_,
       SUM(CASE WHEN EXISTS (SELECT 1 FROM DGSTREAM.IPREO_ISSUE I WHERE I.ISS_ID = O.ISS_ID) THEN 1 ELSE 0 END) AS WITH_ISSUE_
FROM   DGSTREAM.IPREO_ORDER O;

-- ---------- C. GRAIN (what one row means, per table) -----------------------
-- N-C1. Rows vs distinct keys — a ratio above 1 means versions/duplicates and
--       the branch needs a dedupe (ROW_NUMBER by ROWID, like the OPUS branch).
SELECT 'IPREO_ISSUE' AS TBL, COUNT(*) AS ROWS_, COUNT(DISTINCT ISS_ID) AS DISTINCT_KEY_ FROM DGSTREAM.IPREO_ISSUE
UNION ALL SELECT 'IPREO_TRANCHE', COUNT(*), COUNT(DISTINCT TRN_ID) FROM DGSTREAM.IPREO_TRANCHE
UNION ALL SELECT 'IPREO_ORDER', COUNT(*), COUNT(DISTINCT ORD_ID) FROM DGSTREAM.IPREO_ORDER
UNION ALL SELECT 'IPREO_ORDER (ORD_ID,TRN_ID)', COUNT(*), COUNT(DISTINCT ORD_ID || '~' || TRN_ID) FROM DGSTREAM.IPREO_ORDER
UNION ALL SELECT 'IPREO_ORDERPRODUCT (ORD_ID,TRN_ID)', COUNT(*), COUNT(DISTINCT ORD_ID || '~' || TRN_ID) FROM DGSTREAM.IPREO_ORDERPRODUCT
UNION ALL SELECT 'IPREO_ORDERIOI', COUNT(*), COUNT(DISTINCT ORD_ID) FROM DGSTREAM.IPREO_ORDERIOI
UNION ALL SELECT 'IPREO_OPUS_ECM_TRANSACTION', COUNT(*), COUNT(DISTINCT ECM_TRANSACTION_ID) FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION
UNION ALL SELECT 'IPREO_OPUS_ECM_TRANSACTION (DEAL_TRANSACTION_ID)', COUNT(*), COUNT(DISTINCT DEAL_TRANSACTION_ID) FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION
UNION ALL SELECT 'IPREO_OPUS_ECM_TRANSACTION_TRANCHE', COUNT(*), COUNT(DISTINCT ECM_TRANSACTION_TRANCHE_ID) FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION_TRANCHE;

-- N-C2. IOI curve: points per order in IPREO_ORDERIOI (1 = scalar, >1 = curve).
SELECT POINTS, COUNT(*) AS ORDERS_
FROM  (SELECT ORD_ID, COUNT(*) AS POINTS FROM DGSTREAM.IPREO_ORDERIOI GROUP BY ORD_ID)
GROUP  BY POINTS ORDER BY POINTS;

-- ---------- D. VOCABULARIES (the codes the branch maps by CASE) ------------
-- N-D1. Order product: IOI amount type codes (draft maps C/F/P/% — verify).
SELECT 'IOI_AMT_TYPE' AS COL, IOI_AMT_TYPE AS VAL, COUNT(*) AS N FROM DGSTREAM.IPREO_ORDERPRODUCT GROUP BY IOI_AMT_TYPE
UNION ALL SELECT 'IPREO_ORDER.DELETED_IND', DELETED_IND, COUNT(*) FROM DGSTREAM.IPREO_ORDER GROUP BY DELETED_IND
UNION ALL SELECT 'IPREO_ISSUE.DEAL_STATE_CD', DEAL_STATE_CD, COUNT(*) FROM DGSTREAM.IPREO_ISSUE GROUP BY DEAL_STATE_CD
ORDER  BY 1, 3 DESC;

-- N-D2. Any OTHER status-like column on IPREO_ORDER / IPREO_ISSUE / IPREO_TRANCHE
--       (the draft's ORDER_STATUS is derived from DELETED_IND alone, so the
--       CANCELLED / PASS exclusion is inert unless a real status exists).
SELECT table_name, column_name, data_type
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM' AND table_name IN ('IPREO_ORDER', 'IPREO_ISSUE', 'IPREO_TRANCHE', 'IPREO_ORDERPRODUCT')
AND   (column_name LIKE '%STAT%' OR column_name LIKE '%STATE%' OR column_name LIKE '%IND' OR column_name LIKE '%FLAG%'
       OR column_name LIKE '%CANCEL%' OR column_name LIKE '%DELET%' OR column_name LIKE '%ACTIVE%')
ORDER  BY table_name, column_name;

-- N-D3. Execution status vocabulary on the Ipreo OPUS status table (the
--       Confidential/Withdrawn/Terminated exclusion must find the same words).
SELECT STATUS_TYPE, STATUS_VALUE, COUNT(DISTINCT ECM_TRANSACTION_ID) AS TXNS_
FROM   DGSTREAM.IPREO_OPUS_ECM_TRANSACTION_STATUS
GROUP  BY STATUS_TYPE, STATUS_VALUE ORDER BY STATUS_TYPE, TXNS_ DESC;

-- N-D4. Equity type / offering type vocabularies on the Ipreo spine (must
--       match the OPUS vocabulary the catalogs document, or map to it).
SELECT 'EQUITY_TYPE' AS COL, PRODUCT_EQUITY_TYPE_VALUE AS VAL, COUNT(*) AS N
FROM   DGSTREAM.IPREO_OPUS_ECM_TRANSACTION GROUP BY PRODUCT_EQUITY_TYPE_VALUE
UNION ALL
SELECT 'OFFERING_TYPE', PRODUCT_OFFERING_TYPE_VALUE, COUNT(*)
FROM   DGSTREAM.IPREO_OPUS_ECM_TRANSACTION GROUP BY PRODUCT_OFFERING_TYPE_VALUE
UNION ALL
SELECT 'CURRENCY_CODE', CURRENCY_CODE, COUNT(*)
FROM   DGSTREAM.IPREO_OPUS_ECM_TRANSACTION GROUP BY CURRENCY_CODE
ORDER  BY 1, 3 DESC;

-- ---------- E. FILL (which projected columns will actually carry data) -----
-- N-E1. Spine fill.
SELECT COUNT(*) AS TXNS_, COUNT(DEAL_TRANSACTION_ID) AS HAS_DEAL_TXN_, COUNT(SYNDICATE_DEAL_NAME) AS HAS_NAME_,
       COUNT(DEAL_SIZE) AS HAS_SIZE_, COUNT(ISSUER_TICKER) AS HAS_TICKER_, COUNT(ISSUER_INDUSTRY_SECTOR) AS HAS_SECTOR_,
       COUNT(PRODUCT_EQUITY_TYPE_VALUE) AS HAS_EQTYPE_, COUNT(PRODUCT_OFFERING_TYPE_VALUE) AS HAS_OFFTYPE_,
       COUNT(CURRENCY_CODE) AS HAS_CCY_
FROM   DGSTREAM.IPREO_OPUS_ECM_TRANSACTION;

-- N-E2. Order fill (the columns the order branch projects).
SELECT COUNT(*) AS ORDERS_, COUNT(EXT_INV_CD) AS HAS_GPNUM_, COUNT(INST_ALLOC_SIZE) AS HAS_ALLOC_,
       COUNT(ISS_ID) AS HAS_ISS_, COUNT(TRN_ID) AS HAS_TRN_, COUNT(DELETED_IND) AS HAS_DELETED_IND_
FROM   DGSTREAM.IPREO_ORDER;

-- N-E3. Investor identity on IPREO_ORDER — name / id / region / category
--       columns (by name), so the order branch can fill the investor block.
SELECT column_name, data_type
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM' AND table_name = 'IPREO_ORDER'
AND   (column_name LIKE '%INV%' OR column_name LIKE '%NAME%' OR column_name LIKE '%REGION%'
       OR column_name LIKE '%COUNTRY%' OR column_name LIKE '%TYPE%' OR column_name LIKE '%CATEG%'
       OR column_name LIKE '%SALES%' OR column_name LIKE '%ALLOC%' OR column_name LIKE '%DEMAND%'
       OR column_name LIKE '%QTY%' OR column_name LIKE '%AMT%' OR column_name LIKE '%TS' OR column_name LIKE '%DATE%')
ORDER  BY column_name;

-- N-E4. Tranche attributes on IPREO_TRANCHE (name / size / pricing / currency /
--       identifiers), by name.
SELECT column_name, data_type
FROM   all_tab_columns
WHERE  owner = 'DGSTREAM' AND table_name = 'IPREO_TRANCHE'
ORDER  BY column_id;

-- N-E5. IOI table fill and scale.
SELECT COUNT(*) AS IOI_ROWS_, COUNT(IOI_QTY) AS HAS_QTY_, COUNT(IOI_AMT) AS HAS_AMT_,
       COUNT(CASE WHEN IOI_QTY <> ROUND(IOI_QTY, 4) THEN 1 END) AS QTY_GT4DP_,
       MAX(IOI_QTY) AS MAX_QTY_, MAX(IOI_AMT) AS MAX_AMT_
FROM   DGSTREAM.IPREO_ORDERIOI;

-- ---------- F. EXCLUSIONS (so Ipreo counts mean what OPUS counts mean) ------
-- N-F1. Deals the execution-status rule would drop, and deals with NO status
--       row at all (an INNER JOIN to status drops those — the OPUS branch does).
SELECT (SELECT COUNT(DISTINCT T.ECM_TRANSACTION_ID) FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION T) AS TXNS_,
       (SELECT COUNT(DISTINCT T.ECM_TRANSACTION_ID) FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION T
         WHERE NOT EXISTS (SELECT 1 FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION_STATUS S
                           WHERE S.ECM_TRANSACTION_ID = T.ECM_TRANSACTION_ID AND S.STATUS_TYPE = 'Execution_Status')) AS TXNS_WITHOUT_STATUS_,
       (SELECT COUNT(DISTINCT S.ECM_TRANSACTION_ID) FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION_STATUS S
         WHERE S.STATUS_TYPE = 'Execution_Status'
         AND   S.STATUS_VALUE IN ('Confidential', 'Withdrawn', 'Terminated')) AS TXNS_EXCLUDED_
FROM   DUAL;

-- N-F2. Orders the DELETED_IND rule drops vs keeps.
SELECT DELETED_IND, COUNT(*) AS ORDERS_, COUNT(DISTINCT ISS_ID) AS ISSUES_
FROM   DGSTREAM.IPREO_ORDER GROUP BY DELETED_IND;

-- ---------- G. OVERLAP (the same deal in both ECM sources) ------------------
-- N-G1. Ipreo transactions that also exist in the current OPUS ECM spine.
SELECT COUNT(*) AS IPREO_TXNS_ALSO_IN_OPUS_
FROM  (SELECT DISTINCT DEAL_TRANSACTION_ID FROM DGSTREAM.IPREO_OPUS_ECM_TRANSACTION
       WHERE DEAL_TRANSACTION_ID IS NOT NULL) I
WHERE  EXISTS (SELECT 1 FROM DGSTREAM.OPUS_ECM_TRANSACTION T WHERE T.DEAL_TRANSACTION_ID = I.DEAL_TRANSACTION_ID);

-- N-G2. Ipreo ORDERS whose order id also exists in OB_ECM_ORDER (same book
--       loaded twice?) and Ipreo order ids that match OB_ECM_ORDER's
--       IPREO_EXTERNAL_ORDER_ID (the existing feed already carries them?).
SELECT (SELECT COUNT(*) FROM DGSTREAM.IPREO_ORDER O
         WHERE EXISTS (SELECT 1 FROM DGSTREAM.OB_ECM_ORDER E WHERE E.ORDER_ID = TO_CHAR(O.ORD_ID))) AS SAME_ORDER_ID_,
       (SELECT COUNT(*) FROM DGSTREAM.IPREO_ORDER O
         WHERE EXISTS (SELECT 1 FROM DGSTREAM.OB_ECM_ORDER E WHERE E.IPREO_EXTERNAL_ORDER_ID = TO_CHAR(O.ORD_ID))) AS MATCHES_EXTERNAL_ID_
FROM   DUAL;

-- N-G3. Ten overlapping deals side by side (name, size, order counts in each
--       source) — decides "OPUS wins" vs "Ipreo wins" vs "show both".
SELECT *
FROM  (SELECT I.DEAL_TRANSACTION_ID,
              MAX(I.SYNDICATE_DEAL_NAME) AS IPREO_NAME, MAX(I.DEAL_SIZE) AS IPREO_SIZE,
              (SELECT MAX(T.SYNDICATE_DEAL_NAME) FROM DGSTREAM.OPUS_ECM_TRANSACTION T
                WHERE T.DEAL_TRANSACTION_ID = I.DEAL_TRANSACTION_ID) AS OPUS_NAME,
              (SELECT MAX(T.DEAL_SIZE) FROM DGSTREAM.OPUS_ECM_TRANSACTION T
                WHERE T.DEAL_TRANSACTION_ID = I.DEAL_TRANSACTION_ID) AS OPUS_SIZE,
              (SELECT COUNT(*) FROM DGSTREAM.OB_ECM_ORDER E WHERE E.DEAL_ID = I.DEAL_TRANSACTION_ID) AS OPUS_ORDERS,
              (SELECT COUNT(*) FROM DGSTREAM.IPREO_ORDER O WHERE TO_CHAR(O.ISS_ID) = I.DEAL_TRANSACTION_ID) AS IPREO_ORDERS
       FROM   DGSTREAM.IPREO_OPUS_ECM_TRANSACTION I
       WHERE  I.DEAL_TRANSACTION_ID IS NOT NULL
       AND    EXISTS (SELECT 1 FROM DGSTREAM.OPUS_ECM_TRANSACTION T WHERE T.DEAL_TRANSACTION_ID = I.DEAL_TRANSACTION_ID)
       GROUP  BY I.DEAL_TRANSACTION_ID)
WHERE  ROWNUM <= 10;

-- ---------- H. STABILITY (the dedupe keys the branches will partition on) ---
-- N-H1. Within one ORD_ID, do ISS_ID / TRN_ID ever vary (if yes, a widened
--       PARTITION BY would split the order — the 2026-09-02 lesson)?
SELECT COUNT(*) AS ORDERS_WITH_VARYING_PARENTS
FROM  (SELECT ORD_ID FROM DGSTREAM.IPREO_ORDER
       GROUP  BY ORD_ID HAVING COUNT(DISTINCT ISS_ID) > 1 OR COUNT(DISTINCT TRN_ID) > 1);

-- N-H2. NULL keys (a NULL id forms one invisible group in a GROUP BY census).
SELECT SUM(CASE WHEN ORD_ID IS NULL THEN 1 ELSE 0 END) AS NULL_ORD_,
       SUM(CASE WHEN TRN_ID IS NULL THEN 1 ELSE 0 END) AS NULL_TRN_,
       SUM(CASE WHEN ISS_ID IS NULL THEN 1 ELSE 0 END) AS NULL_ISS_
FROM   DGSTREAM.IPREO_ORDER;

-- N-H3. Versioning on the Ipreo OPUS spine: rows per ECM_TRANSACTION_ID and
--       whether a version/published column exists to order the dedupe.
SELECT column_name FROM all_tab_columns
WHERE  owner = 'DGSTREAM' AND table_name = 'IPREO_OPUS_ECM_TRANSACTION'
AND   (column_name LIKE '%VERSION%' OR column_name LIKE '%PUBLISH%' OR column_name LIKE '%UPDATED%' OR column_name LIKE '%_TS')
ORDER  BY column_name;
