CREATE OR REPLACE VIEW "DGSTREAM"."VW_DESIGNATION" AS
SELECT
    'ECM' AS PRODUCT,
    D.DEAL_ID AS DEAL_ID,
    D.TRANCHE_ID AS TRANCHE_ID,
    D.TRANCHE_NAME AS TRANCHE_NAME,
    D.DESIGNATION_ID AS DESIGNATION_ID,
    TO_CHAR(D.TRADE_ID) AS TRADE_ID,
    D.INVESTOR_NAME AS INVESTOR_NAME,
    TO_CHAR(D.GPNUM) AS INVESTOR_GP_ID,
    D.FIRM_ACCOUNT AS FIRM_ACCOUNT,
    D.SIDE AS SIDE,
    D.SALES_ID AS SALES_ID,
    D.CURRENCY AS CURRENCY,
    CAST(D.QUANTITY AS NUMBER(38,4)) AS QUANTITY,
    CAST(D.DESIGNABLE_SHARES AS NUMBER(38,4)) AS DESIGNABLE_SHARES,
    CAST(D.POT_SPLIT AS NUMBER(38,4)) AS POT_SPLIT,
    CAST(D.POT_SPLIT_PERCENTAGE AS NUMBER(38,9)) AS POT_SPLIT_PERCENTAGE,
    CAST(D.SELLING_CONCESSION AS NUMBER(38,6)) AS SELLING_CONCESSION,
    CAST(D.UNDERWRITING_FEES AS NUMBER(38,6)) AS UNDERWRITING_FEES,
    CAST(D.MANAGEMENT_FEES AS NUMBER(38,6)) AS MANAGEMENT_FEES,
    CAST(D.EV AS NUMBER(38,6)) AS EV,
    D.SECURITY_ID AS SECURITY_ID,
    D.SECURITY_ID_TYPE AS SECURITY_ID_TYPE,
    D.BROKER_NAME AS BROKER_NAME,
    D.BROKER_CODE AS BROKER_CODE,
    D.DESIGNATION_TYPE AS DESIGNATION_TYPE,
    D.SUBMISSION_STATUS AS SUBMISSION_STATUS,
    D.CARD_STATUS AS CARD_STATUS,
    D.STATUS AS STATUS,
    CAST(D.TRADE_DATE AS TIMESTAMP(6)) AS TRADE_TS,
    CAST(D.SETTLEMENT_DATE AS TIMESTAMP(6)) AS SETTLEMENT_TS,
    CAST(D.APPROVED_AT AS TIMESTAMP(6)) AS APPROVED_TS,
    D.APPROVED_BY AS APPROVED_BY,
    CAST(D.PUBLISHED_TS AS TIMESTAMP(6)) AS PUBLISHED_TS
FROM (
    SELECT W.*
    FROM (
        SELECT DS.*,
               ROW_NUMBER() OVER (PARTITION BY DS.DESIGNATION_ID
                                  ORDER BY DS.PUBLISHED_TS DESC,
                                           DS.ROWID) AS RN_
        FROM DGSTREAM.OB_ECM_TRADE_BOOK_DESIGNATION DS
        WHERE DS.DESIGNATION_ID IS NOT NULL
    ) W
    WHERE W.RN_ = 1
) D
;
GRANT SELECT ON "DGSTREAM"."VW_DESIGNATION" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_DESIGNATION" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_DESIGNATION" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_DESIGNATION" TO "DGLOBE" WITH GRANT OPTION;
