CREATE OR REPLACE VIEW "DGSTREAM"."VW_DEAL_SUMMARY" AS
SELECT
    'ECM' AS PRODUCT,
    T.DEAL_TRANSACTION_ID AS DEAL_ID,
    MAX(T.SYNDICATE_DEAL_NAME) AS DEAL_NAME,
    MAX(T.DEAL_SIZE) AS DEAL_SIZE,
    MAX(NVL(PCM.PARTY_NAME, NVL(OIN.ISSUER_NAME_BY_GFCID, T.ISSUER_NAME_FROM_SOURCE))) AS ISSUER_NAME,
    MAX(NVL(PCM.PARTY_GFCID, T.ISSUER_GFCID)) AS GFCID,
    MAX(NVL(PCM.PARTY_TICKER, T.ISSUER_TICKER)) AS TICKER,
    MAX(T.ISSUER_INDUSTRY_SECTOR) AS SECTOR,
    MAX(T.USE_OF_PROCEEDS) AS USE_OF_PROCEEDS,
    MAX(T.PRODUCT_EQUITY_TYPE_VALUE) AS EQUITY_TYPE,
    MAX(T.PRODUCT_OFFERING_TYPE_VALUE) AS OFFERING_TYPE,
    MAX(S.STATUS_VALUE) AS DEAL_STATUS,
    MAX(S.STATUS_TYPE) AS EXECUTION_STATUS,
    MAX(OBT.DEAL_REGION) AS DEAL_REGION,
    MAX(T.SETTLEMENT_TS) AS SETTLEMENT_TS,
    MAX(T.SETTLEMENT_CURRENCY_NAME) AS SETTLEMENT_CURRENCY,
    MAX(TR.TRANCHE_COUNT) AS TRANCHE_COUNT,
    MAX(TR.FIRST_PRICED) AS FIRST_PRICED,
    MAX(TR.LAST_PRICED) AS LAST_PRICED,
    MAX(TC.CURRENCIES) AS CURRENCIES,
    MAX(OD.ORDER_COUNT) AS ORDER_COUNT,
    MAX(OD.INVESTOR_COUNT) AS INVESTOR_COUNT
FROM (
    SELECT X.*
    FROM (
        SELECT ET.*,
               ROW_NUMBER() OVER (PARTITION BY ET.ECM_TRANSACTION_ID
                                  ORDER BY ET.ROWID) AS RN_
        FROM DGSTREAM.OPUS_ECM_TRANSACTION ET
        WHERE ET.DEAL_TRANSACTION_ID IS NOT NULL
    ) X
    WHERE X.RN_ = 1
) T
INNER JOIN (
    SELECT ECM_TRANSACTION_ID,
           MAX(STATUS_VALUE) AS STATUS_VALUE,
           MAX(STATUS_TYPE)  AS STATUS_TYPE
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_STATUS
    WHERE STATUS_TYPE = 'Execution_Status'
      AND STATUS_VALUE NOT IN ('Confidential', 'Withdrawn', 'Terminated')
    GROUP BY ECM_TRANSACTION_ID
) S
    ON T.ECM_TRANSACTION_ID = S.ECM_TRANSACTION_ID
LEFT JOIN (
    SELECT TRANSACTION_ID, MAX(DEAL_REGION) AS DEAL_REGION
    FROM DGSTREAM.OPUS_BASE_TRANSACTION
    GROUP BY TRANSACTION_ID
) OBT
    ON T.DEAL_TRANSACTION_ID = OBT.TRANSACTION_ID
LEFT JOIN (
    SELECT ET.DEAL_TRANSACTION_ID,
           COUNT(DISTINCT TT.ECM_TRANSACTION_ID || '~' ||
                          TT.ECM_TRANSACTION_TRANCHE_ID) AS TRANCHE_COUNT,
           MIN(TT.PRICING_TS) AS FIRST_PRICED,
           MAX(TT.PRICING_TS) AS LAST_PRICED
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE TT
    JOIN (SELECT DISTINCT ECM_TRANSACTION_ID, DEAL_TRANSACTION_ID
          FROM DGSTREAM.OPUS_ECM_TRANSACTION) ET
      ON ET.ECM_TRANSACTION_ID = TT.ECM_TRANSACTION_ID
    GROUP BY ET.DEAL_TRANSACTION_ID
) TR
    ON TR.DEAL_TRANSACTION_ID = T.DEAL_TRANSACTION_ID
LEFT JOIN (
    SELECT C.DEAL_TRANSACTION_ID,
           LISTAGG(C.TRANCHE_CURRENCY_ID, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT)
             WITHIN GROUP (ORDER BY C.FIRST_PRICED_TS ASC NULLS LAST,
                           C.TRANCHE_CURRENCY_ID) AS CURRENCIES
    FROM (
        SELECT ET.DEAL_TRANSACTION_ID,
               NVL(TDC.CURRENCY_NAME,
                   NVL(GC.CURRENCY_NAME, TT.TRANCHE_CURRENCY_ID)) AS TRANCHE_CURRENCY_ID,
               MIN(TT.PRICING_TS) AS FIRST_PRICED_TS
        FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE TT
        JOIN (SELECT DISTINCT ECM_TRANSACTION_ID, DEAL_TRANSACTION_ID
              FROM DGSTREAM.OPUS_ECM_TRANSACTION) ET
          ON ET.ECM_TRANSACTION_ID = TT.ECM_TRANSACTION_ID
        LEFT JOIN (
            SELECT ECM_TRANSACTION_ID, ECM_TRANSACTION_TRANCHE_ID, CURRENCY_ID,
                   MAX(CURRENCY_NAME) AS CURRENCY_NAME
            FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY
            GROUP BY ECM_TRANSACTION_ID, ECM_TRANSACTION_TRANCHE_ID, CURRENCY_ID
        ) TDC
          ON TDC.ECM_TRANSACTION_ID = TT.ECM_TRANSACTION_ID
         AND TDC.ECM_TRANSACTION_TRANCHE_ID = TT.ECM_TRANSACTION_TRANCHE_ID
         AND TDC.CURRENCY_ID = TT.TRANCHE_CURRENCY_ID
        LEFT JOIN (
            SELECT CURRENCY_ID, MAX(CURRENCY_NAME) AS CURRENCY_NAME
            FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY
            GROUP BY CURRENCY_ID
        ) GC
          ON GC.CURRENCY_ID = TT.TRANCHE_CURRENCY_ID
        GROUP BY ET.DEAL_TRANSACTION_ID,
                 NVL(TDC.CURRENCY_NAME,
                     NVL(GC.CURRENCY_NAME, TT.TRANCHE_CURRENCY_ID))
    ) C
    GROUP BY C.DEAL_TRANSACTION_ID
) TC
    ON TC.DEAL_TRANSACTION_ID = T.DEAL_TRANSACTION_ID
LEFT JOIN (
    SELECT O.DEAL_ID,
           COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT,
           COUNT(DISTINCT O.INVESTOR_GPNUM) AS INVESTOR_COUNT
    FROM DGSTREAM.OB_ECM_ORDER O
    WHERE O.ORDER_STATUS NOT IN ('CANCELLED', 'DELETED', 'PASS')
      AND ((O.IS_MATCHED = 'true' AND O.IS_DOMINANT = 'true') OR O.IS_MATCHED = 'false')
    GROUP BY O.DEAL_ID
) OD
    ON T.DEAL_TRANSACTION_ID = OD.DEAL_ID
LEFT JOIN (
    SELECT GFCID, MAX(NAME) AS ISSUER_NAME_BY_GFCID
    FROM DGSTREAM.OB_DEAL_ISSUER
    WHERE GFCID IS NOT NULL AND NAME IS NOT NULL
    GROUP BY GFCID
) OIN
    ON OIN.GFCID = T.ISSUER_GFCID
LEFT JOIN (
    SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER
    FROM (
        SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER,
               ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID
                                  ORDER BY PUBLISHED_TS DESC) AS RN_
        FROM DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES
        WHERE PARTY_ROLE = 'Primary Client'
    ) WHERE RN_ = 1
) PCM
    ON PCM.TRANSACTION_ID = T.DEAL_TRANSACTION_ID
GROUP BY T.DEAL_TRANSACTION_ID

UNION ALL

SELECT
    'DCM' AS PRODUCT,
    D.DEAL_ID AS DEAL_ID,
    D.DEAL_NAME AS DEAL_NAME,
    D.DEAL_SIZE AS DEAL_SIZE,
    NVL(PCM.PARTY_NAME, D.ISSUER_NAME) AS ISSUER_NAME,
    NVL(PCM.PARTY_GFCID, D.GFCID) AS GFCID,
    NVL(PCM.PARTY_TICKER, D.TICKER) AS TICKER,
    D.SECTOR AS SECTOR,
    D.USE_OF_PROCEEDS AS USE_OF_PROCEEDS,
    CAST(NULL AS VARCHAR2(4000)) AS EQUITY_TYPE,
    CAST(NULL AS VARCHAR2(4000)) AS OFFERING_TYPE,
    D.DEAL_STATUS AS DEAL_STATUS,
    CAST(NULL AS VARCHAR2(4000)) AS EXECUTION_STATUS,
    D.DEAL_REGION AS DEAL_REGION,
    CAST(D.SETTLEMENT_TS AS TIMESTAMP(6)) AS SETTLEMENT_TS,
    D.SETTLEMENT_CURRENCY AS SETTLEMENT_CURRENCY,
    D.TRANCHE_COUNT AS TRANCHE_COUNT,
    D.FIRST_PRICED AS FIRST_PRICED,
    D.LAST_PRICED AS LAST_PRICED,
    CU.CURRENCIES AS CURRENCIES,
    D.ORDER_COUNT AS ORDER_COUNT,
    D.INVESTOR_COUNT AS INVESTOR_COUNT
FROM (
    SELECT ODT.DEAL_ID,
           MAX(ODT.DEAL_NAME) AS DEAL_NAME,
           MAX(NVL(ODT.DEAL_ISSUE_SIZE, 0)) AS DEAL_SIZE,
           MAX(ODI.NAME) AS ISSUER_NAME,
           MAX(ODI.GFCID) AS GFCID,
           MAX(ODI.TICKER) AS TICKER,
           MAX(ODT.ISSUER_SECTOR) AS SECTOR,
           MAX(ODT.USE_OF_PROCEEDS) AS USE_OF_PROCEEDS,
           MAX(ODT.STATUS) AS DEAL_STATUS,
           MAX(ODT.REGION) AS DEAL_REGION,
           MAX(ODT.SETTLEMENT_DATE) AS SETTLEMENT_TS,
           MAX(ODT.SETTLEMENT_CURRENCY) AS SETTLEMENT_CURRENCY,
           COUNT(DISTINCT ODT.TRANCHE_ID) AS TRANCHE_COUNT,
           MIN(ODT.PRICING_TS) AS FIRST_PRICED,
           MAX(ODT.PRICING_TS) AS LAST_PRICED,
           MAX(OC.ORDER_COUNT) AS ORDER_COUNT,
           MAX(OC.INVESTOR_COUNT) AS INVESTOR_COUNT
    FROM DGSTREAM.OB_DEAL_TRANCHE ODT
    LEFT JOIN (
        SELECT Z.*
        FROM (
            SELECT DI.DEAL_TRANCHE_ID, DI.NAME, DI.GFCID, DI.TICKER,
                   ROW_NUMBER() OVER (PARTITION BY DI.DEAL_TRANCHE_ID
                                      ORDER BY DI.ROWID) AS RN_
            FROM DGSTREAM.OB_DEAL_ISSUER DI
        ) Z
        WHERE Z.RN_ = 1
    ) ODI
        ON ODI.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
    LEFT JOIN (
        SELECT O.ROOT_ID,
               COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT,
               COUNT(DISTINCT O.GPID) AS INVESTOR_COUNT
        FROM DGSTREAM.OB_ORDER O
        GROUP BY O.ROOT_ID
    ) OC
        ON OC.ROOT_ID = ODT.DEAL_ID
    GROUP BY ODT.DEAL_ID
) D
LEFT JOIN (
    SELECT C.DEAL_ID,
           LISTAGG(C.CURRENCY, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT)
             WITHIN GROUP (ORDER BY C.FIRST_PRICED_TS ASC NULLS LAST,
                           C.CURRENCY) AS CURRENCIES
    FROM (
        SELECT DEAL_ID, CURRENCY, MIN(PRICING_TS) AS FIRST_PRICED_TS
        FROM DGSTREAM.OB_DEAL_TRANCHE
        WHERE CURRENCY IS NOT NULL
        GROUP BY DEAL_ID, CURRENCY
    ) C
    GROUP BY C.DEAL_ID
) CU
    ON CU.DEAL_ID = D.DEAL_ID
LEFT JOIN (
    SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER
    FROM (
        SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER,
               ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID
                                  ORDER BY PUBLISHED_TS DESC) AS RN_
        FROM DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES
        WHERE PARTY_ROLE = 'Primary Client'
    ) WHERE RN_ = 1
) PCM
    ON PCM.TRANSACTION_ID = D.DEAL_ID
;
GRANT SELECT ON "DGSTREAM"."VW_DEAL_SUMMARY" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_DEAL_SUMMARY" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_DEAL_SUMMARY" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_DEAL_SUMMARY" TO "DGLOBE" WITH GRANT OPTION;
