CREATE OR REPLACE VIEW "DGSTREAM"."VW_DEAL_SUMMARY" AS
SELECT
    'ECM' AS PRODUCT,
    T.DEAL_TRANSACTION_ID AS DEAL_ID,
    T.SYNDICATE_DEAL_NAME AS DEAL_NAME,
    T.DEAL_SIZE AS DEAL_SIZE,
    T.ISSUER_NAME_FROM_SOURCE AS ISSUER_NAME,
    T.ISSUER_GFCID AS GFCID,
    T.ISSUER_TICKER AS TICKER,
    T.ISSUER_INDUSTRY_SECTOR AS SECTOR,
    T.USE_OF_PROCEEDS AS USE_OF_PROCEEDS,
    T.PRODUCT_EQUITY_TYPE_VALUE AS EQUITY_TYPE,
    T.PRODUCT_OFFERING_TYPE_VALUE AS OFFERING_TYPE,
    S.STATUS_VALUE AS DEAL_STATUS,
    S.STATUS_TYPE AS EXECUTION_STATUS,
    OBT.DEAL_REGION AS DEAL_REGION,
    T.SETTLEMENT_TS AS SETTLEMENT_TS,
    T.SETTLEMENT_CURRENCY_NAME AS SETTLEMENT_CURRENCY,
    TR.TRANCHE_COUNT AS TRANCHE_COUNT,
    TR.FIRST_PRICED AS FIRST_PRICED,
    TR.LAST_PRICED AS LAST_PRICED,
    TC.CURRENCIES AS CURRENCIES,
    OD.ORDER_COUNT AS ORDER_COUNT,
    OD.INVESTOR_COUNT AS INVESTOR_COUNT
FROM DGSTREAM.OPUS_ECM_TRANSACTION T
INNER JOIN DGSTREAM.OPUS_ECM_TRANSACTION_STATUS S
    ON T.ECM_TRANSACTION_ID = S.ECM_TRANSACTION_ID
    AND S.STATUS_TYPE = 'Execution_Status'
    AND S.STATUS_VALUE NOT IN ('Confidential', 'Withdrawn', 'Terminated')
LEFT JOIN DGSTREAM.OPUS_BASE_TRANSACTION OBT
    ON T.DEAL_TRANSACTION_ID = OBT.TRANSACTION_ID
LEFT JOIN (
    SELECT
        TT.ECM_TRANSACTION_ID,
        COUNT(DISTINCT TT.ECM_TRANSACTION_TRANCHE_ID) AS TRANCHE_COUNT,
        MIN(TT.PRICING_TS) AS FIRST_PRICED,
        MAX(TT.PRICING_TS) AS LAST_PRICED
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE TT
    GROUP BY TT.ECM_TRANSACTION_ID
) TR
    ON T.ECM_TRANSACTION_ID = TR.ECM_TRANSACTION_ID
LEFT JOIN (
    SELECT
        C.ECM_TRANSACTION_ID,
        LISTAGG(C.TRANCHE_CURRENCY_ID, ' | ') WITHIN GROUP (ORDER BY C.TRANCHE_CURRENCY_ID) AS CURRENCIES
    FROM (
        SELECT DISTINCT
            TT.ECM_TRANSACTION_ID,
            TT.TRANCHE_CURRENCY_ID
        FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE TT
    ) C
    GROUP BY C.ECM_TRANSACTION_ID
) TC
    ON T.ECM_TRANSACTION_ID = TC.ECM_TRANSACTION_ID
LEFT JOIN (
    SELECT
        O.DEAL_ID,
        COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT,
        COUNT(DISTINCT O.INVESTOR_GPNUM) AS INVESTOR_COUNT
    FROM DGSTREAM.OB_ECM_ORDER O
    WHERE O.IS_OWNED = 'true'
      AND O.ORDER_STATUS NOT IN ('CANCELLED', 'DELETED', 'PASS')
      AND ((O.IS_MATCHED = 'true' AND O.IS_DOMINANT = 'true') OR O.IS_MATCHED = 'false')
    GROUP BY O.DEAL_ID
) OD
    ON T.DEAL_TRANSACTION_ID = OD.DEAL_ID

UNION ALL

SELECT
    'DCM' AS PRODUCT,
    D.DEAL_ID AS DEAL_ID,
    D.DEAL_NAME AS DEAL_NAME,
    D.DEAL_SIZE AS DEAL_SIZE,
    D.ISSUER_NAME AS ISSUER_NAME,
    D.GFCID AS GFCID,
    D.TICKER AS TICKER,
    D.SECTOR AS SECTOR,
    D.USE_OF_PROCEEDS AS USE_OF_PROCEEDS,
    CAST(NULL AS VARCHAR2(4000)) AS EQUITY_TYPE,
    CAST(NULL AS VARCHAR2(4000)) AS OFFERING_TYPE,
    D.DEAL_STATUS AS DEAL_STATUS,
    CAST(NULL AS VARCHAR2(4000)) AS EXECUTION_STATUS,
    CAST(NULL AS VARCHAR2(400)) AS DEAL_REGION,
    CAST(NULL AS TIMESTAMP(6)) AS SETTLEMENT_TS,
    D.SETTLEMENT_CURRENCY AS SETTLEMENT_CURRENCY,
    D.TRANCHE_COUNT AS TRANCHE_COUNT,
    D.FIRST_PRICED AS FIRST_PRICED,
    D.LAST_PRICED AS LAST_PRICED,
    D.CURRENCIES AS CURRENCIES,
    D.ORDER_COUNT AS ORDER_COUNT,
    D.INVESTOR_COUNT AS INVESTOR_COUNT
FROM (
    SELECT
        ODT.DEAL_ID,
        MAX(ODT.DEAL_NAME) AS DEAL_NAME,
        MAX(NVL(ODT.DEAL_ISSUE_SIZE, 0)) AS DEAL_SIZE,
        MAX(ODI.NAME) AS ISSUER_NAME,
        MAX(ODI.GFCID) AS GFCID,
        MAX(ODI.TICKER) AS TICKER,
        MAX(ODT.ISSUER_SECTOR) AS SECTOR,
        MAX(ODT.USE_OF_PROCEEDS) AS USE_OF_PROCEEDS,
        MAX(ODT.STATUS) AS DEAL_STATUS,
        MAX(ODT.SETTLEMENT_CURRENCY) AS SETTLEMENT_CURRENCY,
        COUNT(DISTINCT ODT.TRANCHE_ID) AS TRANCHE_COUNT,
        MIN(ODT.PRICING_TS) AS FIRST_PRICED,
        MAX(ODT.PRICING_TS) AS LAST_PRICED,
        LISTAGG(ODT.CURRENCY, ' | ') WITHIN GROUP (ORDER BY ODT.CURRENCY) AS CURRENCIES,
        MAX(OC.ORDER_COUNT) AS ORDER_COUNT,
        MAX(OC.INVESTOR_COUNT) AS INVESTOR_COUNT
    FROM DGSTREAM.OB_DEAL_TRANCHE ODT
    LEFT JOIN DGSTREAM.OB_DEAL_ISSUER ODI
        ON ODI.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
    LEFT JOIN (
        SELECT
            O.ROOT_ID,
            COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT,
            COUNT(DISTINCT O.GPID) AS INVESTOR_COUNT
        FROM DGSTREAM.OB_ORDER O
        GROUP BY O.ROOT_ID
    ) OC
        ON OC.ROOT_ID = ODT.DEAL_ID
    GROUP BY ODT.DEAL_ID
) D;

GRANT SELECT ON "DGSTREAM"."VW_DEAL_SUMMARY" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_DEAL_SUMMARY" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_DEAL_SUMMARY" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_DEAL_SUMMARY" TO "DGLOBE" WITH GRANT OPTION;
