CREATE OR REPLACE VIEW "DGSTREAM"."VW_ENTITY_SEARCH" AS
SELECT
    'INVESTOR' AS ENTITY_TYPE,
    O.PRODUCT AS PRODUCT,
    O.INVESTOR_NAME AS ENTITY_NAME,
    O.INVESTOR_GP_ID AS ENTITY_ID,
    COUNT(DISTINCT O.DEAL_ID) AS ENTITY_ACTIVITY_COUNT,
    MAX(O.PRICING_TS) AS LAST_ACTIVE,
    MAX(O.INVESTOR_CATEGORY) AS CONTEXT_VALUE_1,
    MAX(O.INVESTOR_REGION) AS CONTEXT_VALUE_2
FROM DGSTREAM.VW_ORDER_DETAIL O
WHERE O.INVESTOR_NAME IS NOT NULL
GROUP BY
    O.PRODUCT,
    O.INVESTOR_NAME,
    O.INVESTOR_GP_ID

UNION ALL

SELECT
    'ISSUER' AS ENTITY_TYPE,
    D.PRODUCT AS PRODUCT,
    D.ISSUER_NAME AS ENTITY_NAME,
    D.GFCID AS ENTITY_ID,
    COUNT(DISTINCT D.DEAL_ID) AS ENTITY_ACTIVITY_COUNT,
    MAX(D.LAST_PRICED) AS LAST_ACTIVE,
    MAX(D.SECTOR) AS CONTEXT_VALUE_1,
    MAX(D.TICKER) AS CONTEXT_VALUE_2
FROM DGSTREAM.VW_DEAL_SUMMARY D
WHERE D.ISSUER_NAME IS NOT NULL
GROUP BY
    D.PRODUCT,
    D.ISSUER_NAME,
    D.GFCID

UNION ALL

SELECT
    'DEAL' AS ENTITY_TYPE,
    D.PRODUCT AS PRODUCT,
    D.DEAL_NAME AS ENTITY_NAME,
    D.DEAL_ID AS ENTITY_ID,
    D.TRANCHE_COUNT AS ENTITY_ACTIVITY_COUNT,
    D.LAST_PRICED AS LAST_ACTIVE,
    D.DEAL_STATUS AS CONTEXT_VALUE_1,
    D.ISSUER_NAME AS CONTEXT_VALUE_2
FROM DGSTREAM.VW_DEAL_SUMMARY D;

GRANT SELECT ON "DGSTREAM"."VW_ENTITY_SEARCH" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_ENTITY_SEARCH" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_ENTITY_SEARCH" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_ENTITY_SEARCH" TO "DGLOBE" WITH GRANT OPTION;
