CREATE OR REPLACE VIEW "DGSTREAM"."VW_HEDGE_ORDER" AS
SELECT
    'DCM' AS PRODUCT,
    H.ROOT_ID AS DEAL_ID,
    H.PARENT_ID AS TRANCHE_ID,
    H.SIBLING_ID AS ORDER_ID,
    H.HEDGE_ORDER_ID AS HEDGE_ORDER_ID,
    H.HEDGE_TYPE AS HEDGE_TYPE,
    H.HEDGE_SOURCE AS HEDGE_SOURCE,
    H.STATUS AS HEDGE_STATUS,
    H.BND AS HEDGE_MANAGER,
    H.SETTLEMENT_PERIOD AS SETTLEMENT_PERIOD,
    H.SETTLEMENT_DATE AS SETTLEMENT_TS,
    H.INVESTOR_NAME AS INVESTOR_NAME,
    H.INVESTOR_GPID AS INVESTOR_GP_ID,
    H.INVESTOR_LEID AS INVESTOR_LEI,
    H.INVESTOR_COUNTRY_NAME AS INVESTOR_REGION,
    H.INVESTOR_TYPE AS INVESTOR_CATEGORY,
    H.INVESTOR_QIB_STATUS AS INVESTOR_QIB_STATUS,
    TRIM(H.SALES_FIRSTNAME || ' ' || H.SALES_LASTNAME) AS SALES_PERSON,
    H.HEDGESIZE_AMOUNT AS HEDGE_AMOUNT,
    H.HEDGESIZE_ISNAMOUNT AS HEDGE_ISN_AMOUNT,
    H.HEDGESIZE_WEIGHT AS HEDGE_WEIGHT_TYPE,
    H.HEDGESIZE_PCTFACE AS HEDGE_PCT_FACE,
    H.HEDGESECURITY_ISIN AS SECURITY_ISIN,
    H.HEDGESECURITY_CUSIP AS SECURITY_CUSIP,
    H.HEDGESECURITY_NAME AS SECURITY_NAME,
    H.HEDGESECURITY_MATURITY_DATE AS SECURITY_MATURITY_TS,
    H.HEDGESECURITY_COUPON AS SECURITY_COUPON,
    H.HEDGESECURITY_COUPON_TYPE AS SECURITY_COUPON_TYPE,
    H.HEDGESECURITY_TYPE AS SECURITY_TYPE,
    H.HEDGESECURITY_ISSUER AS SECURITY_ISSUER,
    CAST(H.PUBLISHED_TS AS TIMESTAMP(6)) AS PUBLISHED_TS
FROM (
    SELECT W.*
    FROM (
        SELECT HO.*,
               ROW_NUMBER() OVER (PARTITION BY HO.HEDGE_ORDER_ID
                                  ORDER BY HO.PUBLISHED_TS DESC,
                                           HO.ROWID) AS RN_
        FROM DGSTREAM.OB_HEDGE_ORDER HO
        WHERE HO.HEDGE_ORDER_ID IS NOT NULL
    ) W
    WHERE W.RN_ = 1
) H
;
GRANT SELECT ON "DGSTREAM"."VW_HEDGE_ORDER" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_HEDGE_ORDER" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_HEDGE_ORDER" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_HEDGE_ORDER" TO "DGLOBE" WITH GRANT OPTION;
