CREATE OR REPLACE VIEW "DGSTREAM"."VW_HEDGE_TRADE" AS
SELECT
    'DCM' AS PRODUCT,
    H.ROOT_ID AS DEAL_ID,
    DN.DEAL_NAME AS DEAL_NAME,
    H.PARENT_ID AS TRANCHE_ID,
    H.SIBLING_ID AS HEDGE_ORDER_ID,
    DN.TRANSACTION_ID AS TRANSACTION_ID,
    TN.TENORS AS TENORS,
    H.HEDGE_TRADE_ID AS HEDGE_TRADE_ID,
    H.TYPE AS TRADE_TYPE,
    H.SUB_TYPE AS TRADE_SUB_TYPE,
    H.DIRECTION AS DIRECTION,
    H.HEDGE_TYPE AS HEDGE_TYPE,
    H.BND AS HEDGE_MANAGER,
    H.SETTLEMENT_PERIOD AS SETTLEMENT_PERIOD,
    H.COUNTERPARTY_NAME AS COUNTERPARTY_NAME,
    H.COUNTERPARTY_GPID AS COUNTERPARTY_GP_ID,
    H.COUNTERPARTY_TYPE AS COUNTERPARTY_TYPE,
    CAST(H.HEDGESIZE_AMOUNT AS NUMBER(38,4)) AS HEDGE_AMOUNT,
    H.HEDGESIZE_WEIGHT AS HEDGE_WEIGHT_TYPE,
    CAST(H.HEDGESIZE_PCTFACE AS NUMBER(38,9)) AS HEDGE_PCT_FACE,
    H.HEDGESECURITY_ISIN AS SECURITY_ISIN,
    H.HEDGESECURITY_CUSIP AS SECURITY_CUSIP,
    H.HEDGESECURITY_NAME AS SECURITY_NAME,
    H.HEDGESECURITY_MATURITY_DATE AS SECURITY_MATURITY_TS,
    CAST(H.HEDGESECURITY_COUPON AS NUMBER(38,9)) AS SECURITY_COUPON,
    H.HEDGESECURITY_COUPON_TYPE AS SECURITY_COUPON_TYPE,
    H.HEDGESECURITY_TYPE AS SECURITY_TYPE,
    H.HEDGESECURITY_ISSUER AS SECURITY_ISSUER,
    TRIM(H.SALES_FIRSTNAME || ' ' || H.SALES_LASTNAME) AS SALES_PERSON,
    H.SALES_REGION AS SALES_REGION,
    H.TRADE_TRADE_REFERENCE AS TRADE_REFERENCE,
    H.TRADE_STATUS AS TRADE_STATUS,
    CAST(H.PUBLISHED_TS AS TIMESTAMP(6)) AS PUBLISHED_TS
FROM (
    SELECT W.*
    FROM (
        SELECT HT.*,
               ROW_NUMBER() OVER (PARTITION BY HT.ROOT_ID, HT.HEDGE_TRADE_ID
                                  ORDER BY HT.PUBLISHED_TS DESC,
                                           HT.ROWID) AS RN_
        FROM DGSTREAM.OB_HEDGE_TRADE HT
        WHERE HT.HEDGE_TRADE_ID IS NOT NULL
    ) W
    WHERE W.RN_ = 1
) H
LEFT JOIN (
    SELECT DEAL_ID, MAX(DEAL_NAME) AS DEAL_NAME,
           MAX(ORIGINATION_TRANSACTION_ID) AS TRANSACTION_ID
    FROM DGSTREAM.OB_DEAL_TRANCHE
    GROUP BY DEAL_ID
) DN
    ON DN.DEAL_ID = H.ROOT_ID
LEFT JOIN (
    SELECT Z.DEAL_ID, Z.TRANCHE_ID,
           CASE WHEN Z.TENOR_VALUE IS NULL AND Z.TENOR_PERIOD IS NULL
                THEN NULL
                ELSE Z.TENOR_VALUE || '-' || Z.TENOR_PERIOD
           END AS TENORS
    FROM (
        SELECT DT.DEAL_ID, DT.TRANCHE_ID, DT.TENOR_VALUE, DT.TENOR_PERIOD,
               ROW_NUMBER() OVER (PARTITION BY DT.DEAL_ID, DT.TRANCHE_ID
                                  ORDER BY DT.ROWID) AS RN_
        FROM DGSTREAM.OB_DEAL_TRANCHE DT
    ) Z
    WHERE Z.RN_ = 1
) TN
    ON TN.DEAL_ID = H.ROOT_ID
    AND TN.TRANCHE_ID = H.PARENT_ID
;
GRANT SELECT ON "DGSTREAM"."VW_HEDGE_TRADE" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_HEDGE_TRADE" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_HEDGE_TRADE" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_HEDGE_TRADE" TO "DGLOBE" WITH GRANT OPTION;
