CREATE OR REPLACE VIEW "DGSTREAM"."VW_ORDER_DETAIL" AS
SELECT
    'ECM' AS PRODUCT,
    O.DEAL_ID AS DEAL_ID,
    T.SYNDICATE_DEAL_NAME AS DEAL_NAME,
    O.TRANCHE_ID AS TRANCHE_ID,
    TT.TRANCHE_NAME AS TRANCHE_NAME,
    O.ORDER_ID AS ORDER_ID,
    O.INVESTOR_NAME AS INVESTOR_NAME,
    O.INVESTOR_GPNUM AS INVESTOR_GP_ID,
    O.INVESTOR_REGION AS INVESTOR_REGION,
    O.INVESTOR_CATEGORY_KEY AS INVESTOR_CATEGORY_KEY,
    O.INVESTOR_CATEGORY_VALUE AS INVESTOR_CATEGORY,
    O.MEETING_TYPE_KEY AS MEETING_TYPE_KEY,
    O.MEETING_TYPE_VALUE AS MEETING_TYPE,
    O.ORDER_TYPE AS ORDER_TYPE,
    O.IOI_TYPE AS IOI_TYPE,
    NVL(OI.LIMIT_VALUE, 0) AS ORDER_AMOUNT,
    O.DEMAND_QTY AS ORDER_DEMAND_QTY,
    NVL(O.PRIVATE_ALLOC, 0) AS ORDER_ALLOCATION,
    CAST(TT.PRICING_TS AS TIMESTAMP(3)) AS PRICING_TS,
    TDC.CURRENCY_NAME AS CURRENCY
FROM DGSTREAM.OB_ECM_ORDER O
INNER JOIN DGSTREAM.OPUS_ECM_TRANSACTION T
    ON O.DEAL_ID = T.DEAL_TRANSACTION_ID
    AND O.IS_OWNED = 'true'
    AND O.ORDER_STATUS NOT IN ('CANCELLED', 'DELETED', 'PASS')
    AND ((O.IS_MATCHED = 'true' AND O.IS_DOMINANT = 'true') OR O.IS_MATCHED = 'false')
INNER JOIN DGSTREAM.OPUS_ECM_TRANSACTION_STATUS S
    ON T.ECM_TRANSACTION_ID = S.ECM_TRANSACTION_ID
    AND S.STATUS_TYPE = 'Execution_Status'
    AND S.STATUS_VALUE NOT IN ('Confidential', 'Withdrawn', 'Terminated')
LEFT JOIN DGSTREAM.OB_ECM_ORDER_IOI OI
    ON O.ORDER_ID = OI.ORDER_ID
LEFT JOIN DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE TT
    ON T.ECM_TRANSACTION_ID = TT.ECM_TRANSACTION_ID
    AND TO_CHAR(TT.ECM_TRANSACTION_TRANCHE_ID) = O.TRANCHE_ID
LEFT JOIN DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY TDC
    ON TT.ECM_TRANSACTION_ID = TDC.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = TDC.ECM_TRANSACTION_TRANCHE_ID
    AND TT.TRANCHE_CURRENCY_ID = TDC.CURRENCY_ID

UNION ALL

SELECT
    'DCM' AS PRODUCT,
    O.ROOT_ID AS DEAL_ID,
    ODT.DEAL_NAME AS DEAL_NAME,
    O.PARENT_ID AS TRANCHE_ID,
    ODT.NAME AS TRANCHE_NAME,
    O.ORDER_ID AS ORDER_ID,
    O.NAME AS INVESTOR_NAME,
    O.GPID AS INVESTOR_GP_ID,
    CAST(NULL AS VARCHAR2(1020)) AS INVESTOR_REGION,
    CAST(NULL AS VARCHAR2(1020)) AS INVESTOR_CATEGORY_KEY,
    CAST(NULL AS VARCHAR2(1020)) AS INVESTOR_CATEGORY,
    CAST(NULL AS VARCHAR2(1020)) AS MEETING_TYPE_KEY,
    CAST(NULL AS VARCHAR2(1020)) AS MEETING_TYPE,
    CAST(NULL AS VARCHAR2(1020)) AS ORDER_TYPE,
    CAST(NULL AS VARCHAR2(400)) AS IOI_TYPE,
    NVL(OZ.AMT, 0) AS ORDER_AMOUNT,
    NVL(OZ.AMT, 0) AS ORDER_DEMAND_QTY,
    NVL(OMT.FINAL_ALLOC, 0) AS ORDER_ALLOCATION,
    ODT.PRICING_TS AS PRICING_TS,
    ODT.CURRENCY AS CURRENCY
FROM DGSTREAM.OB_ORDER O
INNER JOIN DGSTREAM.OB_DEAL_TRANCHE ODT
    ON ODT.DEAL_ID = O.ROOT_ID
    AND ODT.TRANCHE_ID = O.PARENT_ID
LEFT JOIN DGSTREAM.OB_ORDER_SIZE OZ
    ON O.ORDER_ID = OZ.ORDER_ID
LEFT JOIN DGSTREAM.OB_ORDER_MATCH_GROUP OMT
    ON OMT.ROOT_ID = O.ROOT_ID
    AND OMT.PARENT_ID = O.PARENT_ID;

GRANT SELECT ON "DGSTREAM"."VW_ORDER_DETAIL" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_ORDER_DETAIL" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_ORDER_DETAIL" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_ORDER_DETAIL" TO "DGLOBE" WITH GRANT OPTION;
