CREATE OR REPLACE VIEW "DGSTREAM"."VW_ORDER_DETAIL" AS
SELECT
    'ECM' AS PRODUCT,
    O.DEAL_ID AS DEAL_ID,
    T.SYNDICATE_DEAL_NAME AS DEAL_NAME,
    O.TRANCHE_ID AS TRANCHE_ID,
    TT.TRANCHE_NAME AS TRANCHE_NAME,
    O.ORDER_ID AS ORDER_ID,
    O.INVESTOR_NAME AS INVESTOR_NAME,
    O.INVESTOR_GPNUM AS INVESTOR_GP_ID,
    O.INVESTOR_REGION AS INVESTOR_REGION,
    O.INVESTOR_CATEGORY_KEY AS INVESTOR_CATEGORY_KEY,
    O.INVESTOR_CATEGORY_VALUE AS INVESTOR_CATEGORY,
    O.MEETING_TYPE_KEY AS MEETING_TYPE_KEY,
    O.MEETING_TYPE_VALUE AS MEETING_TYPE,
    O.ORDER_TYPE AS ORDER_TYPE,
    O.IOI_TYPE AS IOI_TYPE,
    NVL(OI.LIMIT_VALUE, 0) AS ORDER_AMOUNT,
    O.DEMAND_QTY AS ORDER_DEMAND_QTY,
    NVL(O.PRIVATE_ALLOC, 0) AS ORDER_ALLOCATION,
    CAST(TT.PRICING_TS AS TIMESTAMP(3)) AS PRICING_TS,
    NVL(TDC.CURRENCY_NAME, GC.CURRENCY_NAME) AS CURRENCY,
    NVL(PCM.PARTY_NAME, NVL(OIN.ISSUER_NAME_BY_GFCID, T.ISSUER_NAME_FROM_SOURCE)) AS ISSUER_NAME,
    T.ISSUER_INDUSTRY_SECTOR AS SECTOR,
    CASE WHEN TT.TRANCHE_OFFER_SIZE IS NULL THEN 0
         WHEN REGEXP_LIKE(TO_CHAR(TT.TRANCHE_OFFER_SIZE),
                          '^\s*[+-]?[0-9]+(\.[0-9]+)?([Ee][+-]?[0-9]+)?\s*$')
         THEN TO_NUMBER(TRIM(TO_CHAR(TT.TRANCHE_OFFER_SIZE)))
         ELSE NULL END AS TRANCHE_SIZE,
    O.BILLEDBY_BROKER_CODE AS BILLED_BY,
    T.PRODUCT_OFFERING_TYPE_VALUE AS OFFERING_TYPE,
    T.PRODUCT_EQUITY_TYPE_VALUE AS EQUITY_TYPE,
    CASE WHEN O.IS_OWNED = 'true' THEN 'HOME'
         WHEN O.IS_OWNED = 'false' THEN 'AWAY'
         ELSE NULL END AS ORDER_OWNERSHIP,
    O.DEAL_ID AS TRANSACTION_ID
FROM (
    SELECT E.*
    FROM (
        SELECT EO.*,
               ROW_NUMBER() OVER (PARTITION BY EO.ORDER_ID ORDER BY EO.ROWID) AS RN_
        FROM DGSTREAM.OB_ECM_ORDER EO
    ) E
    WHERE E.RN_ = 1
) O
INNER JOIN (
    SELECT X.*
    FROM (
        SELECT ET.ECM_TRANSACTION_ID, ET.DEAL_TRANSACTION_ID,
               ET.SYNDICATE_DEAL_NAME, ET.ISSUER_NAME_FROM_SOURCE,
               ET.ISSUER_INDUSTRY_SECTOR, ET.PRODUCT_OFFERING_TYPE_VALUE,
               ET.PRODUCT_EQUITY_TYPE_VALUE,
               ET.ISSUER_GFCID,
               ROW_NUMBER() OVER (PARTITION BY ET.ECM_TRANSACTION_ID
                                  ORDER BY ET.ROWID) AS RN_
        FROM DGSTREAM.OPUS_ECM_TRANSACTION ET
    ) X
    WHERE X.RN_ = 1
) T
    ON O.DEAL_ID = T.DEAL_TRANSACTION_ID
    AND O.ORDER_STATUS NOT IN ('CANCELLED', 'DELETED', 'PASS')
    AND ((O.IS_MATCHED = 'true' AND O.IS_DOMINANT = 'true') OR O.IS_MATCHED = 'false')
INNER JOIN (
    SELECT ECM_TRANSACTION_ID,
           MAX(STATUS_VALUE) AS STATUS_VALUE
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_STATUS
    WHERE STATUS_TYPE = 'Execution_Status'
      AND STATUS_VALUE NOT IN ('Confidential', 'Withdrawn', 'Terminated')
    GROUP BY ECM_TRANSACTION_ID
) S
    ON T.ECM_TRANSACTION_ID = S.ECM_TRANSACTION_ID
LEFT JOIN (
    SELECT ORDER_ID, MAX(LIMIT_VALUE) AS LIMIT_VALUE
    FROM DGSTREAM.OB_ECM_ORDER_IOI
    GROUP BY ORDER_ID
) OI
    ON O.ORDER_ID = OI.ORDER_ID
LEFT JOIN (
    SELECT W.*
    FROM (
        SELECT TTR.ECM_TRANSACTION_ID, TTR.ECM_TRANSACTION_TRANCHE_ID,
               TTR.TRANCHE_NAME, TTR.PRICING_TS, TTR.TRANCHE_CURRENCY_ID,
               TTR.TRANCHE_OFFER_SIZE,
               ROW_NUMBER() OVER (PARTITION BY TTR.ECM_TRANSACTION_ID,
                                               TTR.ECM_TRANSACTION_TRANCHE_ID
                                  ORDER BY TTR.ROWID) AS RN_
        FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE TTR
    ) W
    WHERE W.RN_ = 1
) TT
    ON T.ECM_TRANSACTION_ID = TT.ECM_TRANSACTION_ID
    AND TO_CHAR(TT.ECM_TRANSACTION_TRANCHE_ID) = O.TRANCHE_ID
LEFT JOIN (
    SELECT ECM_TRANSACTION_ID, ECM_TRANSACTION_TRANCHE_ID, CURRENCY_ID,
           MAX(CURRENCY_NAME) AS CURRENCY_NAME
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY
    GROUP BY ECM_TRANSACTION_ID, ECM_TRANSACTION_TRANCHE_ID, CURRENCY_ID
) TDC
    ON TT.ECM_TRANSACTION_ID = TDC.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = TDC.ECM_TRANSACTION_TRANCHE_ID
    AND TT.TRANCHE_CURRENCY_ID = TDC.CURRENCY_ID
LEFT JOIN (
    SELECT CURRENCY_ID, MAX(CURRENCY_NAME) AS CURRENCY_NAME
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY
    GROUP BY CURRENCY_ID
) GC
    ON GC.CURRENCY_ID = TT.TRANCHE_CURRENCY_ID

LEFT JOIN (
    SELECT GFCID, MAX(NAME) AS ISSUER_NAME_BY_GFCID
    FROM DGSTREAM.OB_DEAL_ISSUER
    WHERE GFCID IS NOT NULL AND NAME IS NOT NULL
    GROUP BY GFCID
) OIN
    ON OIN.GFCID = T.ISSUER_GFCID

LEFT JOIN (
    SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER
    FROM (
        SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER,
               ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID
                                  ORDER BY PUBLISHED_TS DESC) AS RN_
        FROM DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES
        WHERE PARTY_ROLE = 'Primary Client'
    ) WHERE RN_ = 1
) PCM
    ON PCM.TRANSACTION_ID = T.DEAL_TRANSACTION_ID

UNION ALL

SELECT
    'DCM' AS PRODUCT,
    O.ROOT_ID AS DEAL_ID,
    ODT.DEAL_NAME AS DEAL_NAME,
    O.PARENT_ID AS TRANCHE_ID,
    ODT.NAME AS TRANCHE_NAME,
    O.ORDER_ID AS ORDER_ID,
    O.NAME AS INVESTOR_NAME,
    O.GPID AS INVESTOR_GP_ID,
    CAST(NULL AS VARCHAR2(1020)) AS INVESTOR_REGION,
    CAST(NULL AS VARCHAR2(1020)) AS INVESTOR_CATEGORY_KEY,
    CAST(NULL AS VARCHAR2(1020)) AS INVESTOR_CATEGORY,
    CAST(NULL AS VARCHAR2(1020)) AS MEETING_TYPE_KEY,
    CAST(NULL AS VARCHAR2(1020)) AS MEETING_TYPE,
    CAST(NULL AS VARCHAR2(1020)) AS ORDER_TYPE,
    CAST(NULL AS VARCHAR2(400)) AS IOI_TYPE,
    NVL(OZ.AMT, 0) AS ORDER_AMOUNT,
    NVL(OZ.AMT, 0) AS ORDER_DEMAND_QTY,
    NVL(O.FINAL_ALLOC, 0) AS ORDER_ALLOCATION,
    ODT.PRICING_TS AS PRICING_TS,
    ODT.CURRENCY AS CURRENCY,
    NVL(PCM.PARTY_NAME, ODI.NAME) AS ISSUER_NAME,
    ODT.ISSUER_SECTOR AS SECTOR,
    CASE WHEN ODT.TRANCHE_SIZE IS NULL THEN 0
         WHEN REGEXP_LIKE(TO_CHAR(ODT.TRANCHE_SIZE),
                          '^\s*[+-]?[0-9]+(\.[0-9]+)?([Ee][+-]?[0-9]+)?\s*$')
         THEN TO_NUMBER(TRIM(TO_CHAR(ODT.TRANCHE_SIZE)))
         ELSE NULL END AS TRANCHE_SIZE,
    O.BND AS BILLED_BY,
    CAST(NULL AS VARCHAR2(4000)) AS OFFERING_TYPE,
    CAST(NULL AS VARCHAR2(4000)) AS EQUITY_TYPE,
    CAST(NULL AS VARCHAR2(20)) AS ORDER_OWNERSHIP,
    ODT.ORIGINATION_TRANSACTION_ID AS TRANSACTION_ID
FROM (
    SELECT D.*
    FROM (
        SELECT DO.ORDER_ID, DO.ROOT_ID, DO.PARENT_ID, DO.NAME, DO.GPID,
               DO.FINAL_ALLOC, DO.BND,
               ROW_NUMBER() OVER (PARTITION BY DO.ORDER_ID ORDER BY DO.ROWID) AS RN_
        FROM DGSTREAM.OB_ORDER DO
    ) D
    WHERE D.RN_ = 1
) O
INNER JOIN (
    SELECT Y.*
    FROM (
        SELECT DT.DEAL_ID, DT.TRANCHE_ID, DT.DEAL_NAME, DT.NAME,
               DT.PRICING_TS, DT.CURRENCY, DT.ISSUER_SECTOR, DT.TRANCHE_SIZE,
               DT.ORIGINATION_TRANSACTION_ID,
               ROW_NUMBER() OVER (PARTITION BY DT.DEAL_ID, DT.TRANCHE_ID
                                  ORDER BY DT.ROWID) AS RN_
        FROM DGSTREAM.OB_DEAL_TRANCHE DT
    ) Y
    WHERE Y.RN_ = 1
) ODT
    ON ODT.DEAL_ID = O.ROOT_ID
    AND ODT.TRANCHE_ID = O.PARENT_ID
LEFT JOIN (
    SELECT ORDER_ID, MAX(AMT) AS AMT
    FROM DGSTREAM.OB_ORDER_SIZE
    GROUP BY ORDER_ID
) OZ
    ON O.ORDER_ID = OZ.ORDER_ID
LEFT JOIN (
    SELECT Z.*
    FROM (
        SELECT DI.DEAL_TRANCHE_ID, DI.NAME,
               ROW_NUMBER() OVER (PARTITION BY DI.DEAL_TRANCHE_ID
                                  ORDER BY DI.ROWID) AS RN_
        FROM DGSTREAM.OB_DEAL_ISSUER DI
    ) Z
    WHERE Z.RN_ = 1
) ODI
    ON ODI.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
LEFT JOIN (
    SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER
    FROM (
        SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER,
               ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID
                                  ORDER BY PUBLISHED_TS DESC) AS RN_
        FROM DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES
        WHERE PARTY_ROLE = 'Primary Client'
    ) WHERE RN_ = 1
) PCM
    ON PCM.TRANSACTION_ID = ODT.ORIGINATION_TRANSACTION_ID
;
GRANT SELECT ON "DGSTREAM"."VW_ORDER_DETAIL" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_ORDER_DETAIL" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_ORDER_DETAIL" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_ORDER_DETAIL" TO "DGLOBE" WITH GRANT OPTION;
