CREATE OR REPLACE VIEW "DGSTREAM"."VW_TRADE_DETAIL" AS
SELECT
    'DCM' AS PRODUCT,
    T.ROOT_ID AS DEAL_ID,
    T.PARENT_ID AS TRANCHE_ID,
    T.SIBLING_ID AS ORDER_ID,
    T.ORDER_TRADE_ID AS TRADE_ID,
    T.PARENT_TRADE_ID AS PARENT_TRADE_ID,
    T.TYPE AS TRADE_TYPE,
    T.SUB_TYPE AS TRADE_SUB_TYPE,
    T.ALLOCATION_TYPE AS ALLOCATION_TYPE,
    T.DIRECTION AS DIRECTION,
    T.BND AS BILLED_BY,
    T.COUNTERPARTY_NAME AS COUNTERPARTY_NAME,
    T.COUNTERPARTY_GPID AS COUNTERPARTY_GP_ID,
    T.COUNTERPARTY_TYPE AS COUNTERPARTY_TYPE,
    TRIM(T.SALES_FIRSTNAME || ' ' || T.SALES_LASTNAME) AS SALES_PERSON,
    T.SALES_REGION AS SALES_REGION,
    T.TRADE_SIZE AS TRADE_SIZE,
    T.ALLOCATION_FINALALLOC AS TRADE_ALLOCATION,
    T.PRICE_BASIS_CODE AS PRICE_BASIS_CODE,
    T.PRICE_BASIS_VALUE AS PRICE_BASIS_VALUE,
    T.TRADE_STATUS AS TRADE_STATUS,
    T.TRADE_TRADE_REFERENCE AS TRADE_REFERENCE,
    T.TRADE_SOURCE_SYSTEM AS TRADE_SOURCE_SYSTEM,
    CAST(T.PUBLISHED_TS AS TIMESTAMP(6)) AS PUBLISHED_TS
FROM (
    SELECT W.*
    FROM (
        SELECT OT.*,
               ROW_NUMBER() OVER (PARTITION BY OT.ORDER_TRADE_ID
                                  ORDER BY OT.PUBLISHED_TS DESC,
                                           OT.ROWID) AS RN_
        FROM DGSTREAM.OB_ORDER_TRADE OT
        WHERE OT.ORDER_TRADE_ID IS NOT NULL
    ) W
    WHERE W.RN_ = 1
) T
;
GRANT SELECT ON "DGSTREAM"."VW_TRADE_DETAIL" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRADE_DETAIL" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRADE_DETAIL" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRADE_DETAIL" TO "DGLOBE" WITH GRANT OPTION;
