CREATE OR REPLACE VIEW "DGSTREAM"."VW_TRANCHE_SUMMARY" AS
SELECT
    'ECM' AS PRODUCT,
    T.DEAL_TRANSACTION_ID AS DEAL_ID,
    T.SYNDICATE_DEAL_NAME AS DEAL_NAME,
    T.ISSUER_NAME_FROM_SOURCE AS ISSUER_NAME,
    T.ISSUER_GFCID AS GFCID,
    T.ISSUER_TICKER AS TICKER,
    T.ISSUER_INDUSTRY_SECTOR AS SECTOR,
    OBT.DEAL_REGION AS DEAL_REGION,
    TO_CHAR(TT.ECM_TRANSACTION_TRANCHE_ID) AS TRANCHE_ID,
    TT.TRANCHE_NAME AS TRANCHE_NAME,
    NVL(CAST(TT.TRANCHE_OFFER_SIZE AS VARCHAR2(120)), 0) AS TRANCHE_SIZE,
    CAST(TT.PRICING_TS AS TIMESTAMP(3)) AS PRICING_TS,
    TDC.CURRENCY_NAME AS CURRENCY,
    TT.REGION AS TRANCHE_REGION,
    CAST(NULL AS VARCHAR2(4000)) AS PRODUCT_CLASS,
    CAST(NULL AS VARCHAR2(400)) AS SENIORITY,
    CAST(NULL AS VARCHAR2(400)) AS REG_CATEGORY,
    CAST(NULL AS VARCHAR2(200)) AS ESG_BOND,
    CAST(NULL AS VARCHAR2(400)) AS COUPON_TYPE,
    CAST(NULL AS VARCHAR2(400)) AS COUPON_FREQ,
    T.USE_OF_PROCEEDS AS USE_OF_PROCEEDS,
    TPD.SECURITY_TYPE_NAME AS PRODUCT_TYPE,
    TPD.EXCHANGE AS EXCHANGE,
    T.SETTLEMENT_CURRENCY_NAME AS SETTLEMENT_CURRENCY,
    CAST(NULL AS VARCHAR2(4000)) AS TRANCHE_STATUS,
    S.STATUS_VALUE AS DEAL_STATUS,
    S.STATUS_TYPE AS EXECUTION_STATUS,
    SYN.SYNDICATE_MEMBER_NAME AS SYNDICATE_MEMBER_NAME,
    SYN.SYNDICATE_ROLE AS SYNDICATE_ROLE,
    SYN.BROKER_CODE AS BROKER_CODE,
    SYN.BND_BROKER AS BND_BROKER,
    SYN.BND_BANK AS BND_BANK,
    IDN.IDENTIFIER_TYPE AS IDENTIFIER_TYPE,
    IDN.IDENTIFIER_VALUE AS IDENTIFIER_VALUE,
    CAST(NULL AS VARCHAR2(4000)) AS DELIVERY_TYPE,
    CAST(NULL AS VARCHAR2(4000)) AS ISSUER_RATINGS,
    CAST(NULL AS VARCHAR2(4000)) AS TENORS,
    CAST(NULL AS VARCHAR2(4000)) AS SECURITIES_MATURITY,
    NVL(DST.DEAL_SHARING_TYPE, 'SHARED') AS DEAL_SHARING_TYPE
FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE TT
INNER JOIN DGSTREAM.OPUS_ECM_TRANSACTION T
    ON TT.ECM_TRANSACTION_ID = T.ECM_TRANSACTION_ID
INNER JOIN DGSTREAM.OPUS_ECM_TRANSACTION_STATUS S
    ON T.ECM_TRANSACTION_ID = S.ECM_TRANSACTION_ID
    AND S.STATUS_TYPE = 'Execution_Status'
    AND S.STATUS_VALUE NOT IN ('Confidential', 'Withdrawn', 'Terminated')
LEFT JOIN DGSTREAM.OPUS_BASE_TRANSACTION OBT
    ON T.DEAL_TRANSACTION_ID = OBT.TRANSACTION_ID
LEFT JOIN DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL TPD
    ON TT.ECM_TRANSACTION_ID = TPD.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = TPD.ECM_TRANSACTION_TRANCHE_ID
LEFT JOIN DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY TDC
    ON TT.ECM_TRANSACTION_ID = TDC.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = TDC.ECM_TRANSACTION_TRANCHE_ID
    AND TT.TRANCHE_CURRENCY_ID = TDC.CURRENCY_ID
LEFT JOIN (
    SELECT
        S.ECM_TRANSACTION_ID,
        S.ECM_TRANSACTION_TRANCHE_ID,
        LISTAGG(S.SYNDICATE_MEMBER_NAME, ' | ') WITHIN GROUP (ORDER BY S.BND_BROKER DESC, S.SYNDICATE_MEMBER_NAME) AS SYNDICATE_MEMBER_NAME,
        LISTAGG(S.SYNDICATE_ROLE, ' | ') WITHIN GROUP (ORDER BY S.BND_BROKER DESC, S.SYNDICATE_MEMBER_NAME) AS SYNDICATE_ROLE,
        LISTAGG(S.BROKER_CODE, ' | ') WITHIN GROUP (ORDER BY S.BND_BROKER DESC, S.SYNDICATE_MEMBER_NAME) AS BROKER_CODE,
        LISTAGG(S.BND_BROKER, ' | ') WITHIN GROUP (ORDER BY S.BND_BROKER DESC, S.SYNDICATE_MEMBER_NAME) AS BND_BROKER,
        MAX(CASE WHEN S.BND_BROKER = 'true' THEN S.SYNDICATE_MEMBER_NAME END) AS BND_BANK
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_SYNDICATE S
    GROUP BY
        S.ECM_TRANSACTION_ID,
        S.ECM_TRANSACTION_TRANCHE_ID
) SYN
    ON TT.ECM_TRANSACTION_ID = SYN.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = SYN.ECM_TRANSACTION_TRANCHE_ID
LEFT JOIN (
    SELECT
        I.ECM_TRANSACTION_ID,
        I.ECM_TRANSACTION_TRANCHE_ID,
        LISTAGG(I.IDENTIFIER_TYPE, ' | ') WITHIN GROUP (ORDER BY I.IDENTIFIER_TYPE) AS IDENTIFIER_TYPE,
        LISTAGG(I.IDENTIFIER_VALUE, ' | ') WITHIN GROUP (ORDER BY I.IDENTIFIER_TYPE) AS IDENTIFIER_VALUE
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL_IDENTIFIER I
    GROUP BY
        I.ECM_TRANSACTION_ID,
        I.ECM_TRANSACTION_TRANCHE_ID
) IDN
    ON TT.ECM_TRANSACTION_ID = IDN.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = IDN.ECM_TRANSACTION_TRANCHE_ID
LEFT JOIN (
    SELECT
        S.ECM_TRANSACTION_ID,
        S.ECM_TRANSACTION_TRANCHE_ID,
        CASE
            WHEN COUNT(DISTINCT S.SYNDICATE_MEMBER_NAME) = 1
                AND MAX(S.SYNDICATE_MEMBER_NAME) LIKE '%Citigroup Global%'
            THEN 'SOLO'
            ELSE 'SHARED'
        END AS DEAL_SHARING_TYPE
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_SYNDICATE S
    GROUP BY
        S.ECM_TRANSACTION_ID,
        S.ECM_TRANSACTION_TRANCHE_ID
) DST
    ON TT.ECM_TRANSACTION_ID = DST.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = DST.ECM_TRANSACTION_TRANCHE_ID

UNION ALL

SELECT
    'DCM' AS PRODUCT,
    ODT.DEAL_ID AS DEAL_ID,
    ODT.DEAL_NAME AS DEAL_NAME,
    ODI.NAME AS ISSUER_NAME,
    ODI.GFCID AS GFCID,
    ODI.TICKER AS TICKER,
    ODT.ISSUER_SECTOR AS SECTOR,
    ODT.REGION AS DEAL_REGION,
    ODT.TRANCHE_ID AS TRANCHE_ID,
    ODT.NAME AS TRANCHE_NAME,
    NVL(ODT.TRANCHE_SIZE, 0) AS TRANCHE_SIZE,
    ODT.PRICING_TS AS PRICING_TS,
    ODT.CURRENCY AS CURRENCY,
    ODT.TRANCHE_REGION AS TRANCHE_REGION,
    ODT.PRODUCT_CLASS AS PRODUCT_CLASS,
    ODT.SENIORITY AS SENIORITY,
    ODT.REG_CATEGORY AS REG_CATEGORY,
    ODT.ESG_BOND AS ESG_BOND,
    ODT.COUPON_TYPE AS COUPON_TYPE,
    ODT.COUPON_FREQ AS COUPON_FREQ,
    ODT.USE_OF_PROCEEDS AS USE_OF_PROCEEDS,
    CAST(NULL AS VARCHAR2(4000)) AS PRODUCT_TYPE,
    CAST(NULL AS VARCHAR2(4000)) AS EXCHANGE,
    ODT.SETTLEMENT_CURRENCY AS SETTLEMENT_CURRENCY,
    ODT.STATUS AS TRANCHE_STATUS,
    ODT.STATUS AS DEAL_STATUS,
    CAST(NULL AS VARCHAR2(4000)) AS EXECUTION_STATUS,
    ODT.BD_BANK AS SYNDICATE_MEMBER_NAME,
    CAST(NULL AS VARCHAR2(4000)) AS SYNDICATE_ROLE,
    CAST(NULL AS VARCHAR2(4000)) AS BROKER_CODE,
    CASE
        WHEN ODT.BD_BANK LIKE '%Citigroup Global%'
        THEN 'true'
        ELSE 'false'
    END AS BND_BROKER,
    ODT.BD_BANK AS BND_BANK,
    IDN.IDENTIFIER_TYPE AS IDENTIFIER_TYPE,
    IDN.IDENTIFIER_VALUE AS IDENTIFIER_VALUE,
    IDN.DELIVERY_TYPE AS DELIVERY_TYPE,
    RAT.ISSUER_RATINGS AS ISSUER_RATINGS,
    ODT.TENOR_VALUE || '-' || ODT.TENOR_PERIOD AS TENORS,
    ODT.MATURITY_DATE AS SECURITIES_MATURITY,
    NVL(DST.DEAL_SHARING_TYPE, 'SHARED') AS DEAL_SHARING_TYPE
FROM DGSTREAM.OB_DEAL_TRANCHE ODT
LEFT JOIN DGSTREAM.OB_DEAL_ISSUER ODI
    ON ODI.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
LEFT JOIN (
    SELECT
        T.DEAL_TRANCHE_ID,
        LISTAGG(T.TYPE, ' | ') WITHIN GROUP (ORDER BY T.TYPE) AS IDENTIFIER_TYPE,
        LISTAGG(T.VALUE, ' | ') WITHIN GROUP (ORDER BY T.TYPE) AS IDENTIFIER_VALUE,
        LISTAGG(T.DELIVERY_TYPE, ' | ') WITHIN GROUP (ORDER BY T.DELIVERY_TYPE) AS DELIVERY_TYPE
    FROM DGSTREAM.OB_TRANCHE T
    GROUP BY T.DEAL_TRANCHE_ID
) IDN
    ON IDN.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
LEFT JOIN (
    SELECT
        R.DEAL_TRANCHE_ID,
        LISTAGG(R.AGENCY || ' - ' || R.VALUE || '(' || R.OUTLOOK || ')', ', ')
            WITHIN GROUP (ORDER BY R.AGENCY) AS ISSUER_RATINGS
    FROM DGSTREAM.OB_TRANCHE_RATING R
    GROUP BY R.DEAL_TRANCHE_ID
) RAT
    ON RAT.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
LEFT JOIN (
    SELECT
        S.DEAL_TRANCHE_ID,
        CASE
            WHEN MIN(S.DEALER) = MAX(S.DEALER)
                AND MIN(S.DEALER) LIKE '%Citigroup Global%'
            THEN 'SOLO'
            ELSE 'SHARED'
        END AS DEAL_SHARING_TYPE
    FROM DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER S
    GROUP BY S.DEAL_TRANCHE_ID
) DST
    ON DST.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID;

GRANT SELECT ON "DGSTREAM"."VW_TRANCHE_SUMMARY" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRANCHE_SUMMARY" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRANCHE_SUMMARY" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRANCHE_SUMMARY" TO "DGLOBE" WITH GRANT OPTION;
