CREATE OR REPLACE VIEW "DGSTREAM"."VW_TRANCHE_SUMMARY" AS
SELECT
    'ECM' AS PRODUCT,
    T.DEAL_TRANSACTION_ID AS DEAL_ID,
    T.SYNDICATE_DEAL_NAME AS DEAL_NAME,
    NVL(PCM.PARTY_NAME, NVL(OIN.ISSUER_NAME_BY_GFCID, T.ISSUER_NAME_FROM_SOURCE)) AS ISSUER_NAME,
    NVL(PCM.PARTY_GFCID, T.ISSUER_GFCID) AS GFCID,
    NVL(PCM.PARTY_TICKER, T.ISSUER_TICKER) AS TICKER,
    T.ISSUER_INDUSTRY_SECTOR AS SECTOR,
    OBT.DEAL_REGION AS DEAL_REGION,
    TO_CHAR(TT.ECM_TRANSACTION_TRANCHE_ID) AS TRANCHE_ID,
    TT.TRANCHE_NAME AS TRANCHE_NAME,
    CASE WHEN TT.TRANCHE_OFFER_SIZE IS NULL THEN 0
         WHEN REGEXP_LIKE(TO_CHAR(TT.TRANCHE_OFFER_SIZE),
                          '^\s*[+-]?[0-9]+(\.[0-9]+)?([Ee][+-]?[0-9]+)?\s*$')
         THEN TO_NUMBER(TRIM(TO_CHAR(TT.TRANCHE_OFFER_SIZE)))
         ELSE NULL END AS TRANCHE_SIZE,
    CAST(TT.PRICING_TS AS TIMESTAMP(3)) AS PRICING_TS,
    NVL(TDC.CURRENCY_NAME, GC.CURRENCY_NAME) AS CURRENCY,
    NVL(TT.REGION, OBT.DEAL_REGION) AS TRANCHE_REGION,
    CAST(NULL AS VARCHAR2(4000)) AS PRODUCT_CLASS,
    CAST(NULL AS VARCHAR2(400)) AS SENIORITY,
    CAST(NULL AS VARCHAR2(400)) AS REG_CATEGORY,
    CAST(NULL AS VARCHAR2(200)) AS ESG_BOND,
    CAST(NULL AS VARCHAR2(400)) AS COUPON_TYPE,
    CAST(NULL AS VARCHAR2(400)) AS COUPON_FREQ,
    T.USE_OF_PROCEEDS AS USE_OF_PROCEEDS,
    TPD.SECURITY_TYPE_NAME AS PRODUCT_TYPE,
    TPD.EXCHANGE AS EXCHANGE,
    T.SETTLEMENT_CURRENCY_NAME AS SETTLEMENT_CURRENCY,
    CAST(NULL AS VARCHAR2(4000)) AS TRANCHE_STATUS,
    S.STATUS_VALUE AS DEAL_STATUS,
    S.STATUS_TYPE AS EXECUTION_STATUS,
    SYN.SYNDICATE_MEMBER_NAME AS SYNDICATE_MEMBER_NAME,
    SYN.SYNDICATE_ROLE AS SYNDICATE_ROLE,
    SYN.BROKER_CODE AS BROKER_CODE,
    SYN.BND_BROKER AS BND_BROKER,
    SYN.BND_BANK AS BND_BANK,
    IDN.IDENTIFIER_TYPE AS IDENTIFIER_TYPE,
    IDN.IDENTIFIER_VALUE AS IDENTIFIER_VALUE,
    CAST(NULL AS VARCHAR2(4000)) AS DELIVERY_TYPE,
    CAST(NULL AS VARCHAR2(4000)) AS ISSUER_RATINGS,
    CAST(NULL AS VARCHAR2(4000)) AS TENORS,
    CAST(NULL AS VARCHAR2(4000)) AS SECURITIES_MATURITY,
    NVL(DST.DEAL_SHARING_TYPE, 'SHARED') AS DEAL_SHARING_TYPE,
    T.PRODUCT_EQUITY_TYPE_VALUE AS EQUITY_TYPE,
    CAST(NULL AS TIMESTAMP(6)) AS SETTLEMENT_TS,
    T.DEAL_TRANSACTION_ID AS TRANSACTION_ID,
    T.ISSUER_LEID AS ISSUER_LEI,
    CAST(NULL AS VARCHAR2(80)) AS COUPON,
    CAST(NULL AS VARCHAR2(400)) AS YIELD,
    CAST(NULL AS NUMBER) AS PRICE,
    CAST(NULL AS VARCHAR2(4000)) AS PRICE_GUIDANCE,
    CAST(NULL AS VARCHAR2(400)) AS ORDER_BOOK_SIZE_USD,
    TT.TOTAL_FEE AS TOTAL_FEE,
    TT.UNDERWRITING_FEE AS UNDERWRITING_FEE,
    TT.MANAGEMENT_FEE AS MANAGEMENT_FEES,
    TT.SELLING_CONCESSION_FEE AS SELLING_CONCESSION_FEE,
    TT.PRAEPICIUM_FEE AS PRAECIPIUM_FEES,
    TT.RETAIL_UNDERWRITING_FEE AS RETAIL_UW_FEE,
    CAST(TT.ANNOUNCE_TS AS TIMESTAMP(6)) AS ANNOUNCEMENT_TS,
    CAST(NULL AS TIMESTAMP(6)) AS ISSUE_TS,
    CAST(TT.TRADE_DATE AS TIMESTAMP(6)) AS TRADE_TS,
    CAST(NULL AS VARCHAR2(400)) AS TARGET_MARKET,
    CAST(NULL AS VARCHAR2(400)) AS FRN_COUPON_INDEX,
    TT.GROSS_SPREAD_PER_FEE AS GROSS_SPREAD_PER_FEE,
    TT.DESIGNATION_FEE AS DESIGNATION_FEE,
    TT.TOTAL_SHARES_OVER_ALLOTMENT_AUTHORIZED AS OVER_ALLOTMENT_AUTHORIZED_SHARES,
    TT.TOTAL_SHARES_OVER_ALLOTMENT_EXERCISED AS OVER_ALLOTMENT_EXERCISED_SHARES,
    CAST(TT.FIRST_TRADE_DATE AS TIMESTAMP(6)) AS FIRST_TRADE_TS,
    CAST(TT.MANAGERS_LOCKUP_DATE AS TIMESTAMP(6)) AS LOCKUP_TS
FROM (
    SELECT W.*
    FROM (
        SELECT TTR.*,
               ROW_NUMBER() OVER (PARTITION BY ETX.DEAL_TRANSACTION_ID,
                                               TTR.ECM_TRANSACTION_TRANCHE_ID
                                  ORDER BY TTR.ROWID) AS RN_
        FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE TTR
        JOIN (SELECT DISTINCT ECM_TRANSACTION_ID, DEAL_TRANSACTION_ID
              FROM DGSTREAM.OPUS_ECM_TRANSACTION) ETX
          ON ETX.ECM_TRANSACTION_ID = TTR.ECM_TRANSACTION_ID
    ) W
    WHERE W.RN_ = 1
) TT
INNER JOIN (
    SELECT X.*
    FROM (
        SELECT ET.ECM_TRANSACTION_ID, ET.DEAL_TRANSACTION_ID,
               ET.SYNDICATE_DEAL_NAME, ET.ISSUER_NAME_FROM_SOURCE,
               ET.ISSUER_GFCID, ET.ISSUER_TICKER, ET.ISSUER_LEID,
               ET.ISSUER_INDUSTRY_SECTOR,
               ET.USE_OF_PROCEEDS, ET.SETTLEMENT_CURRENCY_NAME,
               ET.PRODUCT_EQUITY_TYPE_VALUE,
               ROW_NUMBER() OVER (PARTITION BY ET.ECM_TRANSACTION_ID
                                  ORDER BY ET.ROWID) AS RN_
        FROM DGSTREAM.OPUS_ECM_TRANSACTION ET
    ) X
    WHERE X.RN_ = 1
) T
    ON TT.ECM_TRANSACTION_ID = T.ECM_TRANSACTION_ID
INNER JOIN (
    SELECT ECM_TRANSACTION_ID,
           MAX(STATUS_VALUE) AS STATUS_VALUE,
           MAX(STATUS_TYPE)  AS STATUS_TYPE
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_STATUS
    WHERE STATUS_TYPE = 'Execution_Status'
      AND STATUS_VALUE NOT IN ('Confidential', 'Withdrawn', 'Terminated')
    GROUP BY ECM_TRANSACTION_ID
) S
    ON T.ECM_TRANSACTION_ID = S.ECM_TRANSACTION_ID
LEFT JOIN (
    SELECT TRANSACTION_ID, MAX(DEAL_REGION) AS DEAL_REGION
    FROM DGSTREAM.OPUS_BASE_TRANSACTION
    GROUP BY TRANSACTION_ID
) OBT
    ON T.DEAL_TRANSACTION_ID = OBT.TRANSACTION_ID
LEFT JOIN (
    SELECT ECM_TRANSACTION_ID, ECM_TRANSACTION_TRANCHE_ID,
           MAX(SECURITY_TYPE_NAME) AS SECURITY_TYPE_NAME,
           MAX(EXCHANGE)           AS EXCHANGE
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL
    GROUP BY ECM_TRANSACTION_ID, ECM_TRANSACTION_TRANCHE_ID
) TPD
    ON TT.ECM_TRANSACTION_ID = TPD.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = TPD.ECM_TRANSACTION_TRANCHE_ID
LEFT JOIN (
    SELECT ECM_TRANSACTION_ID, ECM_TRANSACTION_TRANCHE_ID, CURRENCY_ID,
           MAX(CURRENCY_NAME) AS CURRENCY_NAME
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY
    GROUP BY ECM_TRANSACTION_ID, ECM_TRANSACTION_TRANCHE_ID, CURRENCY_ID
) TDC
    ON TT.ECM_TRANSACTION_ID = TDC.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = TDC.ECM_TRANSACTION_TRANCHE_ID
    AND TT.TRANCHE_CURRENCY_ID = TDC.CURRENCY_ID
LEFT JOIN (
    SELECT CURRENCY_ID, MAX(CURRENCY_NAME) AS CURRENCY_NAME
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_DEMAND_CURRENCY
    GROUP BY CURRENCY_ID
) GC
    ON GC.CURRENCY_ID = TT.TRANCHE_CURRENCY_ID
LEFT JOIN (
    SELECT
        S.ECM_TRANSACTION_ID,
        S.ECM_TRANSACTION_TRANCHE_ID,
        LISTAGG(S.SYNDICATE_MEMBER_NAME, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT) WITHIN GROUP (ORDER BY S.BND_BROKER DESC, S.SYNDICATE_MEMBER_NAME) AS SYNDICATE_MEMBER_NAME,
        LISTAGG(S.SYNDICATE_ROLE, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT) WITHIN GROUP (ORDER BY S.BND_BROKER DESC, S.SYNDICATE_MEMBER_NAME) AS SYNDICATE_ROLE,
        LISTAGG(S.BROKER_CODE, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT) WITHIN GROUP (ORDER BY S.BND_BROKER DESC, S.SYNDICATE_MEMBER_NAME) AS BROKER_CODE,
        LISTAGG(S.BND_BROKER, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT) WITHIN GROUP (ORDER BY S.BND_BROKER DESC, S.SYNDICATE_MEMBER_NAME) AS BND_BROKER,
        LISTAGG(CASE WHEN S.BND_BROKER = 'true' THEN S.SYNDICATE_MEMBER_NAME END, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT)
          WITHIN GROUP (ORDER BY S.SYNDICATE_MEMBER_NAME) AS BND_BANK
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_SYNDICATE S
    GROUP BY
        S.ECM_TRANSACTION_ID,
        S.ECM_TRANSACTION_TRANCHE_ID
) SYN
    ON TT.ECM_TRANSACTION_ID = SYN.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = SYN.ECM_TRANSACTION_TRANCHE_ID
LEFT JOIN (
    SELECT
        I.ECM_TRANSACTION_ID,
        I.ECM_TRANSACTION_TRANCHE_ID,
        LISTAGG(I.IDENTIFIER_TYPE, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT)
          WITHIN GROUP (ORDER BY I.IDENTIFIER_TYPE, I.IDENTIFIER_VALUE) AS IDENTIFIER_TYPE,
        LISTAGG(I.IDENTIFIER_VALUE, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT)
          WITHIN GROUP (ORDER BY I.IDENTIFIER_TYPE, I.IDENTIFIER_VALUE) AS IDENTIFIER_VALUE
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_PRODUCT_DETAIL_IDENTIFIER I
    GROUP BY
        I.ECM_TRANSACTION_ID,
        I.ECM_TRANSACTION_TRANCHE_ID
) IDN
    ON TT.ECM_TRANSACTION_ID = IDN.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = IDN.ECM_TRANSACTION_TRANCHE_ID
LEFT JOIN (
    SELECT
        S.ECM_TRANSACTION_ID,
        S.ECM_TRANSACTION_TRANCHE_ID,
        CASE
            WHEN COUNT(DISTINCT S.SYNDICATE_MEMBER_NAME) = 1
                AND MAX(S.SYNDICATE_MEMBER_NAME) LIKE '%Citigroup Global%'
            THEN 'SOLO'
            ELSE 'SHARED'
        END AS DEAL_SHARING_TYPE
    FROM DGSTREAM.OPUS_ECM_TRANSACTION_TRANCHE_SYNDICATE S
    GROUP BY
        S.ECM_TRANSACTION_ID,
        S.ECM_TRANSACTION_TRANCHE_ID
) DST
    ON TT.ECM_TRANSACTION_ID = DST.ECM_TRANSACTION_ID
    AND TT.ECM_TRANSACTION_TRANCHE_ID = DST.ECM_TRANSACTION_TRANCHE_ID

LEFT JOIN (
    SELECT GFCID, MAX(NAME) AS ISSUER_NAME_BY_GFCID
    FROM DGSTREAM.OB_DEAL_ISSUER
    WHERE GFCID IS NOT NULL AND NAME IS NOT NULL
    GROUP BY GFCID
) OIN
    ON OIN.GFCID = T.ISSUER_GFCID

LEFT JOIN (
    SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER
    FROM (
        SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER,
               ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID
                                  ORDER BY PUBLISHED_TS DESC) AS RN_
        FROM DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES
        WHERE PARTY_ROLE = 'Primary Client'
    ) WHERE RN_ = 1
) PCM
    ON PCM.TRANSACTION_ID = T.DEAL_TRANSACTION_ID

UNION ALL

SELECT
    'DCM' AS PRODUCT,
    ODT.DEAL_ID AS DEAL_ID,
    ODT.DEAL_NAME AS DEAL_NAME,
    NVL(PCM.PARTY_NAME, ODI.NAME) AS ISSUER_NAME,
    NVL(PCM.PARTY_GFCID, ODI.GFCID) AS GFCID,
    NVL(PCM.PARTY_TICKER, ODI.TICKER) AS TICKER,
    ODT.ISSUER_SECTOR AS SECTOR,
    ODT.REGION AS DEAL_REGION,
    ODT.TRANCHE_ID AS TRANCHE_ID,
    ODT.NAME AS TRANCHE_NAME,
    CASE WHEN ODT.TRANCHE_SIZE IS NULL THEN 0
         WHEN REGEXP_LIKE(ODT.TRANCHE_SIZE,
                          '^\s*[+-]?[0-9]+(\.[0-9]+)?([Ee][+-]?[0-9]+)?\s*$')
         THEN TO_NUMBER(TRIM(ODT.TRANCHE_SIZE))
         ELSE NULL END AS TRANCHE_SIZE,
    ODT.PRICING_TS AS PRICING_TS,
    ODT.CURRENCY AS CURRENCY,
    ODT.TRANCHE_REGION AS TRANCHE_REGION,
    ODT.PRODUCT_CLASS AS PRODUCT_CLASS,
    ODT.SENIORITY AS SENIORITY,
    ODT.REG_CATEGORY AS REG_CATEGORY,
    ODT.ESG_BOND AS ESG_BOND,
    ODT.COUPON_TYPE AS COUPON_TYPE,
    ODT.COUPON_FREQ AS COUPON_FREQ,
    ODT.USE_OF_PROCEEDS AS USE_OF_PROCEEDS,
    CAST(NULL AS VARCHAR2(4000)) AS PRODUCT_TYPE,
    CAST(NULL AS VARCHAR2(4000)) AS EXCHANGE,
    ODT.SETTLEMENT_CURRENCY AS SETTLEMENT_CURRENCY,
    ODT.STATUS AS TRANCHE_STATUS,
    ODT.STATUS AS DEAL_STATUS,
    CAST(NULL AS VARCHAR2(4000)) AS EXECUTION_STATUS,
    NVL(SYNM.SYNDICATE_MEMBER_NAME, ODT.BD_BANK) AS SYNDICATE_MEMBER_NAME,
    CAST(NULL AS VARCHAR2(4000)) AS SYNDICATE_ROLE,
    CAST(NULL AS VARCHAR2(4000)) AS BROKER_CODE,
    CASE
        WHEN ODT.BD_BANK LIKE '%Citigroup Global%'
        THEN 'true'
        ELSE 'false'
    END AS BND_BROKER,
    ODT.BD_BANK AS BND_BANK,
    IDN.IDENTIFIER_TYPE AS IDENTIFIER_TYPE,
    IDN.IDENTIFIER_VALUE AS IDENTIFIER_VALUE,
    IDN.DELIVERY_TYPE AS DELIVERY_TYPE,
    RAT.ISSUER_RATINGS AS ISSUER_RATINGS,
    CASE WHEN ODT.TENOR_VALUE IS NULL AND ODT.TENOR_PERIOD IS NULL
         THEN NULL
         ELSE ODT.TENOR_VALUE || '-' || ODT.TENOR_PERIOD
    END AS TENORS,
    ODT.MATURITY_DATE AS SECURITIES_MATURITY,
    NVL(DST.DEAL_SHARING_TYPE, 'SHARED') AS DEAL_SHARING_TYPE,
    CAST(NULL AS VARCHAR2(4000)) AS EQUITY_TYPE,
    CAST(ODT.SETTLEMENT_DATE AS TIMESTAMP(6)) AS SETTLEMENT_TS,
    ODT.ORIGINATION_TRANSACTION_ID AS TRANSACTION_ID,
    CAST(NULL AS VARCHAR2(200)) AS ISSUER_LEI,
    ODT.COUPON AS COUPON,
    ODT.YIELD AS YIELD,
    ODT.PRICE AS PRICE,
    ODT.PRICE_GUIDANCE AS PRICE_GUIDANCE,
    ODT.ORDER_BOOK_SIZE_USD AS ORDER_BOOK_SIZE_USD,
    ODT.TOTAL_FEE AS TOTAL_FEE,
    ODT.UNDERWRITING_FEE AS UNDERWRITING_FEE,
    ODT.MANAGEMENT_FEES AS MANAGEMENT_FEES,
    ODT.SELLING_CONSESSION_FEE AS SELLING_CONCESSION_FEE,
    ODT.PRAECIPIUM_FEES AS PRAECIPIUM_FEES,
    ODT.RETAIL_UW_FEE AS RETAIL_UW_FEE,
    CAST(ODT.ANNOUNCEMENT_DATE AS TIMESTAMP(6)) AS ANNOUNCEMENT_TS,
    CAST(ODT.ISSUE_DATE AS TIMESTAMP(6)) AS ISSUE_TS,
    CAST(ODT.TRADE_DATE AS TIMESTAMP(6)) AS TRADE_TS,
    ODT.TARGET_MARKET AS TARGET_MARKET,
    ODT.FRN_COUPON_INDEX AS FRN_COUPON_INDEX,
    CAST(NULL AS NUMBER) AS GROSS_SPREAD_PER_FEE,
    CAST(NULL AS NUMBER) AS DESIGNATION_FEE,
    CAST(NULL AS NUMBER) AS OVER_ALLOTMENT_AUTHORIZED_SHARES,
    CAST(NULL AS NUMBER) AS OVER_ALLOTMENT_EXERCISED_SHARES,
    CAST(NULL AS TIMESTAMP(6)) AS FIRST_TRADE_TS,
    CAST(NULL AS TIMESTAMP(6)) AS LOCKUP_TS
FROM (
    SELECT V.*
    FROM (
        SELECT DTR.*,
               ROW_NUMBER() OVER (PARTITION BY DTR.DEAL_ID, DTR.TRANCHE_ID
                                  ORDER BY DTR.ROWID) AS RN_
        FROM DGSTREAM.OB_DEAL_TRANCHE DTR
    ) V
    WHERE V.RN_ = 1
) ODT
LEFT JOIN (
    SELECT Z.*
    FROM (
        SELECT DI.DEAL_TRANCHE_ID, DI.NAME, DI.GFCID, DI.TICKER,
               ROW_NUMBER() OVER (PARTITION BY DI.DEAL_TRANCHE_ID
                                  ORDER BY DI.ROWID) AS RN_
        FROM DGSTREAM.OB_DEAL_ISSUER DI
    ) Z
    WHERE Z.RN_ = 1
) ODI
    ON ODI.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
LEFT JOIN (
    SELECT M.DEAL_TRANCHE_ID,
           LISTAGG(M.SYNDICATE_MEMBER_NAME, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT)
             WITHIN GROUP (ORDER BY M.SYNDICATE_MEMBER_NAME) AS SYNDICATE_MEMBER_NAME
    FROM (
        SELECT DISTINCT S.DEAL_TRANCHE_ID, S.SYNDICATE_MEMBER_NAME
        FROM DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER S
        WHERE S.SYNDICATE_MEMBER_NAME IS NOT NULL
    ) M
    GROUP BY M.DEAL_TRANCHE_ID
) SYNM
    ON SYNM.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
LEFT JOIN (
    SELECT
        T.DEAL_TRANCHE_ID,
        LISTAGG(T.TYPE, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT) WITHIN GROUP (ORDER BY T.TYPE, T.VALUE) AS IDENTIFIER_TYPE,
        LISTAGG(T.VALUE, ' | ' ON OVERFLOW TRUNCATE '...' WITH COUNT) WITHIN GROUP (ORDER BY T.TYPE, T.VALUE) AS IDENTIFIER_VALUE,
        MAX(T.DELIVERY_TYPE) AS DELIVERY_TYPE
    FROM DGSTREAM.OB_TRANCHE T
    GROUP BY T.DEAL_TRANCHE_ID
) IDN
    ON IDN.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
LEFT JOIN (
    SELECT
        R.DEAL_TRANCHE_ID,
        LISTAGG(R.AGENCY || ' - ' || R.VALUE ||
                CASE WHEN R.OUTLOOK IS NOT NULL
                     THEN '(' || R.OUTLOOK || ')' END, ', ' ON OVERFLOW TRUNCATE '...' WITH COUNT)
            WITHIN GROUP (ORDER BY R.AGENCY) AS ISSUER_RATINGS
    FROM DGSTREAM.OB_TRANCHE_RATING R
    GROUP BY R.DEAL_TRANCHE_ID
) RAT
    ON RAT.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
LEFT JOIN (
    SELECT
        S.DEAL_TRANCHE_ID,
        CASE
            WHEN MIN(S.DEALER) = MAX(S.DEALER)
                AND MIN(S.DEALER) LIKE '%Citigroup Global%'
            THEN 'SOLO'
            ELSE 'SHARED'
        END AS DEAL_SHARING_TYPE
    FROM DGSTREAM.OB_TRANCHE_SYNDICATE_MEMBER S
    GROUP BY S.DEAL_TRANCHE_ID
) DST
    ON DST.DEAL_TRANCHE_ID = ODT.DEAL_ID || '-' || ODT.TRANCHE_ID
LEFT JOIN (
    SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER
    FROM (
        SELECT TRANSACTION_ID, PARTY_NAME, PARTY_GFCID, PARTY_TICKER,
               ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID
                                  ORDER BY PUBLISHED_TS DESC) AS RN_
        FROM DGSTREAM.OPUS_BASE_TRANSACTION_RELATED_PARTIES
        WHERE PARTY_ROLE = 'Primary Client'
    ) WHERE RN_ = 1
) PCM
    ON PCM.TRANSACTION_ID = ODT.ORIGINATION_TRANSACTION_ID
;
GRANT SELECT ON "DGSTREAM"."VW_TRANCHE_SUMMARY" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRANCHE_SUMMARY" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRANCHE_SUMMARY" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRANCHE_SUMMARY" TO "DGLOBE" WITH GRANT OPTION;
