CREATE OR REPLACE VIEW "DGSTREAM"."VW_TRADE_SYNDICATE" AS
SELECT
    'DCM' AS PRODUCT,
    S.ORDER_TRADE_ID AS TRADE_ID,
    S.DEALER AS DEALER,
    S.DESIGNATION_AMT AS DESIGNATION_AMT,
    S.ADJUSTED_DESIGNATION_AMT AS ADJUSTED_DESIGNATION_AMT,
    S.ADJUSTED_DESIGNATION_PCT AS ADJUSTED_DESIGNATION_PCT,
    S.CARVEOUT_AMT AS CARVEOUT_AMT,
    S.DISTRIBUTED_CARVEOUT AS DISTRIBUTED_CARVEOUT
FROM (
    SELECT W.*
    FROM (
        SELECT TS.*,
               ROW_NUMBER() OVER (PARTITION BY TS.ORDER_TRADE_ID, TS.DEALER
                                  ORDER BY TS.DG_UPDATED_TS DESC NULLS LAST,
                                           TS.ROWID) AS RN_
        FROM DGSTREAM.OB_ORDER_TRADE_SYNDICATE TS
        WHERE TS.ORDER_TRADE_ID IS NOT NULL
    ) W
    WHERE W.RN_ = 1
) S
;
GRANT SELECT ON "DGSTREAM"."VW_TRADE_SYNDICATE" TO "DGLOBE_ORAAS_TABLEAU_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRADE_SYNDICATE" TO "DGLOBE_ORAAS_RO_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRADE_SYNDICATE" TO "DGLOBE_TABLEAU_RESTRICTED_ROLE";
GRANT SELECT ON "DGSTREAM"."VW_TRADE_SYNDICATE" TO "DGLOBE" WITH GRANT OPTION;
